local NetEventName = {}

NetEventName[0] = "OBJECT_ID_FREED"

NetEventName[1] = "OBJECT_ID_REQUEST"

NetEventName[2] = "ARRAY_DATA_VERIFY"

NetEventName[3] = "SCRIPT_ARRAY_DATA_VERIFY"

NetEventName[4] = "REQUEST_CONTROL"

NetEventName[5] = "GIVE_CONTROL"

NetEventName[6] = "WEAPON_DAMAGE"

NetEventName[7] = "REQUEST_PICKUP"

NetEventName[8] = "REQUEST_MAP_PICKUP"

NetEventName[9] = "GAME_CLOCK"

NetEventName[10] = "GAME_WEATHER"

NetEventName[11] = "RESPAWN_PLAYER_PED"

NetEventName[12] = "GIVE_WEAPON"

NetEventName[13] = "REMOVE_WEAPON"

NetEventName[14] = "REMOVE_ALL_WEAPONS"

NetEventName[15] = "VEHICLE_COMPONENT_CONTROL"

NetEventName[16] = "FIRE"

NetEventName[17] = "EXPLOSION"

NetEventName[18] = "START_PROJECTILE"

NetEventName[19] = "UPDATE_PROJECTILE_TARGET"

NetEventName[20] = "REMOVE_PROJECTILE_ENTITY"

NetEventName[21] = "BREAK_PROJECTILE_TARGET_LOCK"

NetEventName[22] = "ALTER_WANTED_LEVEL"

NetEventName[23] = "CHANGE_RADIO_STATION"

NetEventName[24] = "RAGDOLL_REQUEST"

NetEventName[25] = "PLAYER_TAUNT"

NetEventName[26] = "PLAYER_CARD_STAT"

NetEventName[27] = "DOOR_BREAK"

NetEventName[28] = "SCRIPTED_GAME"

NetEventName[29] = "REMOTE_SCRIPT_INFO"

NetEventName[30] = "REMOTE_SCRIPT_LEAVE"

NetEventName[31] = "MARK_AS_NO_LONGER_NEEDED"

NetEventName[32] = "CONVERT_TO_SCRIPT_ENTITY"

NetEventName[33] = "SCRIPT_WORLD_STATE"

NetEventName[34] = "CLEAR_AREA"

NetEventName[35] = "CLEAR_RECTANGLE_AREA"

NetEventName[36] = "NETWORK_REQUEST_SYNCED_SCENE"

NetEventName[37] = "NETWORK_START_SYNCED_SCENE"

NetEventName[38] = "NETWORK_STOP_SYNCED_SCENE"

NetEventName[39] = "NETWORK_UPDATE_SYNCED_SCENE"

NetEventName[40] = "INCIDENT_ENTITY"

NetEventName[41] = "GIVE_PED_SCRIPTED_TASK"

NetEventName[42] = "GIVE_PED_SEQUENCE_TASK"

NetEventName[43] = "NETWORK_CLEAR_PED_TASKS"

NetEventName[44] = "NETWORK_START_PED_ARREST"

NetEventName[45] = "NETWORK_START_PED_UNCUFF"

NetEventName[46] = "NETWORK_SOUND_CAR_HORN"

NetEventName[47] = "NETWORK_ENTITY_AREA_STATUS"

NetEventName[48] = "NETWORK_GARAGE_OCCUPIED_STATUS"

NetEventName[49] = "PED_CONVERSATION_LINE"

NetEventName[50] = "SCRIPT_ENTITY_STATE_CHANGE"

NetEventName[51] = "NETWORK_PLAY_SOUND"

NetEventName[52] = "NETWORK_STOP_SOUND"

NetEventName[53] = "NETWORK_PLAY_AIRDEFENSE_FIRE"

NetEventName[54] = "NETWORK_BANK_REQUEST"

NetEventName[55] = "NETWORK_AUDIO_BARK"

NetEventName[56] = "REQUEST_DOOR"

NetEventName[57] = "NETWORK_TRAIN_REPORT"

NetEventName[58] = "NETWORK_TRAIN_REQUEST"

NetEventName[59] = "NETWORK_INCREMENT_STAT"

NetEventName[60] = "MODIFY_VEHICLE_LOCK_WORD_STATE_DATA"

NetEventName[61] = "MODIFY_PTFX_WORD_STATE_DATA_SCRIPTED_EVOLVE"

NetEventName[62] = "REQUEST_PHONE_EXPLOSION"

NetEventName[63] = "REQUEST_DETACHMENT"

NetEventName[64] = "KICK_VOTES"

NetEventName[65] = "GIVE_PICKUP_REWARDS"

NetEventName[66] = "NETWORK_CRC_HASH_CHECK"

NetEventName[67] = "BLOW_UP_VEHICLE"

NetEventName[68] = "NETWORK_SPECIAL_FIRE_EQUIPPED_WEAPON"

NetEventName[69] = "NETWORK_RESPONDED_TO_THREAT"

NetEventName[70] = "NETWORK_SHOUT_TARGET_POSITION"

NetEventName[71] = "VOICE_DRIVEN_MOUTH_MOVEMENT_FINISHED"

NetEventName[72] = "PICKUP_DESTROYED"

NetEventName[73] = "UPDATE_PLAYER_SCARS"

NetEventName[74] = "NETWORK_CHECK_EXE_SIZE"

NetEventName[75] = "NETWORK_PTFX"

NetEventName[76] = "NETWORK_PED_SEEN_DEAD_PED"

NetEventName[77] = "REMOVE_STICKY_BOMB"

NetEventName[78] = "NETWORK_CHECK_CODE_CRCS"

NetEventName[79] = "INFORM_SILENCED_GUNSHOT"

NetEventName[80] = "PED_PLAY_PAIN"

NetEventName[81] = "CACHE_PLAYER_HEAD_BLEND_DATA"

NetEventName[82] = "REMOVE_PED_FROM_PEDGROUP"

NetEventName[83] = "REPORT_MYSELF"

NetEventName[84] = "REPORT_CASH_SPAWN"

NetEventName[85] = "ACTIVATE_VEHICLE_SPECIAL_ABILITY"

NetEventName[86] = "BLOCK_WEAPON_SELECTION"

NetEventName[87] = "NETWORK_CHECK_CATALOG_CRC"

return NetEventName