local NetEventName = {}

NetEventName[0] = "OBJECT_ID_FREED_EVENT"

NetEventName[1] = "OBJECT_ID_REQUEST_EVENT"

NetEventName[2] = "ARRAY_DATA_VERIFY_EVENT"

NetEventName[3] = "SCRIPT_ARRAY_DATA_VERIFY_EVENT"

NetEventName[4] = "REQUEST_CONTROL_EVENT"

NetEventName[5] = "GIVE_CONTROL_EVENT"

NetEventName[6] = "WEAPON_DAMAGE_EVENT"

NetEventName[7] = "REQUEST_PICKUP_EVENT"

NetEventName[8] = "REQUEST_MAP_PICKUP_EVENT"

NetEventName[9] = "GAME_CLOCK_EVENT"

NetEventName[10] = "GAME_WEATHER_EVENT"

NetEventName[11] = "RESPAWN_PLAYER_PED_EVENT"

NetEventName[12] = "GIVE_WEAPON_EVENT"

NetEventName[13] = "REMOVE_WEAPON_EVENT"

NetEventName[14] = "REMOVE_ALL_WEAPONS_EVENT"

NetEventName[15] = "VEHICLE_COMPONENT_CONTROL_EVENT"

NetEventName[16] = "FIRE_EVENT"

NetEventName[17] = "EXPLOSION_EVENT"

NetEventName[18] = "START_PROJECTILE_EVENT"

NetEventName[19] = "UPDATE_PROJECTILE_TARGET_EVENT"

NetEventName[20] = "REMOVE_PROJECTILE_ENTITY_EVENT"

NetEventName[21] = "BREAK_PROJECTILE_TARGET_LOCK_EVENT"

NetEventName[22] = "ALTER_WANTED_LEVEL_EVENT"

NetEventName[23] = "CHANGE_RADIO_STATION_EVENT"

NetEventName[24] = "RAGDOLL_REQUEST_EVENT"

NetEventName[25] = "PLAYER_TAUNT_EVENT"

NetEventName[26] = "PLAYER_CARD_STAT_EVENT"

NetEventName[27] = "DOOR_BREAK_EVENT"

NetEventName[28] = "SCRIPTED_GAME_EVENT"

NetEventName[29] = "REMOTE_SCRIPT_INFO_EVENT"

NetEventName[30] = "REMOTE_SCRIPT_LEAVE_EVENT"

NetEventName[31] = "MARK_AS_NO_LONGER_NEEDED_EVENT"

NetEventName[32] = "CONVERT_TO_SCRIPT_ENTITY_EVENT"

NetEventName[33] = "SCRIPT_WORLD_STATE_EVENT"

NetEventName[34] = "CLEAR_AREA_EVENT"

NetEventName[35] = "CLEAR_RECTANGLE_AREA_EVENT"

NetEventName[36] = "NETWORK_REQUEST_SYNCED_SCENE_EVENT"

NetEventName[37] = "NETWORK_START_SYNCED_SCENE_EVENT"

NetEventName[38] = "NETWORK_STOP_SYNCED_SCENE_EVENT"

NetEventName[39] = "NETWORK_UPDATE_SYNCED_SCENE_EVENT"

NetEventName[40] = "INCIDENT_ENTITY_EVENT"

NetEventName[41] = "GIVE_PED_SCRIPTED_TASK_EVENT"

NetEventName[42] = "GIVE_PED_SEQUENCE_TASK_EVENT"

NetEventName[43] = "NETWORK_CLEAR_PED_TASKS_EVENT"

NetEventName[44] = "NETWORK_START_PED_ARREST_EVENT"

NetEventName[45] = "NETWORK_START_PED_UNCUFF_EVENT"

NetEventName[46] = "NETWORK_SOUND_CAR_HORN_EVENT"

NetEventName[47] = "NETWORK_ENTITY_AREA_STATUS_EVENT"

NetEventName[48] = "NETWORK_GARAGE_OCCUPIED_STATUS_EVENT"

NetEventName[49] = "PED_CONVERSATION_LINE_EVENT"

NetEventName[50] = "SCRIPT_ENTITY_STATE_CHANGE_EVENT"

NetEventName[51] = "NETWORK_PLAY_SOUND_EVENT"

NetEventName[52] = "NETWORK_STOP_SOUND_EVENT"

NetEventName[53] = "NETWORK_PLAY_AIRDEFENSE_FIRE_EVENT"

NetEventName[54] = "NETWORK_BANK_REQUEST_EVENT"

NetEventName[55] = "NETWORK_AUDIO_BARK_EVENT"

NetEventName[56] = "REQUEST_DOOR_EVENT"

NetEventName[57] = "NETWORK_TRAIN_REPORT_EVENT"

NetEventName[58] = "NETWORK_TRAIN_REQUEST_EVENT"

NetEventName[59] = "NETWORK_INCREMENT_STAT_EVENT"

NetEventName[60] = "MODIFY_VEHICLE_LOCK_WORD_STATE_DATA"

NetEventName[61] = "MODIFY_PTFX_WORD_STATE_DATA_SCRIPTED_EVOLVE_EVENT"

NetEventName[62] = "REQUEST_PHONE_EXPLOSION_EVENT"

NetEventName[63] = "REQUEST_DETACHMENT_EVENT"

NetEventName[64] = "KICK_VOTES_EVENT"

NetEventName[65] = "GIVE_PICKUP_REWARDS_EVENT"

NetEventName[66] = "NETWORK_CRC_HASH_CHECK_EVENT"

NetEventName[67] = "BLOW_UP_VEHICLE_EVENT"

NetEventName[68] = "NETWORK_SPECIAL_FIRE_EQUIPPED_WEAPON"

NetEventName[69] = "NETWORK_RESPONDED_TO_THREAT_EVENT"

NetEventName[70] = "NETWORK_SHOUT_TARGET_POSITION"

NetEventName[71] = "VOICE_DRIVEN_MOUTH_MOVEMENT_FINISHED_EVENT"

NetEventName[72] = "PICKUP_DESTROYED_EVENT"

NetEventName[73] = "UPDATE_PLAYER_SCARS_EVENT"

NetEventName[74] = "NETWORK_CHECK_EXE_SIZE_EVENT"

NetEventName[75] = "NETWORK_PTFX_EVENT"

NetEventName[76] = "NETWORK_PED_SEEN_DEAD_PED_EVENT"

NetEventName[77] = "REMOVE_STICKY_BOMB_EVENT"

NetEventName[78] = "NETWORK_CHECK_CODE_CRCS_EVENT"

NetEventName[79] = "INFORM_SILENCED_GUNSHOT_EVENT"

NetEventName[80] = "PED_PLAY_PAIN_EVENT"

NetEventName[81] = "CACHE_PLAYER_HEAD_BLEND_DATA_EVENT"

NetEventName[82] = "REMOVE_PED_FROM_PEDGROUP_EVENT"

NetEventName[83] = "REPORT_MYSELF_EVENT"

NetEventName[84] = "REPORT_CASH_SPAWN_EVENT"

NetEventName[85] = "ACTIVATE_VEHICLE_SPECIAL_ABILITY_EVENT"

NetEventName[86] = "BLOCK_WEAPON_SELECTION"

NetEventName[87] = "NETWORK_CHECK_CATALOG_CRC"

return NetEventName