local NetEventID = {}

NetEventID["OBJECT_ID_FREED_EVENT"] = 0

NetEventID["OBJECT_ID_REQUEST_EVENT"] = 1

NetEventID["ARRAY_DATA_VERIFY_EVENT"] = 2

NetEventID["SCRIPT_ARRAY_DATA_VERIFY_EVENT"] = 3

NetEventID["REQUEST_CONTROL_EVENT"] = 4

NetEventID["GIVE_CONTROL_EVENT"] = 5

NetEventID["WEAPON_DAMAGE_EVENT"] = 6

NetEventID["REQUEST_PICKUP_EVENT"] = 7

NetEventID["REQUEST_MAP_PICKUP_EVENT"] = 8

NetEventID["GAME_CLOCK_EVENT"] = 9

NetEventID["GAME_WEATHER_EVENT"] = 10

NetEventID["RESPAWN_PLAYER_PED_EVENT"] = 11

NetEventID["GIVE_WEAPON_EVENT"] = 12

NetEventID["REMOVE_WEAPON_EVENT"] = 13

NetEventID["REMOVE_ALL_WEAPONS_EVENT"] = 14

NetEventID["VEHICLE_COMPONENT_CONTROL_EVENT"] = 15

NetEventID["FIRE_EVENT"] = 16

NetEventID["EXPLOSION_EVENT"] = 17

NetEventID["START_PROJECTILE_EVENT"] = 18

NetEventID["UPDATE_PROJECTILE_TARGET_EVENT"] = 19

NetEventID["REMOVE_PROJECTILE_ENTITY_EVENT"] = 20

NetEventID["BREAK_PROJECTILE_TARGET_LOCK_EVENT"] = 21

NetEventID["ALTER_WANTED_LEVEL_EVENT"] = 22

NetEventID["CHANGE_RADIO_STATION_EVENT"] = 23

NetEventID["RAGDOLL_REQUEST_EVENT"] = 24

NetEventID["PLAYER_TAUNT_EVENT"] = 25

NetEventID["PLAYER_CARD_STAT_EVENT"] = 26

NetEventID["DOOR_BREAK_EVENT"] = 27

NetEventID["SCRIPTED_GAME_EVENT"] = 28

NetEventID["REMOTE_SCRIPT_INFO_EVENT"] = 29

NetEventID["REMOTE_SCRIPT_LEAVE_EVENT"] = 30

NetEventID["MARK_AS_NO_LONGER_NEEDED_EVENT"] = 31

NetEventID["CONVERT_TO_SCRIPT_ENTITY_EVENT"] = 32

NetEventID["SCRIPT_WORLD_STATE_EVENT"] = 33

NetEventID["CLEAR_AREA_EVENT"] = 34

NetEventID["CLEAR_RECTANGLE_AREA_EVENT"] = 35

NetEventID["NETWORK_REQUEST_SYNCED_SCENE_EVENT"] = 36

NetEventID["NETWORK_START_SYNCED_SCENE_EVENT"] = 37

NetEventID["NETWORK_STOP_SYNCED_SCENE_EVENT"] = 38

NetEventID["NETWORK_UPDATE_SYNCED_SCENE_EVENT"] = 39

NetEventID["INCIDENT_ENTITY_EVENT"] = 40

NetEventID["GIVE_PED_SCRIPTED_TASK_EVENT"] = 41

NetEventID["GIVE_PED_SEQUENCE_TASK_EVENT"] = 42

NetEventID["NETWORK_CLEAR_PED_TASKS_EVENT"] = 43

NetEventID["NETWORK_START_PED_ARREST_EVENT"] = 44

NetEventID["NETWORK_START_PED_UNCUFF_EVENT"] = 45

NetEventID["NETWORK_SOUND_CAR_HORN_EVENT"] = 46

NetEventID["NETWORK_ENTITY_AREA_STATUS_EVENT"] = 47

NetEventID["NETWORK_GARAGE_OCCUPIED_STATUS_EVENT"] = 48

NetEventID["PED_CONVERSATION_LINE_EVENT"] = 49

NetEventID["SCRIPT_ENTITY_STATE_CHANGE_EVENT"] = 50

NetEventID["NETWORK_PLAY_SOUND_EVENT"] = 51

NetEventID["NETWORK_STOP_SOUND_EVENT"] = 52

NetEventID["NETWORK_PLAY_AIRDEFENSE_FIRE_EVENT"] = 53

NetEventID["NETWORK_BANK_REQUEST_EVENT"] = 54

NetEventID["NETWORK_AUDIO_BARK_EVENT"] = 55

NetEventID["REQUEST_DOOR_EVENT"] = 56

NetEventID["NETWORK_TRAIN_REPORT_EVENT"] = 57

NetEventID["NETWORK_TRAIN_REQUEST_EVENT"] = 58

NetEventID["NETWORK_INCREMENT_STAT_EVENT"] = 59

NetEventID["MODIFY_VEHICLE_LOCK_WORD_STATE_DATA"] = 60

NetEventID["MODIFY_PTFX_WORD_STATE_DATA_SCRIPTED_EVOLVE_EVENT"] = 61

NetEventID["REQUEST_PHONE_EXPLOSION_EVENT"] = 62

NetEventID["REQUEST_DETACHMENT_EVENT"] = 63

NetEventID["KICK_VOTES_EVENT"] = 64

NetEventID["GIVE_PICKUP_REWARDS_EVENT"] = 65

NetEventID["NETWORK_CRC_HASH_CHECK_EVENT"] = 66

NetEventID["BLOW_UP_VEHICLE_EVENT"] = 67

NetEventID["NETWORK_SPECIAL_FIRE_EQUIPPED_WEAPON"] = 68

NetEventID["NETWORK_RESPONDED_TO_THREAT_EVENT"] = 69

NetEventID["NETWORK_SHOUT_TARGET_POSITION"] = 70

NetEventID["VOICE_DRIVEN_MOUTH_MOVEMENT_FINISHED_EVENT"] = 71

NetEventID["PICKUP_DESTROYED_EVENT"] = 72

NetEventID["UPDATE_PLAYER_SCARS_EVENT"] = 73

NetEventID["NETWORK_CHECK_EXE_SIZE_EVENT"] = 74

NetEventID["NETWORK_PTFX_EVENT"] = 75

NetEventID["NETWORK_PED_SEEN_DEAD_PED_EVENT"] = 76

NetEventID["REMOVE_STICKY_BOMB_EVENT"] = 77

NetEventID["NETWORK_CHECK_CODE_CRCS_EVENT"] = 78

NetEventID["INFORM_SILENCED_GUNSHOT_EVENT"] = 79

NetEventID["PED_PLAY_PAIN_EVENT"] = 80

NetEventID["CACHE_PLAYER_HEAD_BLEND_DATA_EVENT"] = 81

NetEventID["REMOVE_PED_FROM_PEDGROUP_EVENT"] = 82

NetEventID["REPORT_MYSELF_EVENT"] = 83

NetEventID["REPORT_CASH_SPAWN_EVENT"] = 84

NetEventID["ACTIVATE_VEHICLE_SPECIAL_ABILITY_EVENT"] = 85

NetEventID["BLOCK_WEAPON_SELECTION"] = 86

NetEventID["NETWORK_CHECK_CATALOG_CRC"] = 87

return NetEventID