--Please ignore the comments
--Do not touch "/n"

--V1.6.0 [add ln.43~ln.45]

Translate = {
    ["sG.wolf's script public version"] = "sG.wolf's script public version", 
    ["sG.wolf's script public ver"] = "sG.wolf's script public ver",
    ["sG.wolf's script loading"] = "sG.wolf's script loading",
    ["Copyright(C)2021 sG.wolf all rights reserved."] = "Copyright(C)2021 sG.wolf all rights reserved.",
    ["sG.wolf script"] = "sG.wolf script",
    ["Mark all as modder"] = "Mark all as modder", --modder flag
    ["self"] = "self", --self option
    ["SOON"] = "SOON", 
    ["weapon"] = "weapon", --weapon option
    ["sight Airstrike"] = "sight Airstrike",
    ["sight RailGun"] = "sight RailGun",
    ["Airstrike Gun"] = "Airstrike Gun",
    ["chat"] = "chat", --chat option
    ["chat spammer"] = "chat spammer",
    ["chat preset(default)"] = "chat preset(default)",
    ["'Fuck you Chinese!' MassSpam"] = "'Fuck you Chinese!' MassSpam",
    ["'2TAKE1 GOD.' MassSpam"] = "'2TAKE1 GOD.' MassSpam",
    ["'FUCK YOU!' MassSpam"] = "'FUCK YOU!' MassSpam",
    ["'LOVE ME!' MassSpam"] = "'LOVE ME!' MassSpam",
    ["'FUCK YOU!' Spam"] = "'FUCK YOU!' Spam",
    ["'YOU SUCK' Spam"] = "'YOU SUCK' Spam",
    ["'Fuck you Chinese!' Spam"] = "'Fuck you Chinese!' Spam",
    ["'Empty' Message Spam"] = "'Empty' Message Spam",
    ["custom chat spammer"] = "custom chat spammer",
    ["Enter Chat Message"] = "Enter Chat Message", --input window
    ["clipbord chat spammer"] = "clipbord chat spammer",
    ["spam 'preset 1'"] = "spam 'preset 1'",
    ["spam 'preset 2'"] = "spam 'preset 2'",
    ["spam 'preset 3'"] = "spam 'preset 3'",
    ["spam 'preset 4'"] = "spam 'preset 4'",
    ["protex"] = "protex", --protection option
    ["Mark all Players as Modder"] = "Mark all Players as Modder",
    ["Unmark all Players as Modder"] = "Unmark all Players as Modder",
    ["Safe Space(anti-crash-cam)"] = "Safe Space(anti-crash-cam)",
    ["Here is safe space!"] = "Here is safe space!",
    ["Wait a sec"] = "Wait a sec",
    ["Frame Drop Protection"] = "Frame Drop Protection",
    ["Auto Anti-Crash Cam ACTIVATED!"] = "Auto Anti-Crash Cam ACTIVATED!",
    ["If you want to turn off the anti-crash cam,\nplease turn it off manually"] = "If you want to turn off the anti-crash cam,\nplease turn it off manually",
    ["Teleport"] = "Teleport", --teleport option
    ["auto teleport to Waypoint"] = "auto teleport to Waypoint",
    ["I can't get the coordinates of the ground :(("] = "I can't get the coordinates of the ground :((",
    ["I'll teleport to the sky :)"] = "I'll teleport to the sky :)",
    ["Teleported"] = "Teleported",
    ["Random Pos Teleport"] = "Random Pos Teleport",
    ["Custom Teleport"] = "Custom Teleport",
    ["Removed\nPlease Reload Custom Teleport Location"] = "Removed\nPlease Reload Custom Teleport Location",
    ["Remove"] = "Remove",
    ["Add Custom Teleport Location(Current Location)"] = "Add Custom Teleport Location(Current Location)",
    ["Enter Preset Name"] = "Enter Preset Name", --input window
    ["done"] = "done",
    ["The maximum number of presets is 100.\nPlease delete some presets and try again"] = "The maximum number of presets is 100.\nPlease delete some presets and try again",
    ["[Developing]Add Custom Teleport Location(Input Location)"] = "[Developing]Add Custom Teleport Location(Input Location)",
    ["Reload Custom Teleport Location"] = "Reload Custom Teleport Location",
    ["Reload Done"] = "Reload Done",
    ["vehicle"] = "vehicle", --vehicle option
    ["Vehicle missale rapid fire"] = "Vehicle missale rapid fire",
    ["Fast"] = "Fast",
    ["Normal"] = "Normal",
    ["Slow"] = "Slow",
    ["SCID"] = "SCID", --SCID option
    ["SAVE SCID(RID)[TXT file]"] = "SAVE SCID(RID)[TXT file]",
    ["start saving scid\n\n"] = "start saving scid\n\n",
    ["start saving scid"] = "start saving scid",
    ["\nended saving scid\n\n\n"] = "\nended saving scid\n\n\n",
    ["scid save ended"] = "scid save ended",
    ["2take1 appdata - scripts - sG.wolf's_script - scid.txt"] = "2take1 appdata - scripts - sG.wolf's_script - scid.txt",
    ["SAVE SCID(RID)[Hex][TXT file]"] = "SAVE SCID(RID)[Hex][TXT file]",
    ["start saving scid(hex)\n\n"] = "start saving scid(hex)\n\n",
    ["start saving scid(hex)"] = "start saving scid(hex)",
    ["\nended saving scid(hex)\n\n\n"] = "\nended saving scid(hex)\n\n\n",
    ["scid save ended(hex)"] = "scid save ended(hex)",
    ["Add as fakefriends(all session player)"] = "Add as fakefriends(all session player)",
    ["add as fakefriends ended"] = "add as fakefriends ended",
    ["please re-inject menu"] = "please re-inject menu",
    ["Misc"] = "Misc", --misc option
    ["Player log[WIP]"] = "Player log[WIP]",
    ["copy SCID"] = "copy SCID",
    ["int"] = "int",
    ["hex"] = "hex",
    ["Squid Game"] = "Squid Game",
    ["Red Light, Green Light"] = "Red Light, Green Light",
    ["Red Light! DON'T MOVE!!!"] = "Red Light! DON'T MOVE!!!",
    ["New player joined.\n The player will join the game at the next Red Light"] = "New player joined.\n The player will join the game at the next Red Light",
    ["Red Light"] = "Red Light",
    ["I can't kill "] = "I can't kill ",
    ["Green Light! Now you can move."] = "Green Light! Now you can move.",
    ["Green Light"] = "Green Light",
    ["Red"] = "Red",
    ["Green"] = "Green",
    ["ped Kill aura"] = "ped Kill aura",
    ["Player Kill aura"] = "Player Kill aura",
    ["Translation"] = "Translation", --Translate option
    ["Set default language"] = "Set default language",
    ["Please Reload This Script"] = "Please Reload This Script",
    ["Trolling"] = "Trolling",
    ["Railgun kill loop"] = "Railgun kill loop",
    ["player lock-on(local ped)"] = "player lock-on(local ped)",
    ["set Waypoint"] = "set Waypoint",
    ["check version"] = "check version",
    ["Developer"] = "Developer",
    ["Special thanks to"] = "Special thanks to",
    ["sG.wolf's script loaded"] = "sG.wolf's script loaded"
}

--DO NOT TOUCH THIS!!!
return Translate