--Please ignore the comments
--Do not touch "/n"

--V1.6.0 [add ln.43~ln.45]

Translate = {
    ["sG.wolf's script public version"] = "sG.wolf's Script Public", 
    ["sG.wolf's script public ver"] = "sG.wolf's Script Public",
    ["sG.wolf's script loading"] = "sG.wolf's Script 인젝 중..",
    ["Copyright(C)2021 sG.wolf all rights reserved."] = "Copyright(C)2021 sG.wolf all rights reserved.(저작권자 표시)",
    ["sG.wolf script"] = "sG.wolf Script",
    ["Mark all as modder"] = "모두를 모더체킹하기", --modder flag
    ["self"] = "셀프", --self option
    ["SOON"] = "SOON", 
    ["weapon"] = "무기", --weapon option
    ["sight Airstrike"] = "시점에 공중폭격",
    ["sight RailGun"] = "시점에 레일건",
    ["Airstrike Gun"] = "공중폭격 총",
    ["chat"] = "채팅", --chat option
    ["chat spammer"] = "채팅 스팸",
    ["chat preset(default)"] = "기본 채팅 프리셋",
    ["'Fuck you Chinese!' MassSpam"] = "'Fuck you Chinese!' 큰 메시지 스팸",
    ["'2TAKE1 GOD.' MassSpam"] = "'2TAKE1 GOD.' 큰 메시지 스팸",
    ["'FUCK YOU!' MassSpam"] = "'FUCK YOU!' 큰 메시지 스팸",
    ["'LOVE ME!' MassSpam"] = "'LOVE ME!' 큰 메시지 스팸",
    ["'FUCK YOU!' Spam"] = "'FUCK YOU!' 스팸",
    ["'YOU SUCK' Spam"] = "'YOU SUCK' 스팸",
    ["'Fuck you Chinese!' Spam"] = "'Fuck you Chinese!' 스팸",
    ["'Empty' Message Spam"] = "비어 있는 메시지 스팸",
    ["custom chat spammer"] = "커스텀 채팅 스팸",
    ["Enter Chat Message"] = "채팅 메시지 입력", --input window
    ["clipbord chat spammer"] = "채팅 스팸(클립보드)",
    ["spam 'preset 1'"] = "'Preset 1' 스팸",
    ["spam 'preset 2'"] = "'Preset 2' 스팸",
    ["spam 'preset 3'"] = "'Preset 3' 스팸",
    ["spam 'preset 4'"] = "'Preset 4' 스팸",
    ["protex"] = "프로텍션", --protection option
    ["Mark all Players as Modder"] = "모두를 모더체킹하기",
    ["Unmark all Players as Modder"] = "모두를 모더체킹 풀기",
    ["Safe Space(anti-crash-cam)"] = "크래쉬 방지 카메라",
    ["Here is safe space!"] = "안전한 위치로 이동했어요.",
    ["Wait a sec"] = "조금만 기다려 주세요.",
    ["Frame Drop Protection"] = "Frame Drop Protection",
    ["Auto Anti-Crash Cam ACTIVATED!"] = "Auto Anti-Crash Cam ACTIVATED!",
    ["If you want to turn off the anti-crash cam,\nplease turn it off manually"] = "If you want to turn off the anti-crash cam,\nplease turn it off manually",
    ["Teleport"] = "순간이동", --teleport option
    ["auto teleport to Waypoint"] = "경유지로 자동 텔레포트",
    ["I can't get the coordinates of the ground :(("] = "땅의 좌표를 찾을 수 없어요. :(",
    ["I'll teleport to the sky :)"] = "하늘로 이동할게요. :)",
    ["Teleported"] = "텔레포트를 완료했어요.",
    ["Random Pos Teleport"] = "무작위 위치로 이동",
    ["Custom Teleport"] = "커스텀 순간이동 위치",
    ["Removed\nPlease Reload Custom Teleport Location"] = "삭제 완료\n커스텀 순간이동 위치를 새로고침해 주세요.",
    ["Remove"] = "삭제",
    ["Add Custom Teleport Location(Current Location)"] = "커스텀 순간이동 위치 추가 [현재 위치]",
    ["Enter Preset Name"] = "이름 입력", --input window
    ["done"] = "완료",
    ["The maximum number of presets is 100.\nPlease delete some presets and try again"] = "커스텀 순간이동 위치는 100개까지 추가할 수 있어요.\n몇 개의 위치를 삭제하고 재시도해 보세요. :)",
    ["[Developing]Add Custom Teleport Location(Input Location)"] = "[개발중] 커스텀 순간이동 위치 추가 [좌표 입력]",
    ["Reload Custom Teleport Location"] = "커스텀 순간이동 위치 새로고침",
    ["Reload Done"] = "새로고침을 완료했어요.",
    ["vehicle"] = "차량", --vehicle option
    ["Vehicle missale rapid fire"] = "차량 무기 재장전 없음",
    ["Fast"] = "빠름",
    ["Normal"] = "일반",
    ["Slow"] = "느림",
    ["SCID"] = "SCID", --SCID option
    ["SCID Finder"] = "SCID Finder",
    ["Enter Username"] = "Enter Username",
    ["I can't find SCID"] = "I can't find SCID",
    ["Reason: \nInvalid Username or Server Error(https://eintim.one/ridapi.php)"] = "Reason: \nInvalid Username or Server Error(https://eintim.one/ridapi.php)",
    ["SCID copied!"] = "SCID copied!",
    ["SAVE SCID(RID)[TXT file]"] = "SCID 저장 [TXT 파일]",
    ["start saving scid\n\n"] = "SCID 저장 시작\n\n",
    ["start saving scid"] = "SCID 저장 시작",
    ["\nended saving scid\n\n\n"] = "\nSCID 저장을 완료했어요.\n\n\n",
    ["scid save ended"] = "SCID 저장을 완료했어요.",
    ["2take1 appdata - scripts - sG.wolf's_script - scid.txt"] = "저장위치: 2take1 appdata - scripts - sG.wolf's_script - scid.txt",
    ["SAVE SCID(RID)[Hex][TXT file]"] = "SCID 저장 [Hex] [TXT file]",
    ["start saving scid(hex)\n\n"] = "SCID 저장 시작 [hex]\n\n",
    ["start saving scid(hex)"] = "SCID 저장 시작 [hex]",
    ["\nended saving scid(hex)\n\n\n"] = "\nSCID 저장을 완료했어요. [hex]\n\n\n",
    ["scid save ended(hex)"] = "SCID 저장을 완료했어요. [hex]",
    ["Add as fakefriends(all session player)"] = "세션의 모두를 가짜 친구로 등록하기",
    ["add as fakefriends ended"] = "가짜 친구 등록을 완료했어요.",
    ["please re-inject menu"] = "2Take1을 재인젝해 주세요.",
    ["Misc"] = "기타", --misc option
    ["Player log[WIP]"] = "플레이어 로그 [베타]",
    ["copy SCID"] = "SCID 복사",
    ["int"] = "일반",
    ["hex"] = "16진수",
    ["Squid Game"] = "오징어 게임",
    ["Red Light, Green Light"] = "무궁화 꽃이 피었습니다",
    ["Red Light! DON'T MOVE!!!"] = "움직이지 마세요.",
    ["New player joined.\n The player will join the game at the next Red Light"] = " 새로운 플레이어가 참가했어요.\n 다음 '움직이지 마세요'라는 메시지가 나올 때 참가할 거에요.",
    ["Red Light"] = "움직이지 마세요.",
    ["I can't kill "] = "다음 플레이어를 죽일 수 없어요: ",
    ["Green Light! Now you can move."] = "이제 움직일 수 있어요.",
    ["Green Light"] = "이제 움직일 수 있어요.",
    ["Red"] = "이동 X",
    ["Green"] = "이동 O",
    ["Translation"] = "번역 by 나는 크롬.", --Translate option
    ["Set default language"] = "기본 언어 설정",
    ["Please Reload This Script"] = "스크립트를 재인젝 해주세요.",
    ["Trolling"] = "트롤링",
    ["Railgun kill loop"] = "레일건으로 죽이기 [반복]",
    ["player lock-on(local ped)"] = "플레이어 락온 [로컬 NPC]",
    ["set Waypoint"] = "경유지 설정",
    ["check version"] = "버전 확인",
    ["Developer"] = "개발자",
    ["Special thanks to"] = "제작에 기여한 사람들 :",
    ["sG.wolf's script loaded"] = "sG.wolf's Script 인젝 완료"
}

--DO NOT TOUCH THIS!!!
return Translate