--[[Sommaire
1 BOAT
2 COMMERCIAL
3 COMPACT
4 COMPACTS
5 COUPE
6 CYCLE
7 EMERGENCY
8 HELICOPTER
9 INDUSTRIAL
10 MILITARY
11 MOTORCYCLE
12 MUSCLE
13 OFF_ROAD
14 OPEN_WHEEL
15 PLANE
16 RAIL
17 SEDAN
18 SERVICE
19 SPORT
20 SPORT_CLASSIC
21 SUPER"
22 SUV
23 UTILITY
24 VAN]]
local Anger_vehicle = {}

local vehicles_data = {
    BOAT = {
        {ref_name="avisa", HEX_hash=0x9A474B5E, display_name="Avisa"},
        {ref_name="dinghy", HEX_hash=0x3D961290, display_name="Dinghy"},
        {ref_name="dinghy2", HEX_hash=0x107F392C, display_name="Dinghy"},
        {ref_name="dinghy3", HEX_hash=0x1E5E54EA, display_name="Dinghy"},
        {ref_name="dinghy4", HEX_hash=0x33B47F96, display_name="Dinghy"},
        {ref_name="dinghy5", HEX_hash=0xC58DA34A, display_name="Weaponized Dinghy"},
        {ref_name="jetmax", HEX_hash=0x33581161, display_name="Jetmax"},
        {ref_name="kosatka", HEX_hash=0x4FAF0D70, display_name="Kosatka"},
        {ref_name="longfin", HEX_hash=0x6EF89CCC, display_name="Longfin"},
        {ref_name="marquis", HEX_hash=0xC1CE1183, display_name="Marquis"},
        {ref_name="patrolboat", HEX_hash=0xEF813606, display_name="Kurtz 31 Patrol Boat"},
        {ref_name="predator", HEX_hash=0xE2E7D4AB, display_name="Police Predator"},
        {ref_name="seashark", HEX_hash=0xC2974024, display_name="Seashark"},
        {ref_name="seashark2", HEX_hash=0xDB4388E4, display_name="Seashark"},
        {ref_name="seashark3", HEX_hash=0xED762D49, display_name="Seashark"},
        {ref_name="speeder", HEX_hash=0xDC60D2B, display_name="Speeder"},
        {ref_name="speeder2", HEX_hash=0x1A144F2A, display_name="Speeder"},
        {ref_name="squalo", HEX_hash=0x17DF5EC2, display_name="Squalo"},
        {ref_name="submersible", HEX_hash=0x2DFF622F, display_name="Submersible"},
        {ref_name="submersible2", HEX_hash=0xC07107EE, display_name="Kraken"},
        {ref_name="suntrap", HEX_hash=0xEF2295C9, display_name="Suntrap "},
        {ref_name="toro", HEX_hash=0x3FD5AA2F, display_name="Toro"},
        {ref_name="toro2", HEX_hash=0x362CAC6D, display_name="Toro"},
        {ref_name="tropic", HEX_hash=0x1149422F, display_name="Tropic"},
        {ref_name="tropic2", HEX_hash=0x56590FE9, display_name="Tropic"},
        {ref_name="tug", HEX_hash=0x82CAC433, display_name="Tug"}
    },
    COMMERCIAL = {
        {ref_name="benson", HEX_hash=0x7A61B330, display_name="Benson"},
        {ref_name="biff", HEX_hash=0x32B91AE8, display_name="Biff"},
        {ref_name="cerberus", HEX_hash=0xD039510B, display_name="Apocalypse Cerberus"},
        {ref_name="cerberus2", HEX_hash=0x287FA449, display_name="Future Shock Cerberus"},
        {ref_name="cerberus3", HEX_hash=0x71D3B6F0, display_name="Nightmare Cerberus"},
        {ref_name="hauler", HEX_hash=0x5A82F9AE, display_name="Hauler"},
        {ref_name="hauler2", HEX_hash=0x171C92C4, display_name="Hauler Custom"},
        {ref_name="mule", HEX_hash=0x35ED670B, display_name="Mule"},
        {ref_name="mule2", HEX_hash=0xC1632BEB, display_name="Mule"},
        {ref_name="mule3", HEX_hash=0x85A5B471, display_name="Mule"},
        {ref_name="mule4", HEX_hash=0x73F4110E, display_name="Mule Custom"},
        {ref_name="packer", HEX_hash=0x21EEE87D, display_name="Packer"},
        {ref_name="phantom", HEX_hash=0x809AA4CB, display_name="Phantom"},
        {ref_name="phantom2", HEX_hash=0x9DAE1398, display_name="Phantom Wedge"},
        {ref_name="phantom3", HEX_hash=0xA90ED5C, display_name="Phantom Custom"},
        {ref_name="pounder", HEX_hash=0x7DE35E7D, display_name="Pounder"},
        {ref_name="pounder2", HEX_hash=0x6290F15B, display_name="Pounder Custom"},
        {ref_name="stockade", HEX_hash=0x6827CF72, display_name="Stockade"},
        {ref_name="stockade3", HEX_hash=0xF337AB36, display_name="Stockade"},
        {ref_name="terbyte", HEX_hash=0x897AFC65, display_name="Terrorbyte"}
    },
    COMPACT = {
        {ref_name="asbo", HEX_hash=0x42ACA95F, display_name="Asbo"},
        {ref_name="blista", HEX_hash=0xEB70965F, display_name="Blista"},
        {ref_name="brioso", HEX_hash=0x5C55CB39, display_name="Brioso R/A"},
        {ref_name="club", HEX_hash=0x82E47E85, display_name="Club"},
        {ref_name="dilettante", HEX_hash=0xBC993509, display_name="Dilettante"},
        {ref_name="dilettante2", HEX_hash=0x64430650, display_name="Dilettante"},
        {ref_name="issi2", HEX_hash=0xB9CB3B69, display_name="Issi"},
        {ref_name="kanjo", HEX_hash=0x18619B7E, display_name="Blista Kanjo"},
        {ref_name="panto", HEX_hash=0xE644E480, display_name="Panto"},
        {ref_name="prairie", HEX_hash=0xA988D3A2, display_name="Prairie"},
        {ref_name="rhapsody", HEX_hash=0x322CF98F, display_name="Rhapsody"}
    },
    COMPACTS = {
        {ref_name="brioso2", HEX_hash=0x55365079, display_name="Brioso 300"},
        {ref_name="issi3", HEX_hash=0x378236E1, display_name="Issi Classic"},
        {ref_name="issi4", HEX_hash=0x256E92BA, display_name="Apocalypse Issi"},
        {ref_name="issi5", HEX_hash=0x5BA0FF1E, display_name="Future Shock Issi"},
        {ref_name="issi6", HEX_hash=0x49E25BA1, display_name="Nightmare Issi"},
        {ref_name="weevil", HEX_hash=0x61FE4D6A, display_name="Weevil"}
    },
    COUPE = {
        {ref_name="cogcabrio", HEX_hash=0x13B57D8A, display_name="Cognoscenti Cabrio"},
        {ref_name="exemplar", HEX_hash=0xFFB15B5E, display_name="Exemplar"},
        {ref_name="f620", HEX_hash=0xDCBCBE48, display_name="F620"},
        {ref_name="felon", HEX_hash=0xE8A8BDA8, display_name="Felon"},
        {ref_name="felon2", HEX_hash=0xFAAD85EE, display_name="Felon GT"},
        {ref_name="jackal", HEX_hash=0xDAC67112, display_name="Jackal"},
        {ref_name="oracle", HEX_hash=0x506434F6, display_name="Oracle XS"},
        {ref_name="oracle2", HEX_hash=0xE18195B2, display_name="Oracle"},
        {ref_name="sentinel", HEX_hash=0x50732C82, display_name="Sentinel XS"},
        {ref_name="sentinel2", HEX_hash=0x3412AE2D, display_name="Sentinel"},
        {ref_name="windsor", HEX_hash=0x5E4327C8, display_name="Windsor"},
        {ref_name="windsor2", HEX_hash=0x8CF5CAE1, display_name="Windsor Drop"},
        {ref_name="zion", HEX_hash=0xBD1B39C3, display_name="Zion"},
        {ref_name="zion2", HEX_hash=0xB8E2AE18, display_name="Zion Cabrio"}
    },
    CYCLE = {
        {ref_name="bmx", HEX_hash=0x43779C54, display_name="BMX"},
        {ref_name="cruiser", HEX_hash=0x1ABA13B5, display_name="Cruiser"},
        {ref_name="fixter", HEX_hash=0xCE23D3BF, display_name="Fixter"},
        {ref_name="scorcher", HEX_hash=0xF4E1AA15, display_name="Scorcher"},
        {ref_name="tribike", HEX_hash=0x4339CD69, display_name="Whippet Race Bike"},
        {ref_name="tribike2", HEX_hash=0xB67597EC, display_name="Endurex Race Bike"},
        {ref_name="tribike3", HEX_hash=0xE823FB48, display_name="Tri Cycles Race Bike"}
    },
    EMERGENCY = {
        {ref_name="ambulance", HEX_hash=0x45D56ADA, display_name="Ambulance"},
        {ref_name="fbi", HEX_hash=0x432EA949, display_name="FIB"},
        {ref_name="fbi2", HEX_hash=0x9DC66994, display_name="FIB"},
        {ref_name="firetruk", HEX_hash=0x73920F8E, display_name="Fire Truck"},
        {ref_name="lguard", HEX_hash=0x1BF8D381, display_name="Lifeguard"},
        {ref_name="pbus", HEX_hash=0x885F3671, display_name="Police Prison Bus"},
        {ref_name="police", HEX_hash=0x79FBB0C5, display_name="Police Cruiser"},
        {ref_name="police2", HEX_hash=0x9F05F101, display_name="Police Cruiser"},
        {ref_name="police3", HEX_hash=0x71FA16EA, display_name="Police Cruiser"},
        {ref_name="police4", HEX_hash=0x8A63C7B9, display_name="Unmarked Cruiser"},
        {ref_name="policeb", HEX_hash=0xFDEFAEC3, display_name="Police Bike"},
        {ref_name="policeold1", HEX_hash=0xA46462F7, display_name="Police Rancher"},
        {ref_name="policeold2", HEX_hash=0x95F4C618, display_name="Police Roadcruiser"},
        {ref_name="policet", HEX_hash=0x1B38E955, display_name="Police Transporter"},
        {ref_name="pranger", HEX_hash=0x2C33B46E, display_name="Park Ranger"},
        {ref_name="riot", HEX_hash=0xB822A1AA, display_name="Police Riot"},
        {ref_name="riot2", HEX_hash=0x9B16A3B4, display_name="RCV"},
        {ref_name="sheriff", HEX_hash=0x9BAA707C, display_name="Sheriff Cruiser"},
        {ref_name="sheriff2", HEX_hash=0x72935408, display_name="Sheriff SUV"}
    },
    HELICOPTER = {
        {ref_name="akula", HEX_hash=0x46699F47, display_name="Akula"},
        {ref_name="annihilator", HEX_hash=0x31F0B376, display_name="Annihilator"},
        {ref_name="annihilator2", HEX_hash=0x11962E49, display_name="Annihilator Stealth"},
        {ref_name="buzzard", HEX_hash=0x2F03547B, display_name="Buzzard Attack Chopper"},
        {ref_name="buzzard2", HEX_hash=0x2C75F0DD, display_name="Buzzard"},
        {ref_name="cargobob", HEX_hash=0xFCFCB68B, display_name="Cargobob"},
        {ref_name="cargobob2", HEX_hash=0x60A7EA10, display_name="Cargobob"},
        {ref_name="cargobob3", HEX_hash=0x53174EEF, display_name="Cargobob"},
        {ref_name="cargobob4", HEX_hash=0x78BC1A3C, display_name="Cargobob"},
        {ref_name="frogger", HEX_hash=0x2C634FBD, display_name="Frogger"},
        {ref_name="frogger2", HEX_hash=0x742E9AC0, display_name="Frogger"},
        {ref_name="havok", HEX_hash=0x89BA59F5, display_name="Havok"},
        {ref_name="hunter", HEX_hash=0xFD707EDE, display_name="FH 1 Hunter"},
        {ref_name="maverick", HEX_hash=0x9D0450CA, display_name="Maverick"},
        {ref_name="polmav", HEX_hash=0x1517D4D9, display_name="Police Maverick"},
        {ref_name="savage", HEX_hash=0xFB133A17, display_name="Savage"},
        {ref_name="seasparrow", HEX_hash=0xD4AE63D9, display_name="Sea Sparrow"},
        {ref_name="seasparrow2", HEX_hash=0x494752F7, display_name="Sparrow"},
        {ref_name="seasparrow3", HEX_hash=0x5F017E6B, display_name="Sparrow"},
        {ref_name="skylift", HEX_hash=0x3E48BF23, display_name="Skylift"},
        {ref_name="supervolito", HEX_hash=0x2A54C47D, display_name="SuperVolito"},
        {ref_name="supervolito2", HEX_hash=0x9C5E5644, display_name="SuperVolito Carbon"},
        {ref_name="swift", HEX_hash=0xEBC24DF2, display_name="Swift"},
        {ref_name="swift2", HEX_hash=0x4019CB4C, display_name="Swift Deluxe"},
        {ref_name="valkyrie", HEX_hash=0xA09E15FD, display_name="Valkyrie"},
        {ref_name="valkyrie2", HEX_hash=0x5BFA5C4B, display_name="Valkyrie MOD.0"},
        {ref_name="volatus", HEX_hash=0x920016F1, display_name="Volatus"}
    },
    INDUSTRIAL = {
        {ref_name="bulldozer", HEX_hash=0x7074F39D, display_name="Dozer"},
        {ref_name="cutter", HEX_hash=0xC3FBA120, display_name="Cutter"},
        {ref_name="dump", HEX_hash=0x810369E2, display_name="Dump"},
        {ref_name="flatbed", HEX_hash=0x50B0215A, display_name="Flatbed"},
        {ref_name="guardian", HEX_hash=0x825A9F4C, display_name="Guardian"},
        {ref_name="handler", HEX_hash=0x1A7FCEFA, display_name="Dock Handler"},
        {ref_name="mixer", HEX_hash=0xD138A6BB, display_name="Mixer"},
        {ref_name="mixer2", HEX_hash=0x1C534995, display_name="Mixer"},
        {ref_name="rubble", HEX_hash=0x9A5B1DCC, display_name="Rubble"},
        {ref_name="tiptruck", HEX_hash=0x2E19879, display_name="Tipper"},
        {ref_name="tiptruck2", HEX_hash=0xC7824E5E, display_name="Tipper"}
    },
    MILITARY = {
        {ref_name="apc", HEX_hash=0x2189D250, display_name="APC"},
        {ref_name="barracks", HEX_hash=0xCEEA3F4B, display_name="Barracks"},
        {ref_name="barracks2", HEX_hash=0x4008EABB, display_name="Barracks Semi"},
        {ref_name="barracks3", HEX_hash=0x2592B5CF, display_name="Barracks"},
        {ref_name="barrage", HEX_hash=0xF34DFB25, display_name="Barrage"},
        {ref_name="chernobog", HEX_hash=0xD6BC7523, display_name="Chernobog"},
        {ref_name="crusader", HEX_hash=0x132D5A1A, display_name="Crusader"},
        {ref_name="halftrack", HEX_hash=0xFE141DA6, display_name="Half track"},
        {ref_name="khanjali", HEX_hash=0xAA6F980A, display_name="TM 02 Khanjali"},
        {ref_name="minitank", HEX_hash=0xB53C6C52, display_name="Invade and Persuade Tank"},
        {ref_name="rhino", HEX_hash=0x2EA68690, display_name="Rhino Tank"},
        {ref_name="scarab", HEX_hash=0xBBA2A2F7, display_name="Apocalypse Scarab"},
        {ref_name="scarab2", HEX_hash=0x5BEB3CE0, display_name="Future Shock Scarab"},
        {ref_name="scarab3", HEX_hash=0xDD71BFEB, display_name="Nightmare Scarab"},
        {ref_name="thruster", HEX_hash=0x58CDAF30, display_name="Thruster"},
        {ref_name="trailersmall2", HEX_hash=0x8FD54EBB, display_name="Anti Aircraft Trailer"},
        {ref_name="vetir", HEX_hash=0x780FFBD2, display_name="Vetir"}
    },
    MOTORCYCLE = {
        {ref_name="akuma", HEX_hash=0x63ABADE7, display_name="Akuma"},
        {ref_name="avarus", HEX_hash=0x81E38F7F, display_name="Avarus"},
        {ref_name="bagger", HEX_hash=0x806B9CC3, display_name="Bagger"},
        {ref_name="bati", HEX_hash=0xF9300CC5, display_name="Bati 801"},
        {ref_name="bati2", HEX_hash=0xCADD5D2D, display_name="Bati 801RR"},
        {ref_name="bf400", HEX_hash=0x5283265, display_name="BF400"},
        {ref_name="carbonrs", HEX_hash=0xABB0C0, display_name="Carbon RS"},
        {ref_name="chimera", HEX_hash=0x675ED7, display_name="Chimera"},
        {ref_name="cliffhanger", HEX_hash=0x17420102, display_name="Cliffhanger"},
        {ref_name="daemon", HEX_hash=0x77934CEE, display_name="Daemon"},
        {ref_name="daemon2", HEX_hash=0xAC4E93C9, display_name="Daemon"},
        {ref_name="deathbike", HEX_hash=0xFE5F0722, display_name="Apocalypse Deathbike"},
        {ref_name="deathbike2", HEX_hash=0x93F09558, display_name="Future Shock Deathbike"},
        {ref_name="deathbike3", HEX_hash=0xAE12C99C, display_name="Nightmare Deathbike"},
        {ref_name="defiler", HEX_hash=0x30FF0190, display_name="Defiler"},
        {ref_name="diablous", HEX_hash=0xF1B44F44, display_name="Diabolus"},
        {ref_name="diablous2", HEX_hash=0x6ABDF65E, display_name="Diabolus Custom"},
        {ref_name="double", HEX_hash=0x9C669788, display_name="Double T"},
        {ref_name="enduro", HEX_hash=0x6882FA73, display_name="Enduro"},
        {ref_name="esskey", HEX_hash=0x794CB30C, display_name="Esskey"},
        {ref_name="faggio", HEX_hash=0x9229E4EB, display_name="Faggio Sport"},
        {ref_name="faggio2", HEX_hash=0x350D1AB, display_name="Faggio"},
        {ref_name="faggio3", HEX_hash=0xB328B188, display_name="Faggio Mod"},
        {ref_name="fcr", HEX_hash=0x25676EAF, display_name="FCR 1000"},
        {ref_name="fcr2", HEX_hash=0xD2D5E00E, display_name="FCR 1000 Custom"},
        {ref_name="gargoyle", HEX_hash=0x2C2C2324, display_name="Gargoyle"},
        {ref_name="hakuchou", HEX_hash=0x4B6C568A, display_name="Hakuchou"},
        {ref_name="hakuchou2", HEX_hash=0xF0C2A91F, display_name="Hakuchou Drag"},
        {ref_name="hexer", HEX_hash=0x11F76C14, display_name="Hexer"},
        {ref_name="innovation", HEX_hash=0xF683EACA, display_name="Innovation"},
        {ref_name="lectro", HEX_hash=0x26321E67, display_name="Lectro"},
        {ref_name="manchez", HEX_hash=0xA5325278, display_name="Manchez"},
        {ref_name="manchez2", HEX_hash=0x40C332A3, display_name="Manchez Scout"},
        {ref_name="nemesis", HEX_hash=0xDA288376, display_name="Nemesis"},
        {ref_name="nightblade", HEX_hash=0xA0438767, display_name="Nightblade"},
        {ref_name="oppressor", HEX_hash=0x34B82784, display_name="Oppressor"},
        {ref_name="oppressor2", HEX_hash=0x7B54A9D3, display_name="Oppressor Mk II"},
        {ref_name="pcj", HEX_hash=0xC9CEAF06, display_name="PCJ 600"},
        {ref_name="ratbike", HEX_hash=0x6FACDF31, display_name="Rat Bike"},
        {ref_name="rrocket", HEX_hash=0x36A167E0, display_name="Rampant Rocket"},
        {ref_name="ruffian", HEX_hash=0xCABD11E8, display_name="Ruffian"},
        {ref_name="sanchez", HEX_hash=0x2EF89E46, display_name="Sanchez (livery)"},
        {ref_name="sanchez2", HEX_hash=0xA960B13E, display_name="Sanchez"},
        {ref_name="sanctus", HEX_hash=0x58E316C7, display_name="Sanctus"},
        {ref_name="shotaro", HEX_hash=0xE7D2A16E, display_name="Shotaro"},
        {ref_name="sovereign", HEX_hash=0x2C509634, display_name="Sovereign"},
        {ref_name="stryder", HEX_hash=0x11F58A5A, display_name="Stryder"},
        {ref_name="thrust", HEX_hash=0x6D6F8F43, display_name="Thrust"},
        {ref_name="vader", HEX_hash=0xF79A00F7, display_name="Vader"},
        {ref_name="vindicator", HEX_hash=0xAF599F01, display_name="Vindicator"},
        {ref_name="vortex", HEX_hash=0xDBA9DBFC, display_name="Vortex"},
        {ref_name="wolfsbane", HEX_hash=0xDB20A373, display_name="Wolfsbane"},
        {ref_name="zombiea", HEX_hash=0xC3D7C72B, display_name="Zombie Bobber"},
        {ref_name="zombieb", HEX_hash=0xDE05FB87, display_name="Zombie Chopper"}
    },
    MUSCLE = {
        {ref_name="blade", HEX_hash=0xB820ED5E, display_name="Blade"},
        {ref_name="buccaneer", HEX_hash=0xD756460C, display_name="Buccaneer"},
        {ref_name="buccaneer2", HEX_hash=0xC397F748, display_name="Buccaneer Custom"},
        {ref_name="chino", HEX_hash=0x14D69010, display_name="Chino"},
        {ref_name="chino2", HEX_hash=0xAED64A63, display_name="Chino Custom"},
        {ref_name="clique", HEX_hash=0xA29F78B0, display_name="Clique"},
        {ref_name="coquette3", HEX_hash=0x2EC385FE, display_name="Coquette BlackFin"},
        {ref_name="deviant", HEX_hash=0x4C3FFF49, display_name="Deviant"},
        {ref_name="dominator", HEX_hash=0x4CE68AC, display_name="Dominator"},
        {ref_name="dominator2", HEX_hash=0xC96B73D9, display_name="Pisswasser Dominator"},
        {ref_name="dominator3", HEX_hash=0xC52C6B93, display_name="Dominator GTX"},
        {ref_name="dominator4", HEX_hash=0xD6FB0F30, display_name="Apocalypse Dominator"},
        {ref_name="dominator5", HEX_hash=0xAE0A3D4F, display_name="Future Shock Dominator"},
        {ref_name="dominator6", HEX_hash=0xB2E046FB, display_name="Nightmare Dominator"},
        {ref_name="dukes", HEX_hash=0x2B26F456, display_name="Dukes"},
        {ref_name="dukes2", HEX_hash=0xEC8F7094, display_name="Duke O'Death"},
        {ref_name="dukes3", HEX_hash=0x7F3415E3, display_name="Beater Dukes"},
        {ref_name="ellie", HEX_hash=0xB472D2B5, display_name="Ellie"},
        {ref_name="faction", HEX_hash=0x81A9CDDF, display_name="Faction"},
        {ref_name="faction2", HEX_hash=0x95466BDB, display_name="Faction Custom"},
        {ref_name="faction3", HEX_hash=0x866BCE26, display_name="Faction Custom Donk"},
        {ref_name="gauntlet", HEX_hash=0x94B395C5, display_name="Gauntlet"},
        {ref_name="gauntlet2", HEX_hash=0x14D22159, display_name="Redwood Gauntlet"},
        {ref_name="gauntlet3", HEX_hash=0x2B0C4DCD, display_name="Gauntlet Classic"},
        {ref_name="gauntlet4", HEX_hash=0x734C5E50, display_name="Gauntlet Hellfire"},
        {ref_name="gauntlet5", HEX_hash=0x817AFAAD, display_name="Gauntlet Classic Custom"},
        {ref_name="hermes", HEX_hash=0xE83C17, display_name="Hermes"},
        {ref_name="hotknife", HEX_hash=0x239E390, display_name="Hotknife"},
        {ref_name="hustler", HEX_hash=0x23CA25F2, display_name="Hustler"},
        {ref_name="impaler", HEX_hash=0x83070B62, display_name="Impaler"},
        {ref_name="impaler2", HEX_hash=0x3C26BD0C, display_name="Apocalypse Impaler"},
        {ref_name="impaler3", HEX_hash=0x8D45DF49, display_name="Future Shock Impaler"},
        {ref_name="impaler4", HEX_hash=0x9804F4C7, display_name="Nightmare Impaler"},
        {ref_name="imperator", HEX_hash=0x1A861243, display_name="Apocalypse Imperator"},
        {ref_name="imperator2", HEX_hash=0x619C1B82, display_name="Future Shock Imperator"},
        {ref_name="imperator3", HEX_hash=0xD2F77E37, display_name="Nightmare Imperator"},
        {ref_name="lurcher", HEX_hash=0x7B47A6A7, display_name="Lurcher"},
        {ref_name="manana2", HEX_hash=0x665F785D, display_name="Manana Custom"},
        {ref_name="moonbeam", HEX_hash=0x1F52A43F, display_name="Moonbeam"},
        {ref_name="moonbeam2", HEX_hash=0x710A2B9B, display_name="Moonbeam Custom"},
        {ref_name="nightshade", HEX_hash=0x8C2BD0DC, display_name="Nightshade"},
        {ref_name="peyote2", HEX_hash=0x9472CD24, display_name="Peyote Gasser"},
        {ref_name="phoenix", HEX_hash=0x831A21D5, display_name="Phoenix"},
        {ref_name="picador", HEX_hash=0x59E0FBF3, display_name="Picador"},
        {ref_name="ratloader", HEX_hash=0xD83C13CE, display_name="Rat Loader"},
        {ref_name="ratloader2", HEX_hash=0xDCE1D9F7, display_name="Rat Truck"},
        {ref_name="ruiner", HEX_hash=0xF26CEFF9, display_name="Ruiner"},
        {ref_name="ruiner2", HEX_hash=0x381E10BD, display_name="Ruiner 2000"},
        {ref_name="ruiner3", HEX_hash=0x2E5AFD37, display_name="Ruiner"},
        {ref_name="sabregt", HEX_hash=0x9B909C94, display_name="Sabre Turbo"},
        {ref_name="sabregt2", HEX_hash=0xD4EA603, display_name="Sabre Turbo Custom"},
        {ref_name="slamvan", HEX_hash=0x2B7F9DE3, display_name="Slamvan"},
        {ref_name="slamvan2", HEX_hash=0x31ADBBFC, display_name="Lost Slamvan"},
        {ref_name="slamvan3", HEX_hash=0x42BC5E19, display_name="Slamvan Custom"},
        {ref_name="slamvan4", HEX_hash=0x8526E2F5, display_name="Apocalypse Slamvan"},
        {ref_name="slamvan5", HEX_hash=0x163F8520, display_name="Future Shock Slamvan"},
        {ref_name="slamvan6", HEX_hash=0x67D52852, display_name="Nightmare Slamvan"},
        {ref_name="stalion", HEX_hash=0x72A4C31E, display_name="Stallion"},
        {ref_name="stalion2", HEX_hash=0xE80F67EE, display_name="Burger Shot Stallion"},
        {ref_name="tampa", HEX_hash=0x39F9C898, display_name="Tampa"},
        {ref_name="tampa3", HEX_hash=0xB7D9F7F1, display_name="Weaponized Tampa"},
        {ref_name="tulip", HEX_hash=0x56D42971, display_name="Tulip"},
        {ref_name="vamos", HEX_hash=0xFD128DFD, display_name="Vamos"},
        {ref_name="vigero", HEX_hash=0xCEC6B9B7, display_name="Vigero"},
        {ref_name="virgo", HEX_hash=0xE2504942, display_name="Virgo"},
        {ref_name="virgo2", HEX_hash=0xCA62927A, display_name="Virgo Classic Custom"},
        {ref_name="virgo3", HEX_hash=0xFDFFB0, display_name="Virgo Classic"},
        {ref_name="voodoo", HEX_hash=0x779B4F2D, display_name="Voodoo Custom"},
        {ref_name="voodoo2", HEX_hash=0x1F3766E3, display_name="Voodoo"},
        {ref_name="yosemite", HEX_hash=0x6F946279, display_name="Yosemite"},
        {ref_name="yosemite2", HEX_hash=0x64F49967, display_name="Drift Yosemite"}
    },
    OFF_ROAD = {
        {ref_name="bfinjection", HEX_hash=0x432AA566, display_name="Injection"},
        {ref_name="bifta", HEX_hash=0xEB298297, display_name="Bifta"},
        {ref_name="blazer", HEX_hash=0x8125BCF9, display_name="Blazer"},
        {ref_name="blazer2", HEX_hash=0xFD231729, display_name="Blazer Lifeguard"},
        {ref_name="blazer3", HEX_hash=0xB44F0582, display_name="Hot Rod Blazer"},
        {ref_name="blazer4", HEX_hash=0xE5BA6858, display_name="Street Blazer"},
        {ref_name="blazer5", HEX_hash=0xA1355F67, display_name="Blazer Aqua"},
        {ref_name="bodhi2", HEX_hash=0xAA699BB6, display_name="Bodhi"},
        {ref_name="brawler", HEX_hash=0xA7CE1BC5, display_name="Brawler"},
        {ref_name="bruiser", HEX_hash=0x27D79225, display_name="Apocalypse Bruiser"},
        {ref_name="bruiser2", HEX_hash=0x9B065C9E, display_name="Future Shock Bruiser"},
        {ref_name="bruiser3", HEX_hash=0x8644331A, display_name="Nightmare Bruiser"},
        {ref_name="brutus", HEX_hash=0x7F81A829, display_name="Apocalypse Brutus"},
        {ref_name="brutus2", HEX_hash=0x8F49AE28, display_name="Future Shock Brutus"},
        {ref_name="brutus3", HEX_hash=0x798682A2, display_name="Nightmare Brutus"},
        {ref_name="caracara", HEX_hash=0x4ABEBF23, display_name="Caracara"},
        {ref_name="caracara2", HEX_hash=0xAF966F3C, display_name="Caracara 4x4"},
        {ref_name="dloader", HEX_hash=0x698521E3, display_name="Duneloader"},
        {ref_name="dubsta3", HEX_hash=0xB6410173, display_name="Dubsta 6x6"},
        {ref_name="dune", HEX_hash=0x9CF21E0F, display_name="Dune Buggy"},
        {ref_name="dune2", HEX_hash=0x1FD824AF, display_name="Space Docker"},
        {ref_name="dune3", HEX_hash=0x711D4738, display_name="Dune FAV"},
        {ref_name="dune4", HEX_hash=0xCEB28249, display_name="Ramp Buggy"},
        {ref_name="dune5", HEX_hash=0xED62BFA9, display_name="Ramp Buggy"},
        {ref_name="everon", HEX_hash=0x97553C28, display_name="Everon"},
        {ref_name="freecrawler", HEX_hash=0xFCC2F483, display_name="Freecrawler"},
        {ref_name="hellion", HEX_hash=0xEA6A047F, display_name="Hellion"},
        {ref_name="insurgent", HEX_hash=0x9114EADA, display_name="Insurgent Pick Up"},
        {ref_name="insurgent2", HEX_hash=0x7B7E56F0, display_name="Insurgent"},
        {ref_name="insurgent3", HEX_hash=0x8D4B7A8A, display_name="Insurgent Pick Up Custom"},
        {ref_name="kalahari", HEX_hash=0x5852838, display_name="Kalahari"},
        {ref_name="kamacho", HEX_hash=0xF8C2E0E7, display_name="Kamacho"},
        {ref_name="marshall", HEX_hash=0x49863E9C, display_name="Marshall"},
        {ref_name="menacer", HEX_hash=0x79DD18AE, display_name="Menacer"},
        {ref_name="mesa3", HEX_hash=0x84F42E51, display_name="Mesa"},
        {ref_name="monster", HEX_hash=0xCD93A7DB, display_name="Monster"},
        {ref_name="monster3", HEX_hash=0x669EB40A, display_name="Apocalypse Sasquatch"},
        {ref_name="monster4", HEX_hash=0x32174AFC, display_name="Future Shock Sasquatch"},
        {ref_name="monster5", HEX_hash=0xD556917C, display_name="Nightmare Sasquatch"},
        {ref_name="nightshark", HEX_hash=0x19DD9ED1, display_name="Nightshark"},
        {ref_name="outlaw", HEX_hash=0x185E2FF3, display_name="Outlaw"},
        {ref_name="rancherxl", HEX_hash=0x6210CBB0, display_name="Rancher XL"},
        {ref_name="rancherxl2", HEX_hash=0x7341576B, display_name="Rancher XL"},
        {ref_name="rcbandito", HEX_hash=0xEEF345EC, display_name="RC Bandito"},
        {ref_name="rebel", HEX_hash=0xB802DD46, display_name="Rusty Rebel"},
        {ref_name="rebel2", HEX_hash=0x8612B64B, display_name="Rebel"},
        {ref_name="riata", HEX_hash=0xA4A4E453, display_name="Riata"},
        {ref_name="sandking", HEX_hash=0xB9210FD0, display_name="Sandking XL"},
        {ref_name="sandking2", HEX_hash=0x3AF8C345, display_name="Sandking SWB"},
        {ref_name="technical", HEX_hash=0x83051506, display_name="Technical"},
        {ref_name="technical2", HEX_hash=0x4662BCBB, display_name="Technical Aqua"},
        {ref_name="technical3", HEX_hash=0x50D4D19F, display_name="Technical Custom"},
        {ref_name="trophytruck", HEX_hash=0x612F4B6, display_name="Trophy Truck"},
        {ref_name="trophytruck2", HEX_hash=0xD876DBE2, display_name="Desert Raid"},
        {ref_name="vagrant", HEX_hash=0x2C1FEA99, display_name="Vagrant"},
        {ref_name="verus", HEX_hash=0x11CBC051, display_name="Verus"},
        {ref_name="winky", HEX_hash=0xF376F1E6, display_name="Winky"},
        {ref_name="yosemite3", HEX_hash=0x409D787, display_name="Yosemite Rancher"},
        {ref_name="zhaba", HEX_hash=0x4C8DBA51, display_name="Zhaba"}
    },
    OPEN_WHEEL = {
        {ref_name="formula", HEX_hash=0x1446590A, display_name="PR4"},
        {ref_name="formula2", HEX_hash=0x8B213907, display_name="R88"},
        {ref_name="openwheel1", HEX_hash=0x58F77553, display_name="BR8"},
        {ref_name="openwheel2", HEX_hash=0x4669D038, display_name="DR1"}
    },
    PLANE = {
        {ref_name="alkonost", HEX_hash=0xEA313705, display_name="RO 86 Alkonost"},
        {ref_name="alphaz1", HEX_hash=0xA52F6866, display_name="Alpha Z1"},
        {ref_name="avenger", HEX_hash=0x81BD2ED0, display_name="Avenger"},
        {ref_name="avenger2", HEX_hash=0x18606535, display_name="Avenger"},
        {ref_name="besra", HEX_hash=0x6CBD1D6D, display_name="Besra"},
        {ref_name="blimp", HEX_hash=0xF7004C86, display_name="Atomic Blimp"},
        {ref_name="blimp2", HEX_hash=0xDB6B4924, display_name="Xero Blimp"},
        {ref_name="blimp3", HEX_hash=0xEDA4ED97, display_name="Blimp"},
        {ref_name="bombushka", HEX_hash=0xFE0A508C, display_name="RM 10 Bombushka"},
        {ref_name="cargoplane", HEX_hash=0x15F27762, display_name="Cargo Plane"},
        {ref_name="cuban800", HEX_hash=0xD9927FE3, display_name="Cuban 800"},
        {ref_name="dodo", HEX_hash=0xCA495705, display_name="Dodo"},
        {ref_name="duster", HEX_hash=0x39D6779E, display_name="Duster"},
        {ref_name="howard", HEX_hash=0xC3F25753, display_name="Howard NX 25"},
        {ref_name="hydra", HEX_hash=0x39D6E83F, display_name="Hydra"},
        {ref_name="jet", HEX_hash=0x3F119114, display_name="Jet"},
        {ref_name="lazer", HEX_hash=0xB39B0AE6, display_name="P 996 LAZER"},
        {ref_name="luxor", HEX_hash=0x250B0C5E, display_name="Luxor"},
        {ref_name="luxor2", HEX_hash=0xB79F589E, display_name="Luxor Deluxe"},
        {ref_name="mammatus", HEX_hash=0x97E55D11, display_name="Mammatus"},
        {ref_name="microlight", HEX_hash=0x96E24857, display_name="Ultralight"},
        {ref_name="miljet", HEX_hash=0x9D80F93, display_name="Miljet"},
        {ref_name="mogul", HEX_hash=0xD35698EF, display_name="Mogul"},
        {ref_name="molotok", HEX_hash=0x5D56F01B, display_name="V 65 Molotok"},
        {ref_name="nimbus", HEX_hash=0xB2CF7250, display_name="Nimbus"},
        {ref_name="nokota", HEX_hash=0x3DC92356, display_name="P 45 Nokota"},
        {ref_name="pyro", HEX_hash=0xAD6065C0, display_name="Pyro"},
        {ref_name="rogue", HEX_hash=0xC5DD6967, display_name="Rogue"},
        {ref_name="seabreeze", HEX_hash=0xE8983F9F, display_name="Seabreeze"},
        {ref_name="shamal", HEX_hash=0xB79C1BF5, display_name="Shamal"},
        {ref_name="starling", HEX_hash=0x9A9EB7DE, display_name="LF 22 Starling"},
        {ref_name="strikeforce", HEX_hash=0x64DE07A1, display_name="B 11 Strikeforce"},
        {ref_name="stunt", HEX_hash=0x81794C70, display_name="Mallard"},
        {ref_name="titan", HEX_hash=0x761E2AD3, display_name="Titan"},
        {ref_name="tula", HEX_hash=0x3E2E4F8A, display_name="Tula"},
        {ref_name="velum", HEX_hash=0x9C429B6A, display_name="Velum"},
        {ref_name="velum2", HEX_hash=0x403820E8, display_name="Velum 5 Seater"},
        {ref_name="vestra", HEX_hash=0x4FF77E37, display_name="Vestra"},
        {ref_name="volatol", HEX_hash=0x1AAD0DED, display_name="Volatol"}
    },
    RAIL = {
        {ref_name="cablecar", HEX_hash=0xC6C3242D, display_name="Cable Car"},
        {ref_name="freight", HEX_hash=0x3D6AAA9B, display_name="Freight Train"},
        {ref_name="freightcar", HEX_hash=0xAFD22A6, display_name="Freight Train"},
        {ref_name="freightcont1", HEX_hash=0x36DCFF98, display_name="Freight Train"},
        {ref_name="freightcont2", HEX_hash=0xE512E79, display_name="Freight Train"},
        {ref_name="freightgrain", HEX_hash=0x264D9262, display_name="Freight Train"},
        {ref_name="metrotrain", HEX_hash=0x33C9E158, display_name="Freight Train"},
        {ref_name="tankercar", HEX_hash=0x22EDDC30, display_name="Freight Train"}
    },
    SEDAN = {
        {ref_name="asea", HEX_hash=0x94204D89, display_name="Asea"},
        {ref_name="asea2", HEX_hash=0x9441D8D5, display_name="Asea"},
        {ref_name="asterope", HEX_hash=0x8E9254FB, display_name="Asterope"},
        {ref_name="cog55", HEX_hash=0x360A438E, display_name="Cognoscenti 55"},
        {ref_name="cog552", HEX_hash=0x29FCD3E4, display_name="Cognoscenti 55 (Armored)"},
        {ref_name="cognoscenti", HEX_hash=0x86FE0B60, display_name="Cognoscenti"},
        {ref_name="cognoscenti2", HEX_hash=0xDBF2D57A, display_name="Cognoscenti (Armored)"},
        {ref_name="emperor", HEX_hash=0xD7278283, display_name="Emperor"},
        {ref_name="emperor2", HEX_hash=0x8FC3AADC, display_name="Emperor"},
        {ref_name="emperor3", HEX_hash=0xB5FCF74E, display_name="Emperor"},
        {ref_name="fugitive", HEX_hash=0x71CB2FFB, display_name="Fugitive"},
        {ref_name="glendale", HEX_hash=0x47A6BC1, display_name="Glendale"},
        {ref_name="glendale2", HEX_hash=0xC98BBAD6, display_name="Glendale Custom"},
        {ref_name="ingot", HEX_hash=0xB3206692, display_name="Ingot"},
        {ref_name="intruder", HEX_hash=0x34DD8AA1, display_name="Intruder"},
        {ref_name="limo2", HEX_hash=0xF92AEC4D, display_name="Turreted Limo"},
        {ref_name="premier", HEX_hash=0x8FB66F9B, display_name="Premier"},
        {ref_name="primo", HEX_hash=0xBB6B404F, display_name="Primo"},
        {ref_name="primo2", HEX_hash=0x86618EDA, display_name="Primo Custom"},
        {ref_name="regina", HEX_hash=0xFF22D208, display_name="Regina"},
        {ref_name="romero", HEX_hash=0x2560B2FC, display_name="Romero Hearse"},
        {ref_name="schafter2", HEX_hash=0xB52B5113, display_name="Schafter"},
        {ref_name="schafter5", HEX_hash=0xCB0E7CD9, display_name="Schafter V12 (Armored)"},
        {ref_name="schafter6", HEX_hash=0x72934BE4, display_name="Schafter LWB (Armored)"},
        {ref_name="stafford", HEX_hash=0x1324E960, display_name="Stafford"},
        {ref_name="stanier", HEX_hash=0xA7EDE74D, display_name="Stanier"},
        {ref_name="stratum", HEX_hash=0x66B4FC45, display_name="Stratum"},
        {ref_name="stretch", HEX_hash=0x8B13F083, display_name="Stretch"},
        {ref_name="superd", HEX_hash=0x42F2ED16, display_name="Super Diamond"},
        {ref_name="surge", HEX_hash=0x8F0E3594, display_name="Surge"},
        {ref_name="tailgater", HEX_hash=0xC3DDFDCE, display_name="Tailgater"},
        {ref_name="warrener", HEX_hash=0x51D83328, display_name="Warrener"},
        {ref_name="washington", HEX_hash=0x69F06B57, display_name="Washington"}
    },
    SERVICE = {
        {ref_name="airbus", HEX_hash=0x4C80EB0E, display_name="Airport Bus"},
        {ref_name="brickade", HEX_hash=0xEDC6F847, display_name="Brickade"},
        {ref_name="bus", HEX_hash=0xD577C962, display_name="Bus"},
        {ref_name="coach", HEX_hash=0x84718D34, display_name="Dashound"},
        {ref_name="pbus2", HEX_hash=0x149BD32A, display_name="Festival Bus"},
        {ref_name="rallytruck", HEX_hash=0x829A3C44, display_name="Dune"},
        {ref_name="rentalbus", HEX_hash=0xBE819C63, display_name="Rental Shuttle Bus"},
        {ref_name="taxi", HEX_hash=0xC703DB5F, display_name="Taxi"},
        {ref_name="tourbus", HEX_hash=0x73B1C3CB, display_name="Tourbus"},
        {ref_name="trash", HEX_hash=0x72435A19, display_name="Trashmaster"},
        {ref_name="trash2", HEX_hash=0xB527915C, display_name="Trashmaster"},
        {ref_name="wastelander", HEX_hash=0x8E08EC82, display_name="Wastelander"}
    },
    SPORT = {
        {ref_name="alpha", HEX_hash=0x2DB8D1AA, display_name="Alpha"},
        {ref_name="banshee", HEX_hash=0xC1E908D2, display_name="Banshee"},
        {ref_name="bestiagts", HEX_hash=0x4BFCF28B, display_name="Bestia GTS"},
        {ref_name="blista2", HEX_hash=0x3DEE5EDA, display_name="Blista Compact"},
        {ref_name="blista3", HEX_hash=0xDCBC1C3B, display_name="Go Go Monkey Blista"},
        {ref_name="buffalo", HEX_hash=0xEDD516C6, display_name="Buffalo"},
        {ref_name="buffalo2", HEX_hash=0x2BEC3CBE, display_name="Buffalo S"},
        {ref_name="buffalo3", HEX_hash=0xE2C013E, display_name="Sprunk Buffalo"},
        {ref_name="carbonizzare", HEX_hash=0x7B8AB45F, display_name="Carbonizzare"},
        {ref_name="comet2", HEX_hash=0xC1AE4D16, display_name="Comet"},
        {ref_name="comet3", HEX_hash=0x877358AD, display_name="Comet Retro Custom"},
        {ref_name="comet4", HEX_hash=0x5D1903F9, display_name="Comet Safari"},
        {ref_name="comet5", HEX_hash=0x276D98A3, display_name="Comet SR"},
        {ref_name="coquette", HEX_hash=0x67BC037, display_name="Coquette"},
        {ref_name="coquette4", HEX_hash=0x98F65A5E, display_name="Coquette D10"},
        {ref_name="drafter", HEX_hash=0x28EAB80F, display_name="8F Drafter"},
        {ref_name="elegy", HEX_hash=0xBBA2261, display_name="Elegy Retro Custom"},
        {ref_name="elegy2", HEX_hash=0xDE3D9D22, display_name="Elegy RH8"},
        {ref_name="feltzer2", HEX_hash=0x8911B9F5, display_name="Feltzer"},
        {ref_name="flashgt", HEX_hash=0xB4F32118, display_name="Flash GT"},
        {ref_name="furoregt", HEX_hash=0xBF1691E0, display_name="Furore GT"},
        {ref_name="fusilade", HEX_hash=0x1DC0BA53, display_name="Fusilade"},
        {ref_name="futo", HEX_hash=0x7836CE2F, display_name="Futo"},
        {ref_name="gb200", HEX_hash=0x71CBEA98, display_name="GB200"},
        {ref_name="hotring", HEX_hash=0x42836BE5, display_name="Hotring Sabre"},
        {ref_name="imorgon", HEX_hash=0xBC7C0A00, display_name="Imorgon"},
        {ref_name="issi7", HEX_hash=0x6E8DA4F7, display_name="Issi Sport"},
        {ref_name="italigto", HEX_hash=0xEC3E3404, display_name="Itali GTO"},
        {ref_name="italirsx", HEX_hash=0xBB78956A, display_name="Itali RSX"},
        {ref_name="jester", HEX_hash=0xB2A716A3, display_name="Jester"},
        {ref_name="jester2", HEX_hash=0xBE0E6126, display_name="Jester (Racecar)"},
        {ref_name="jester3", HEX_hash=0xF330CB6A, display_name="Jester Classic"},
        {ref_name="jugular", HEX_hash=0xF38C4245, display_name="Jugular"},
        {ref_name="khamelion", HEX_hash=0x206D1B68, display_name="Khamelion"},
        {ref_name="komoda", HEX_hash=0xCE44C4B9, display_name="Komoda"},
        {ref_name="kuruma", HEX_hash=0xAE2BFE94, display_name="Kuruma"},
        {ref_name="kuruma2", HEX_hash=0x187D938D, display_name="Kuruma (armored)"},
        {ref_name="locust", HEX_hash=0xC7E55211, display_name="Locust"},
        {ref_name="lynx", HEX_hash=0x1CBDC10B, display_name="Lynx"},
        {ref_name="massacro", HEX_hash=0xF77ADE32, display_name="Massacro"},
        {ref_name="massacro2", HEX_hash=0xDA5819A3, display_name="Massacro (Racecar)"},
        {ref_name="neo", HEX_hash=0x9F6ED5A2, display_name="Neo"},
        {ref_name="neon", HEX_hash=0x91CA96EE, display_name="Neon"},
        {ref_name="ninef", HEX_hash=0x3D8FA25C, display_name="9F"},
        {ref_name="ninef2", HEX_hash=0xA8E38B01, display_name="9F Cabrio"},
        {ref_name="omnis", HEX_hash=0xD1AD4937, display_name="Omnis"},
        {ref_name="paragon", HEX_hash=0xE550775B, display_name="Paragon R"},
        {ref_name="paragon2", HEX_hash=0x546D8EEE, display_name="Paragon R (Armored)"},
        {ref_name="pariah", HEX_hash=0x33B98FE2, display_name="Pariah"},
        {ref_name="penumbra", HEX_hash=0xE9805550, display_name="Penumbra"},
        {ref_name="penumbra2", HEX_hash=0xDA5EC7DA, display_name="Penumbra FF"},
        {ref_name="raiden", HEX_hash=0xA4D99B7D, display_name="Raiden"},
        {ref_name="rapidgt", HEX_hash=0x8CB29A14, display_name="Rapid GT"},
        {ref_name="rapidgt2", HEX_hash=0x679450AF, display_name="Rapid GT"},
        {ref_name="raptor", HEX_hash=0xD7C56D39, display_name="Raptor"},
        {ref_name="revolter", HEX_hash=0xE78CC3D9, display_name="Revolter"},
        {ref_name="ruston", HEX_hash=0x2AE524A8, display_name="Ruston"},
        {ref_name="schafter3", HEX_hash=0xA774B5A6, display_name="Schafter V12"},
        {ref_name="schafter4", HEX_hash=0x58CF185C, display_name="Schafter LWB"},
        {ref_name="schlagen", HEX_hash=0xE1C03AB0, display_name="Schlagen GT"},
        {ref_name="schwarzer", HEX_hash=0xD37B7976, display_name="Schwartzer"},
        {ref_name="sentinel3", HEX_hash=0x41D149AA, display_name="Sentinel"},
        {ref_name="seven70", HEX_hash=0x97398A4B, display_name="Seven 70"},
        {ref_name="specter", HEX_hash=0x706E2B40, display_name="Specter"},
        {ref_name="specter2", HEX_hash=0x400F5147, display_name="Specter Custom"},
        {ref_name="streiter", HEX_hash=0x67D2B389, display_name="Streiter"},
        {ref_name="sugoi", HEX_hash=0x3ADB9758, display_name="Sugoi"},
        {ref_name="sultan", HEX_hash=0x39DA2754, display_name="Sultan"},
        {ref_name="sultan2", HEX_hash=0x3404691C, display_name="Sultan Classic"},
        {ref_name="surano", HEX_hash=0x16E478C1, display_name="Surano"},
        {ref_name="tampa2", HEX_hash=0xC0240885, display_name="Drift Tampa"},
        {ref_name="tropos", HEX_hash=0x707E63A4, display_name="Tropos Rallye"},
        {ref_name="verlierer2", HEX_hash=0x41B77FA4, display_name="Verlierer"},
        {ref_name="veto", HEX_hash=0xCCE5C8FA, display_name="Veto Classic"},
        {ref_name="veto2", HEX_hash=0xA703E4A9, display_name="Veto Modern"},
        {ref_name="vstr", HEX_hash=0x56CDEE7D, display_name="V STR"},
        {ref_name="zr380", HEX_hash=0x20314B42, display_name="Apocalypse ZR380"},
        {ref_name="zr3802", HEX_hash=0xBE11EFC6, display_name="Future Shock ZR380"},
        {ref_name="zr3803", HEX_hash=0xA7DCC35C, display_name="Nightmare ZR380"}
    },
    SPORT_CLASSIC = {
        {ref_name="ardent", HEX_hash=0x97E5533, display_name="Ardent"},
        {ref_name="btype", HEX_hash=0x6FF6914, display_name="Roosevelt"},
        {ref_name="btype2", HEX_hash=0xCE6B35A4, display_name="Fränken Stange"},
        {ref_name="btype3", HEX_hash=0xDC19D101, display_name="Roosevelt Valor"},
        {ref_name="casco", HEX_hash=0x3822BDFE, display_name="Casco"},
        {ref_name="cheburek", HEX_hash=0xC514AAE0, display_name="Cheburek"},
        {ref_name="cheetah2", HEX_hash=0xD4E5F4D, display_name="Cheetah Classic"},
        {ref_name="coquette2", HEX_hash=0x3C4E2113, display_name="Coquette Classic"},
        {ref_name="deluxo", HEX_hash=0x586765FB, display_name="Deluxo"},
        {ref_name="dynasty", HEX_hash=0x127E90D5, display_name="Dynasty"},
        {ref_name="fagaloa", HEX_hash=0x6068AD86, display_name="Fagaloa"},
        {ref_name="feltzer3", HEX_hash=0xA29D6D10, display_name="Stirling GT"},
        {ref_name="gt500", HEX_hash=0x8408F33A, display_name="GT500"},
        {ref_name="infernus2", HEX_hash=0xAC33179C, display_name="Infernus Classic"},
        {ref_name="jb700", HEX_hash=0x3EAB5555, display_name="JB 700"},
        {ref_name="jb7002", HEX_hash=0x177DA45C, display_name="JB 700W"},
        {ref_name="mamba", HEX_hash=0x9CFFFC56, display_name="Mamba"},
        {ref_name="manana", HEX_hash=0x81634188, display_name="Manana"},
        {ref_name="michelli", HEX_hash=0x3E5BD8D9, display_name="Michelli GT"},
        {ref_name="monroe", HEX_hash=0xE62B361B, display_name="Monroe"},
        {ref_name="nebula", HEX_hash=0xCB642637, display_name="Nebula Turbo"},
        {ref_name="peyote", HEX_hash=0x6D19CCBC, display_name="Peyote"},
        {ref_name="peyote3", HEX_hash=0x4201A843, display_name="Peyote Custom"},
        {ref_name="pigalle", HEX_hash=0x404B6381, display_name="Pigalle"},
        {ref_name="rapidgt3", HEX_hash=0x7A2EF5E4, display_name="Rapid GT Classic"},
        {ref_name="retinue", HEX_hash=0x6DBD6C0A, display_name="Retinue"},
        {ref_name="retinue2", HEX_hash=0x79178F0A, display_name="Retinue Mk II"},
        {ref_name="savestra", HEX_hash=0x35DED0DD, display_name="Savestra"},
        {ref_name="stinger", HEX_hash=0x5C23AF9B, display_name="Stinger"},
        {ref_name="stingergt", HEX_hash=0x82E499FA, display_name="Stinger GT"},
        {ref_name="stromberg", HEX_hash=0x34DBA661, display_name="Stromberg"},
        {ref_name="swinger", HEX_hash=0x1DD4C0FF, display_name="Swinger"},
        {ref_name="toreador", HEX_hash=0x56C8A5EF, display_name="Toreador"},
        {ref_name="torero", HEX_hash=0x59A9E570, display_name="Torero"},
        {ref_name="tornado", HEX_hash=0x1BB290BC, display_name="Tornado"},
        {ref_name="tornado2", HEX_hash=0x5B42A5C4, display_name="Tornado"},
        {ref_name="tornado3", HEX_hash=0x690A4153, display_name="Tornado"},
        {ref_name="tornado4", HEX_hash=0x86CF7CDD, display_name="Tornado"},
        {ref_name="tornado5", HEX_hash=0x94DA98EF, display_name="Tornado Custom"},
        {ref_name="tornado6", HEX_hash=0xA31CB573, display_name="Tornado Rat Rod"},
        {ref_name="turismo2", HEX_hash=0xC575DF11, display_name="Turismo Classic"},
        {ref_name="viseris", HEX_hash=0xE8A8BA94, display_name="Viseris"},
        {ref_name="z190", HEX_hash=0x3201DD49, display_name="190z"},
        {ref_name="zion3", HEX_hash=0x6F039A67, display_name="Zion Classic"},
        {ref_name="ztype", HEX_hash=0x2D3BD401, display_name="Z Type"}
    },
    SUPER = {
        {ref_name="adder", HEX_hash=0xB779A091, display_name="Adder"},
        {ref_name="autarch", HEX_hash=0xED552C74, display_name="Autarch"},
        {ref_name="banshee2", HEX_hash=0x25C5AF13, display_name="Banshee 900R"},
        {ref_name="bullet", HEX_hash=0x9AE6DDA1, display_name="Bullet"},
        {ref_name="cheetah", HEX_hash=0xB1D95DA0, display_name="Cheetah"},
        {ref_name="cyclone", HEX_hash=0x52FF9437, display_name="Cyclone"},
        {ref_name="deveste", HEX_hash=0x5EE005DA, display_name="Deveste Eight"},
        {ref_name="emerus", HEX_hash=0x4EE74355, display_name="Emerus"},
        {ref_name="entity2", HEX_hash=0x8198AEDC, display_name="Entity XXR"},
        {ref_name="entityxf", HEX_hash=0xB2FE5CF9, display_name="Entity XF"},
        {ref_name="fmj", HEX_hash=0x5502626C, display_name="FMJ"},
        {ref_name="furia", HEX_hash=0x3944D5A0, display_name="Furia"},
        {ref_name="gp1", HEX_hash=0x4992196C, display_name="GP1"},
        {ref_name="infernus", HEX_hash=0x18F25AC7, display_name="Infernus"},
        {ref_name="italigtb", HEX_hash=0x85E8E76B, display_name="Itali GTB"},
        {ref_name="italigtb2", HEX_hash=0xE33A477B, display_name="Itali GTB Custom"},
        {ref_name="krieger", HEX_hash=0xD86A0247, display_name="Krieger"},
        {ref_name="le7b", HEX_hash=0xB6846A55, display_name="RE 7B"},
        {ref_name="nero", HEX_hash=0x3DA47243, display_name="Nero"},
        {ref_name="nero2", HEX_hash=0x4131F378, display_name="Nero Custom"},
        {ref_name="osiris", HEX_hash=0x767164D6, display_name="Osiris"},
        {ref_name="penetrator", HEX_hash=0x9734F3EA, display_name="Penetrator"},
        {ref_name="pfister811", HEX_hash=0x92EF6E04, display_name="811"},
        {ref_name="prototipo", HEX_hash=0x7E8F677F, display_name="X80 Proto"},
        {ref_name="reaper", HEX_hash=0xDF381E5, display_name="Reaper"},
        {ref_name="s80", HEX_hash=0xECA6B6A3, display_name="S80RR"},
        {ref_name="sc1", HEX_hash=0x5097F589, display_name="SC1"},
        {ref_name="scramjet", HEX_hash=0xD9F0503D, display_name="Scramjet"},
        {ref_name="sheava", HEX_hash=0x30D3F6D8, display_name="ETR1"},
        {ref_name="sultanrs", HEX_hash=0xEE6024BC, display_name="Sultan RS"},
        {ref_name="t20", HEX_hash=0x6322B39A, display_name="T20"},
        {ref_name="taipan", HEX_hash=0xBC5DC07E, display_name="Taipan"},
        {ref_name="tempesta", HEX_hash=0x1044926F, display_name="Tempesta"},
        {ref_name="tezeract", HEX_hash=0x3D7C6410, display_name="Tezeract"},
        {ref_name="thrax", HEX_hash=0x3E3D1F59, display_name="Thrax"},
        {ref_name="tigon", HEX_hash=0xAF0B8D48, display_name="Tigon"},
        {ref_name="turismor", HEX_hash=0x185484E1, display_name="Turismo R"},
        {ref_name="tyrant", HEX_hash=0xE99011C2, display_name="Tyrant"},
        {ref_name="tyrus", HEX_hash=0x7B406EFB, display_name="Tyrus"},
        {ref_name="vacca", HEX_hash=0x142E0DC3, display_name="Vacca"},
        {ref_name="vagner", HEX_hash=0x7397224C, display_name="Vagner"},
        {ref_name="vigilante", HEX_hash=0xB5EF4C33, display_name="Vigilante"},
        {ref_name="visione", HEX_hash=0xC4810400, display_name="Visione"},
        {ref_name="voltic", HEX_hash=0x9F4B77BE, display_name="Voltic"},
        {ref_name="voltic2", HEX_hash=0x3AF76F4A, display_name="Rocket Voltic"},
        {ref_name="xa21", HEX_hash=0x36B4A8A9, display_name="XA 21"},
        {ref_name="zentorno", HEX_hash=0xAC5DF515, display_name="Zentorno"},
        {ref_name="zorrusso", HEX_hash=0xD757D97D, display_name="Zorrusso"}
    },
    SUV = {
        {ref_name="baller", HEX_hash=0xCFCA3668, display_name="Baller"},
        {ref_name="baller2", HEX_hash=0x8852855, display_name="Baller"},
        {ref_name="baller3", HEX_hash=0x6FF0F727, display_name="Baller LE"},
        {ref_name="baller4", HEX_hash=0x25CBE2E2, display_name="Baller LE LWB"},
        {ref_name="baller5", HEX_hash=0x1C09CF5E, display_name="Baller LE (Armored)"},
        {ref_name="baller6", HEX_hash=0x27B4E6B0, display_name="Baller LE LWB (Armored)"},
        {ref_name="bjxl", HEX_hash=0x32B29A4B, display_name="BeeJay XL"},
        {ref_name="cavalcade", HEX_hash=0x779F23AA, display_name="Cavalcade"},
        {ref_name="cavalcade2", HEX_hash=0xD0EB2BE5, display_name="Cavalcade"},
        {ref_name="contender", HEX_hash=0x28B67ACA, display_name="Contender"},
        {ref_name="dubsta", HEX_hash=0x462FE277, display_name="Dubsta"},
        {ref_name="dubsta2", HEX_hash=0xE882E5F6, display_name="Dubsta"},
        {ref_name="fq2", HEX_hash=0xBC32A33B, display_name="FQ 2"},
        {ref_name="granger", HEX_hash=0x9628879C, display_name="Granger"},
        {ref_name="gresley", HEX_hash=0xA3FC0F4D, display_name="Gresley"},
        {ref_name="habanero", HEX_hash=0x34B7390F, display_name="Habanero"},
        {ref_name="huntley", HEX_hash=0x1D06D681, display_name="Huntley S"},
        {ref_name="landstalker", HEX_hash=0x4BA4E8DC, display_name="Landstalker"},
        {ref_name="landstalker2", HEX_hash=0xCE0B9F22, display_name="Landstalker XL"},
        {ref_name="mesa", HEX_hash=0x36848602, display_name="Mesa"},
        {ref_name="mesa2", HEX_hash=0xD36A4B44, display_name="Mesa"},
        {ref_name="novak", HEX_hash=0x92F5024E, display_name="Novak"},
        {ref_name="patriot", HEX_hash=0xCFCFEB3B, display_name="Patriot"},
        {ref_name="patriot2", HEX_hash=0xE6E967F8, display_name="Patriot Stretch"},
        {ref_name="radi", HEX_hash=0x9D96B45B, display_name="Radius"},
        {ref_name="rebla", HEX_hash=0x4F48FC4, display_name="Rebla GTS"},
        {ref_name="rocoto", HEX_hash=0x7F5C91F1, display_name="Rocoto"},
        {ref_name="seminole", HEX_hash=0x48CECED3, display_name="Seminole"},
        {ref_name="seminole2", HEX_hash=0x94114926, display_name="Seminole Frontier"},
        {ref_name="serrano", HEX_hash=0x4FB1A214, display_name="Serrano"},
        {ref_name="squaddie", HEX_hash=0xF9E67C05, display_name="Squaddie"},
        {ref_name="toros", HEX_hash=0xBA5334AC, display_name="Toros"},
        {ref_name="xls", HEX_hash=0x47BBCF2E, display_name="XLS"},
        {ref_name="xls2", HEX_hash=0xE6401328, display_name="XLS (Armored)"}
    },
    UTILITY = {
        {ref_name="airtug", HEX_hash=0x5D0AAC8F, display_name="Airtug"},
        {ref_name="armytanker", HEX_hash=0xB8081009, display_name="Army Trailer"},
        {ref_name="armytrailer", HEX_hash=0xA7FF33F5, display_name="Army Trailer"},
        {ref_name="armytrailer2", HEX_hash=0x9E6B14D6, display_name="Army Trailer"},
        {ref_name="baletrailer", HEX_hash=0xE82AE656, display_name="Baletrailer"},
        {ref_name="boattrailer", HEX_hash=0x1F3D44B5, display_name="Boat Trailer"},
        {ref_name="caddy", HEX_hash=0x44623884, display_name="Caddy"},
        {ref_name="caddy2", HEX_hash=0xDFF0594C, display_name="Caddy"},
        {ref_name="caddy3", HEX_hash=0xD227BDBB, display_name="Caddy"},
        {ref_name="docktrailer", HEX_hash=0x806EFBEE, display_name=""},
        {ref_name="docktug", HEX_hash=0xCB44B1CA, display_name="Docktug"},
        {ref_name="forklift", HEX_hash=0x58E49664, display_name="Forklift"},
        {ref_name="freighttrailer", HEX_hash=0xD1ABB666, display_name=""},
        {ref_name="graintrailer", HEX_hash=0x3CC7F596, display_name="Graintrailer"},
        {ref_name="mower", HEX_hash=0x6A4BD8F6, display_name="Lawn Mower"},
        {ref_name="proptrailer", HEX_hash=0x153E1B0A, display_name=""},
        {ref_name="raketrailer", HEX_hash=0x174CB172, display_name="Trailer"},
        {ref_name="ripley", HEX_hash=0xCD935EF9, display_name="Ripley"},
        {ref_name="sadler", HEX_hash=0xDC434E51, display_name="Sadler"},
        {ref_name="sadler2", HEX_hash=0x2BC345D1, display_name="Sadler"},
        {ref_name="scrap", HEX_hash=0x9A9FD3DF, display_name="Scrap Truck"},
        {ref_name="slamtruck", HEX_hash=0xC1A8A914, display_name="Slamtruck"},
        {ref_name="tanker", HEX_hash=0xD46F4737, display_name="Trailer"},
        {ref_name="tanker2", HEX_hash=0x74998082, display_name=""},
        {ref_name="towtruck", HEX_hash=0xB12314E0, display_name="Towtruck"},
        {ref_name="towtruck2", HEX_hash=0xE5A2D6C6, display_name="Towtruck"},
        {ref_name="tr2", HEX_hash=0x7BE032C6, display_name="Trailer"},
        {ref_name="tr3", HEX_hash=0x6A59902D, display_name="Trailer"},
        {ref_name="tr4", HEX_hash=0x7CAB34D0, display_name="Trailer"},
        {ref_name="tractor", HEX_hash=0x61D6BA8C, display_name="Tractor"},
        {ref_name="tractor2", HEX_hash=0x843B73DE, display_name="Fieldmaster"},
        {ref_name="tractor3", HEX_hash=0x562A97BD, display_name="Fieldmaster"},
        {ref_name="trailerlarge", HEX_hash=0x5993F939, display_name="Mobile Operations Center"},
        {ref_name="trailerlogs", HEX_hash=0x782A236D, display_name="Trailer"},
        {ref_name="trailers", HEX_hash=0xCBB2BE0E, display_name="Trailer"},
        {ref_name="trailers2", HEX_hash=0xA1DA3C91, display_name="Trailer"},
        {ref_name="trailers3", HEX_hash=0x8548036D, display_name="Trailer"},
        {ref_name="trailers4", HEX_hash=0xBE66F5AA, display_name="Trailer"},
        {ref_name="trailersmall", HEX_hash=0x2A72BEAB, display_name="Trailer"},
        {ref_name="trflat", HEX_hash=0xAF62F6B2, display_name="Trailer"},
        {ref_name="tvtrailer", HEX_hash=0x967620BE, display_name="Trailer"},
        {ref_name="utillitruck", HEX_hash=0x1ED0A534, display_name="Utility Truck"},
        {ref_name="utillitruck2", HEX_hash=0x34E6BF6B, display_name="Utility Truck"},
        {ref_name="utillitruck3", HEX_hash=0x7F2153DF, display_name="Utility Truck"}
    },
    VAN = {
        {ref_name="bison", HEX_hash=0xFEFD644F, display_name="Bison"},
        {ref_name="bison2", HEX_hash=0x7B8297C5, display_name="Bison"},
        {ref_name="bison3", HEX_hash=0x67B3F020, display_name="Bison"},
        {ref_name="bobcatxl", HEX_hash=0x3FC5D440, display_name="Bobcat XL"},
        {ref_name="boxville", HEX_hash=0x898ECCEA, display_name="Boxville"},
        {ref_name="boxville2", HEX_hash=0xF21B33BE, display_name="Boxville"},
        {ref_name="boxville3", HEX_hash=0x7405E08, display_name="Boxville"},
        {ref_name="boxville4", HEX_hash=0x1A79847A, display_name="Boxville"},
        {ref_name="boxville5", HEX_hash=0x28AD20E1, display_name="Armored Boxville"},
        {ref_name="burrito", HEX_hash=0xAFBB2CA4, display_name="Burrito"},
        {ref_name="burrito2", HEX_hash=0xC9E8FF76, display_name="Bugstars Burrito"},
        {ref_name="burrito3", HEX_hash=0x98171BD3, display_name="Burrito"},
        {ref_name="burrito4", HEX_hash=0x353B561D, display_name="Burrito"},
        {ref_name="burrito5", HEX_hash=0x437CF2A0, display_name="Burrito"},
        {ref_name="camper", HEX_hash=0x6FD95F68, display_name="Camper"},
        {ref_name="gburrito", HEX_hash=0x97FA4F36, display_name="Gang Burrito"},
        {ref_name="gburrito2", HEX_hash=0x11AA0E14, display_name="Gang Burrito"},
        {ref_name="journey", HEX_hash=0xF8D48E7A, display_name="Journey"},
        {ref_name="minivan", HEX_hash=0xED7EADA4, display_name="Minivan"},
        {ref_name="minivan2", HEX_hash=0xBCDE91F0, display_name="Minivan Custom"},
        {ref_name="paradise", HEX_hash=0x58B3979C, display_name="Paradise"},
        {ref_name="pony", HEX_hash=0xF8DE29A8, display_name="Pony"},
        {ref_name="pony2", HEX_hash=0x38408341, display_name="Pony"},
        {ref_name="rumpo", HEX_hash=0x4543B74D, display_name="Rumpo"},
        {ref_name="rumpo2", HEX_hash=0x961AFEF7, display_name="Rumpo"},
        {ref_name="rumpo3", HEX_hash=0x57F682AF, display_name="Rumpo Custom"},
        {ref_name="speedo", HEX_hash=0xCFB3870C, display_name="Speedo"},
        {ref_name="speedo2", HEX_hash=0x2B6DC64A, display_name="Clown Van"},
        {ref_name="speedo4", HEX_hash=0xD17099D, display_name="Speedo Custom"},
        {ref_name="surfer", HEX_hash=0x29B0DA97, display_name="Surfer"},
        {ref_name="surfer2", HEX_hash=0xB1D80E06, display_name="Surfer"},
        {ref_name="taco", HEX_hash=0x744CA80D, display_name="Taco Van"},
        {ref_name="youga", HEX_hash=0x3E5F6B8, display_name="Youga"},
        {ref_name="youga2", HEX_hash=0x3D29CD2B, display_name="Youga Classic"},
        {ref_name="youga3", HEX_hash=0x6B73A9BE, display_name="Youga Classic 4x4"}
    }
}

function Anger_vehicle.get_vehicle_db()
    return vehicles_data
end

return Anger_vehicle