-- GeeSkid v1.0

_GT_class_str_list = {	
"Boats", --
"Commercial",
"Compacts",
"Coupes",
"Cycles",
"Emergency",
"Helicopters",
"Industrial",
"Military",
"Motorcycles", --
"Muscle",
"Off-Road",
"Open Wheel",
"Planes",
"Sedans",
"Service",
"Sports",
"Sports Classics",
"Super",
"SUVs",
"Trains",
"Utility",
"Vans",
}

_GT_vk_spawn_1_7 = {
"1",
"2",
"3",
"4",
"5",
"6",
"7",
}

 -- 1-name 2-make 3-make/model 4-hash 5-gamehash 6-class
_GT_all_veh_info = {
{"Avisa", "Kraken", "Kraken Avisa", 2588363614, gameplay.get_hash_key("avisa"), "Boats"},
{"Dinghy", "Nagasaki", "Nagasaki Dinghy", 1033245328, gameplay.get_hash_key("dinghy"), "Boats"},
{"Dinghy 2", "Nagasaki", "Nagasaki Dinghy 2", 276773164, gameplay.get_hash_key("dinghy2"), "Boats"},
{"Dinghy 3", "Nagasaki", "Nagasaki Dinghy 3", 509498602, gameplay.get_hash_key("dinghy3"), "Boats"},
{"Dinghy 4", "Nagasaki", "Nagasaki Dinghy 4", 867467158, gameplay.get_hash_key("dinghy4"), "Boats"},
{"Jetmax", "Shitzu", "Shitzu Jetmax", 861409633, gameplay.get_hash_key("jetmax"), "Boats"},
{"Kosatka", "RUNE", "RUNE Kosatka", 1336872304, gameplay.get_hash_key("kosatka"), "Boats"},
{"Kraken", "Kraken Submersibles", "Kraken Submersibles Kraken", 3228633070, gameplay.get_hash_key("submersible2"), "Boats"},
{"Kurtz 31 Patrol Boat", "", "Kurtz 31 Patrol Boat", 4018222598, gameplay.get_hash_key("patrolboat"), "Boats"},
{"Longfin", "Shitzu", "Shitzu Longfin", 1861786828, gameplay.get_hash_key("longfin"), "Boats"},
{"Marquis", "Dinka", "Dinka Marquis", 3251507587, gameplay.get_hash_key("marquis"), "Boats"},
{"Police Predator", "", "Police Predator", 3806844075, gameplay.get_hash_key("predator"), "Boats"},
{"Seashark", "Speedophile", "Speedophile Seashark", 3264692260, gameplay.get_hash_key("seashark"), "Boats"},
{"Seashark 2", "Speedophile", "Speedophile Seashark 2", 3678636260, gameplay.get_hash_key("seashark2"), "Boats"},
{"Seashark 3", "Speedophile", "Speedophile Seashark 3", 3983945033, gameplay.get_hash_key("seashark3"), "Boats"},
{"Speeder", "Pegassi", "Pegassi Speeder", 231083307, gameplay.get_hash_key("speeder"), "Boats"},
{"Speeder 2", "Pegassi", "Pegassi Speeder 2", 437538602, gameplay.get_hash_key("speeder2"), "Boats"},
{"Squalo", "Shitzu", "Shitzu Squalo", 400514754, gameplay.get_hash_key("squalo"), "Boats"},
{"Submersible", "Kraken", "Kraken Submersible", 771711535, gameplay.get_hash_key("submersible"), "Boats"},
{"Suntrap", "Shitzu", "Shitzu Suntrap", 4012021193, gameplay.get_hash_key("suntrap"), "Boats"},
{"Toro", "Lampadati", "Lampadati Toro", 1070967343, gameplay.get_hash_key("toro"), "Boats"},
{"Toro 2", "Lampadati", "Lampadati Toro 2", 908897389, gameplay.get_hash_key("toro2"), "Boats"},
{"Tropic", "Shitzu", "Shitzu Tropic", 290013743, gameplay.get_hash_key("tropic"), "Boats"},
{"Tropic 2", "Shitzu", "Shitzu Tropic 2", 1448677353, gameplay.get_hash_key("tropic2"), "Boats"},
{"Tug", "", "Tug", 2194326579, gameplay.get_hash_key("tug"), "Boats"},
{"Weaponized Dinghy", "Nagasaki", "Nagasaki Weaponized Dinghy", 3314393930, gameplay.get_hash_key("dinghy5"), "Boats"},
{"Apocalypse Cerberus", "MTL", "MTL Apocalypse Cerberus", 3493417227, gameplay.get_hash_key("cerberus"), "Commercial"},
{"Benson", "Vapid", "Vapid Benson", 2053223216, gameplay.get_hash_key("benson"), "Commercial"},
{"Biff", "HVY", "HVY Biff", 850991848, gameplay.get_hash_key("biff"), "Commercial"},
{"Future Shock Cerberus", "MTL", "MTL Future Shock Cerberus", 679453769, gameplay.get_hash_key("cerberus2"), "Commercial"},
{"Hauler", "JoBuilt", "JoBuilt Hauler", 1518533038, gameplay.get_hash_key("hauler"), "Commercial"},
{"Hauler Custom", "JoBuilt", "JoBuilt Hauler Custom", 387748548, gameplay.get_hash_key("hauler2"), "Commercial"},
{"Mule", "Maibatsu", "Maibatsu Mule", 904750859, gameplay.get_hash_key("mule"), "Commercial"},
{"Mule 2", "Maibatsu", "Maibatsu Mule 2", 3244501995, gameplay.get_hash_key("mule2"), "Commercial"},
{"Mule 3", "Maibatsu", "Maibatsu Mule 3", 2242229361, gameplay.get_hash_key("mule3"), "Commercial"},
{"Mule 4", "Maibatsu", "Maibatsu Mule 4", 1343932732, gameplay.get_hash_key("mule5"), "Commercial"},
{"Mule Custom", "Maibatsu", "Maibatsu Mule Custom", 1945374990, gameplay.get_hash_key("mule4"), "Commercial"},
{"Nightmare Cerberus", "MTL", "MTL Nightmare Cerberus", 1909700336, gameplay.get_hash_key("cerberus3"), "Commercial"},
{"Packer", "MTL", "MTL Packer", 569305213, gameplay.get_hash_key("packer"), "Commercial"},
{"Phantom", "JoBuilt", "JoBuilt Phantom", 2157618379, gameplay.get_hash_key("phantom"), "Commercial"},
{"Phantom Custom", "JoBuilt", "JoBuilt Phantom Custom", 177270108, gameplay.get_hash_key("phantom3"), "Commercial"},
{"Phantom Wedge", "JoBuilt", "JoBuilt Phantom Wedge", 2645431192, gameplay.get_hash_key("phantom2"), "Commercial"},
{"Pounder", "MTL", "MTL Pounder", 2112052861, gameplay.get_hash_key("pounder"), "Commercial"},
{"Pounder Custom", "MTL", "MTL Pounder Custom", 1653666139, gameplay.get_hash_key("pounder2"), "Commercial"},
{"Stockade", "Brute", "Brute Stockade", 1747439474, gameplay.get_hash_key("stockade"), "Commercial"},
{"Stockade 3", "Brute", "Brute Stockade 3", 4080511798, gameplay.get_hash_key("stockade3"), "Commercial"},
{"Terrorbyte", "Benefactor", "Benefactor Terrorbyte", 2306538597, gameplay.get_hash_key("terbyte"), "Commercial"},
{"Apocalypse Issi", "Weeny", "Weeny Apocalypse Issi", 628003514, gameplay.get_hash_key("issi4"), "Compacts"},
{"Asbo", "Maxwell", "Maxwell Asbo", 1118611807, gameplay.get_hash_key("asbo"), "Compacts"},
{"Blista", "Dinka", "Dinka Blista", 3950024287, gameplay.get_hash_key("blista"), "Compacts"},
{"Blista Kanjo", "Dinka", "Dinka Blista Kanjo", 409049982, gameplay.get_hash_key("kanjo"), "Compacts"},
{"Brioso 300", "Grotti", "Grotti Brioso 300", 1429622905, gameplay.get_hash_key("brioso2"), "Compacts"},
{"Brioso R/A", "Grotti", "Grotti Brioso R/A", 1549126457, gameplay.get_hash_key("brioso"), "Compacts"},
{"Club", "BF", "BF Club", 2196012677, gameplay.get_hash_key("club"), "Compacts"},
{"Dilettante", "Karin", "Karin Dilettante", 3164157193, gameplay.get_hash_key("dilettante"), "Compacts"},
{"Dilettante 2", "Karin", "Karin Dilettante 2", 1682114128, gameplay.get_hash_key("dilettante2"), "Compacts"},
{"Future Shock Issi", "Weeny", "Weeny Future Shock Issi", 1537277726, gameplay.get_hash_key("issi5"), "Compacts"},
{"Issi", "Weeny", "Weeny Issi", 3117103977, gameplay.get_hash_key("issi2"), "Compacts"},
{"Issi Classic", "Weeny", "Weeny Issi Classic", 931280609, gameplay.get_hash_key("issi3"), "Compacts"},
{"Nightmare Issi", "Weeny", "Weeny Nightmare Issi", 1239571361, gameplay.get_hash_key("issi6"), "Compacts"},
{"Panto", "Benefactor", "Benefactor Panto", 3863274624, gameplay.get_hash_key("panto"), "Compacts"},
{"Prairie", "Bollokan", "Bollokan Prairie", 2844316578, gameplay.get_hash_key("prairie"), "Compacts"},
{"Rhapsody", "Declasse", "Declasse Rhapsody", 841808271, gameplay.get_hash_key("rhapsody"), "Compacts"},
{"Weevil", "BF", "BF Weevil", 1644055914, gameplay.get_hash_key("weevil"), "Compacts"},
{"Cognoscenti Cabrio", "Enus", "Enus Cognoscenti Cabrio", 330661258, gameplay.get_hash_key("cogcabrio"), "Coupes"},
{"Exemplar", "Dewbauchee", "Dewbauchee Exemplar", 4289813342, gameplay.get_hash_key("exemplar"), "Coupes"},
{"F620", "Ocelot", "Ocelot F620", 3703357000, gameplay.get_hash_key("f620"), "Coupes"},
{"Felon", "Lampadati", "Lampadati Felon", 3903372712, gameplay.get_hash_key("felon"), "Coupes"},
{"Felon GT", "Lampadati", "Lampadati Felon GT", 4205676014, gameplay.get_hash_key("felon2"), "Coupes"},
{"Jackal", "Ocelot", "Ocelot Jackal", 3670438162, gameplay.get_hash_key("jackal"), "Coupes"},
{"Oracle", "Ubermacht", "Ubermacht Oracle", 3783366066, gameplay.get_hash_key("oracle2"), "Coupes"},
{"Oracle XS", "Ubermacht", "Ubermacht Oracle XS", 1348744438, gameplay.get_hash_key("oracle"), "Coupes"},
{"Previon", "Karin", "Karin Previon", 1416471345, gameplay.get_hash_key("previon"), "Coupes"},
{"Sentinel", "Ubermacht", "Ubermacht Sentinel", 873639469, gameplay.get_hash_key("sentinel2"), "Coupes"},
{"Sentinel XS", "Ubermacht", "Ubermacht Sentinel XS", 1349725314, gameplay.get_hash_key("sentinel"), "Coupes"},
{"Windsor", "Enus", "Enus Windsor", 1581459400, gameplay.get_hash_key("windsor"), "Coupes"},
{"Windsor Drop", "Enus", "Enus Windsor Drop", 2364918497, gameplay.get_hash_key("windsor2"), "Coupes"},
{"Zion", "Ubermacht", "Ubermacht Zion", 3172678083, gameplay.get_hash_key("zion"), "Coupes"},
{"Zion Cabrio", "Ubermacht", "Ubermacht Zion Cabrio", 3101863448, gameplay.get_hash_key("zion2"), "Coupes"},
{"BMX", "", "BMX", 1131912276, gameplay.get_hash_key("bmx"), "Cycles"},
{"Cruiser", "", "Cruiser", 448402357, gameplay.get_hash_key("cruiser"), "Cycles"},
{"Endurex Race Bike", "", "Endurex Race Bike", 3061159916, gameplay.get_hash_key("tribike2"), "Cycles"},
{"Fixter", "", "Fixter", 3458454463, gameplay.get_hash_key("fixter"), "Cycles"},
{"Scorcher", "", "Scorcher", 4108429845, gameplay.get_hash_key("scorcher"), "Cycles"},
{"Tri-Cycles Race Bike", "", "Tri-Cycles Race Bike", 3894672200, gameplay.get_hash_key("tribike3"), "Cycles"},
{"Whippet Race Bike", "", "Whippet Race Bike", 1127861609, gameplay.get_hash_key("tribike"), "Cycles"},
{"Ambulance", "Brute ", "Brute  Ambulance", 1171614426, gameplay.get_hash_key("ambulance"), "Emergency"},
{"FIB", "Declasse", "Declasse FIB", 1127131465, gameplay.get_hash_key("fbi"), "Emergency"},
{"FIB 2", "Declasse", "Declasse FIB 2", 2647026068, gameplay.get_hash_key("fbi2"), "Emergency"},
{"Fire Truck", "MTL", "MTL Fire Truck", 1938952078, gameplay.get_hash_key("firetruk"), "Emergency"},
{"Lifeguard", "Declasse", "Declasse Lifeguard", 469291905, gameplay.get_hash_key("lguard"), "Emergency"},
{"Park Ranger", "Declasse", "Declasse Park Ranger", 741586030, gameplay.get_hash_key("pranger"), "Emergency"},
{"Police Bike", "Western Motorcycle Company", "Western Motorcycle Company Police Bike", 4260343491, gameplay.get_hash_key("policeb"), "Emergency"},
{"Police Cruiser", "Vapid", "Vapid Police Cruiser", 2046537925, gameplay.get_hash_key("police"), "Emergency"},
{"Police Cruiser 2", "Vapid", "Vapid Police Cruiser 2", 2667966721, gameplay.get_hash_key("police2"), "Emergency"},
{"Police Cruiser 3", "Vapid", "Vapid Police Cruiser 3", 1912215274, gameplay.get_hash_key("police3"), "Emergency"},
{"Police Rancher", "Declasse", "Declasse Police Rancher", 2758042359, gameplay.get_hash_key("policeold1"), "Emergency"},
{"Police Riot", "Brute", "Brute Police Riot", 3089277354, gameplay.get_hash_key("riot"), "Emergency"},
{"Police Roadcruiser", "Albany", "Albany Police Roadcruiser", 2515846680, gameplay.get_hash_key("policeold2"), "Emergency"},
{"Police Transporter", "Declasse", "Declasse Police Transporter", 456714581, gameplay.get_hash_key("policet"), "Emergency"},
{"Prison Bus", "Brute", "Brute Prison Bus", 2287941233, gameplay.get_hash_key("pbus"), "Emergency"},
{"RCV", "Brute", "Brute RCV", 2601952180, gameplay.get_hash_key("riot2"), "Emergency"},
{"Sheriff Cruiser", "Vapid", "Vapid Sheriff Cruiser", 2611638396, gameplay.get_hash_key("sheriff"), "Emergency"},
{"Sheriff SUV", "Declasse", "Declasse Sheriff SUV", 1922257928, gameplay.get_hash_key("sheriff2"), "Emergency"},
{"Unmarked Cruiser", "Vapid", "Vapid Unmarked Cruiser", 2321795001, gameplay.get_hash_key("police4"), "Emergency"},
{"Akula", "Buckingham", "Buckingham Akula", 1181327175, gameplay.get_hash_key("akula"), "Helicopters"},
{"Annihilator", "Western Company", "Western Company Annihilator", 837858166, gameplay.get_hash_key("annihilator"), "Helicopters"},
{"Annihilator Stealth", "Western Company", "Western Company Annihilator Stealth", 295054921, gameplay.get_hash_key("annihilator2"), "Helicopters"},
{"Buzzard", "Nagasaki", "Nagasaki Buzzard", 745926877, gameplay.get_hash_key("buzzard2"), "Helicopters"},
{"Buzzard Attack Chopper", "Nagasaki", "Nagasaki Buzzard Attack Chopper", 788747387, gameplay.get_hash_key("buzzard"), "Helicopters"},
{"Cargobob", "Western Company ", "Western Company  Cargobob", 4244420235, gameplay.get_hash_key("cargobob"), "Helicopters"},
{"Cargobob 2", "Western Company ", "Western Company  Cargobob 2", 1621617168, gameplay.get_hash_key("cargobob2"), "Helicopters"},
{"Cargobob 3", "Western Company ", "Western Company  Cargobob 3", 1394036463, gameplay.get_hash_key("cargobob3"), "Helicopters"},
{"Cargobob 4", "Western Company ", "Western Company  Cargobob 4", 2025593404, gameplay.get_hash_key("cargobob4"), "Helicopters"},
{"FH-1 Hunter", "", "FH-1 Hunter", 4252008158, gameplay.get_hash_key("hunter"), "Helicopters"},
{"Frogger", "Maibatsu", "Maibatsu Frogger", 744705981, gameplay.get_hash_key("frogger"), "Helicopters"},
{"Frogger 2", "Maibatsu", "Maibatsu Frogger 2", 1949211328, gameplay.get_hash_key("frogger2"), "Helicopters"},
{"Havok", "Nagasaki", "Nagasaki Havok", 2310691317, gameplay.get_hash_key("havok"), "Helicopters"},
{"Maverick", "Buckingham", "Buckingham Maverick", 2634305738, gameplay.get_hash_key("maverick"), "Helicopters"},
{"Police Maverick", "Buckingham", "Buckingham Police Maverick", 353883353, gameplay.get_hash_key("polmav"), "Helicopters"},
{"Savage", "", "Savage", 4212341271, gameplay.get_hash_key("savage"), "Helicopters"},
{"Sea Sparrow", "", "Sea Sparrow", 3568198617, gameplay.get_hash_key("seasparrow"), "Helicopters"},
{"Skylift", "HYV", "HYV Skylift", 1044954915, gameplay.get_hash_key("skylift"), "Helicopters"},
{"Sparrow", "", "Sparrow", 1229411063, gameplay.get_hash_key("seasparrow2"), "Helicopters"},
{"SuperVolito", "Buckingham", "Buckingham SuperVolito", 710198397, gameplay.get_hash_key("supervolito"), "Helicopters"},
{"SuperVolito Carbon", "Buckingham", "Buckingham SuperVolito Carbon", 2623428164, gameplay.get_hash_key("supervolito2"), "Helicopters"},
{"Swift", "Buckingham", "Buckingham Swift", 3955379698, gameplay.get_hash_key("swift"), "Helicopters"},
{"Swift Deluxe", "Buckingham", "Buckingham Swift Deluxe", 1075432268, gameplay.get_hash_key("swift2"), "Helicopters"},
{"Valkyrie", "Buckingham", "Buckingham Valkyrie", 2694714877, gameplay.get_hash_key("valkyrie"), "Helicopters"},
{"Valkyrie MOD.0", "Buckingham", "Buckingham Valkyrie MOD.0", 1543134283, gameplay.get_hash_key("valkyrie2"), "Helicopters"},
{"Volatus", "Buckingham", "Buckingham Volatus", 2449479409, gameplay.get_hash_key("volatus"), "Helicopters"},
{"Cutter", "HVY", "HVY Cutter", 3288047904, gameplay.get_hash_key("cutter"), "Industrial"},
{"Dock Handler", "HYV", "HYV Dock Handler", 444583674, gameplay.get_hash_key("handler"), "Industrial"},
{"Dozer", "HVY", "HVY Dozer", 1886712733, gameplay.get_hash_key("bulldozer"), "Industrial"},
{"Dump", "HVY", "HVY Dump", 2164484578, gameplay.get_hash_key("dump"), "Industrial"},
{"Flatbed", "MTL", "MTL Flatbed", 1353720154, gameplay.get_hash_key("flatbed"), "Industrial"},
{"Guardian", "Vapid", "Vapid Guardian", 2186977100, gameplay.get_hash_key("guardian"), "Industrial"},
{"Mixer", "HVY", "HVY Mixer", 3510150843, gameplay.get_hash_key("mixer"), "Industrial"},
{"Mixer 2", "HVY", "HVY Mixer 2", 475220373, gameplay.get_hash_key("mixer2"), "Industrial"},
{"Rubble", "JoBuilt", "JoBuilt Rubble", 2589662668, gameplay.get_hash_key("rubble"), "Industrial"},
{"Tipper", "Brute", "Brute Tipper", 48339065, gameplay.get_hash_key("tiptruck"), "Industrial"},
{"Tipper 2", "Brute", "Brute Tipper 2", 3347205726, gameplay.get_hash_key("tiptruck2"), "Industrial"},
{"Anti-Aircraft Trailer", "Vom Feuer", "Vom Feuer Anti-Aircraft Trailer", 2413121211, gameplay.get_hash_key("trailersmall2"), "Military"},
{"APC", "HVY", "HVY APC", 562680400, gameplay.get_hash_key("apc"), "Military"},
{"Apocalypse Scarab", "HVY", "HVY Apocalypse Scarab", 3147997943, gameplay.get_hash_key("scarab"), "Military"},
{"Barracks", "HYV", "HYV Barracks", 3471458123, gameplay.get_hash_key("barracks"), "Military"},
{"Barracks 3", "HYV", "HYV Barracks 3", 630371791, gameplay.get_hash_key("barracks3"), "Military"},
{"Barracks Semi", "HVY", "HVY Barracks Semi", 1074326203, gameplay.get_hash_key("barracks2"), "Military"},
{"Barrage", "HYV", "HYV Barrage", 4081974053, gameplay.get_hash_key("barrage"), "Military"},
{"Chernobog", "HYV", "HYV Chernobog", 3602674979, gameplay.get_hash_key("chernobog"), "Military"},
{"Crusader", "Canis", "Canis Crusader", 321739290, gameplay.get_hash_key("crusader"), "Military"},
{"Future Shock Scarab", "HVY", "HVY Future Shock Scarab", 1542143200, gameplay.get_hash_key("scarab2"), "Military"},
{"Half-track", "Bravado", "Bravado Half-track", 4262731174, gameplay.get_hash_key("halftrack"), "Military"},
{"Invade and Persuade Tank", "", "Invade and Persuade Tank", 3040635986, gameplay.get_hash_key("minitank"), "Military"},
{"Nightmare Scarab", "HVY", "HVY Nightmare Scarab", 3715219435, gameplay.get_hash_key("scarab3"), "Military"},
{"Rhino Tank", "", "Rhino Tank", 782665360, gameplay.get_hash_key("rhino"), "Military"},
{"Thruster", "Mammoth", "Mammoth Thruster", 1489874736, gameplay.get_hash_key("thruster"), "Military"},
{"TM-02 Khanjali", "", "TM-02 Khanjali", 2859440138, gameplay.get_hash_key("khanjali"), "Military"},
{"Vetir", "HYV", "HYV Vetir", 2014313426, gameplay.get_hash_key("vetir"), "Military"},
{"Akuma", "Dinka", "Dinka Akuma", 1672195559, gameplay.get_hash_key("akuma"), "Motorcycles"},
{"Apocalypse Deathbike", "Western", "Western Apocalypse Deathbike", 4267640610, gameplay.get_hash_key("deathbike"), "Motorcycles"},
{"Avarus", "LCC", "LCC Avarus", 2179174271, gameplay.get_hash_key("avarus"), "Motorcycles"},
{"Bagger", "Western", "Western Bagger", 2154536131, gameplay.get_hash_key("bagger"), "Motorcycles"},
{"Bati 801", "Pegassi", "Pegassi Bati 801", 4180675781, gameplay.get_hash_key("bati"), "Motorcycles"},
{"Bati 801RR", "Pegassi", "Pegassi Bati 801RR", 3403504941, gameplay.get_hash_key("bati2"), "Motorcycles"},
{"BF400", "Nagasaki", "Nagasaki BF400", 86520421, gameplay.get_hash_key("bf400"), "Motorcycles"},
{"Carbon RS", "Nagasaki", "Nagasaki Carbon RS", 11251904, gameplay.get_hash_key("carbonrs"), "Motorcycles"},
{"Chimera", "Nagasaki", "Nagasaki Chimera", 6774487, gameplay.get_hash_key("chimera"), "Motorcycles"},
{"Cliffhanger", "Western", "Western Cliffhanger", 390201602, gameplay.get_hash_key("cliffhanger"), "Motorcycles"},
{"Daemon", "Western", "Western Daemon", 2006142190, gameplay.get_hash_key("daemon"), "Motorcycles"},
{"Daemon 2", "Western", "Western Daemon 2", 2890830793, gameplay.get_hash_key("daemon2"), "Motorcycles"},
{"Defiler", "Shitzu", "Shitzu Defiler", 822018448, gameplay.get_hash_key("defiler"), "Motorcycles"},
{"Diabolus", "Principe", "Principe Diabolus", 4055125828, gameplay.get_hash_key("diablous"), "Motorcycles"},
{"Diabolus Custom", "Principe", "Principe Diabolus Custom", 1790834270, gameplay.get_hash_key("diablous2"), "Motorcycles"},
{"Double-T", "Dinka", "Dinka Double-T", 2623969160, gameplay.get_hash_key("double"), "Motorcycles"},
{"Enduro", "Dinka", "Dinka Enduro", 1753414259, gameplay.get_hash_key("enduro"), "Motorcycles"},
{"Esskey", "Pegassi", "Pegassi Esskey", 2035069708, gameplay.get_hash_key("esskey"), "Motorcycles"},
{"Faggio", "Pegassi", "Pegassi Faggio", 55628203, gameplay.get_hash_key("faggio2"), "Motorcycles"},
{"Faggio Mod", "Pegassi", "Pegassi Faggio Mod", 3005788552, gameplay.get_hash_key("faggio3"), "Motorcycles"},
{"Faggio Sport", "Pegassi", "Pegassi Faggio Sport", 2452219115, gameplay.get_hash_key("faggio"), "Motorcycles"},
{"FCR 1000", "Pegassi", "Pegassi FCR 1000", 627535535, gameplay.get_hash_key("fcr"), "Motorcycles"},
{"FCR 1000 Custom", "Pegassi", "Pegassi FCR 1000 Custom", 3537231886, gameplay.get_hash_key("fcr2"), "Motorcycles"},
{"Future Shock Deathbike", "Western", "Western Future Shock Deathbike", 2482017624, gameplay.get_hash_key("deathbike2"), "Motorcycles"},
{"Gargoyle", "Western", "Western Gargoyle", 741090084, gameplay.get_hash_key("gargoyle"), "Motorcycles"},
{"Hakuchou", "Shitzu", "Shitzu Hakuchou", 1265391242, gameplay.get_hash_key("hakuchou"), "Motorcycles"},
{"Hakuchou Drag", "Shitzu", "Shitzu Hakuchou Drag", 4039289119, gameplay.get_hash_key("hakuchou2"), "Motorcycles"},
{"Hexer", "LCC", "LCC Hexer", 301427732, gameplay.get_hash_key("hexer"), "Motorcycles"},
{"Innovation", "LCC", "LCC Innovation", 4135840458, gameplay.get_hash_key("innovation"), "Motorcycles"},
{"Lectro", "Principe", "Principe Lectro", 640818791, gameplay.get_hash_key("lectro"), "Motorcycles"},
{"Manchez", "Maibatsu", "Maibatsu Manchez", 2771538552, gameplay.get_hash_key("manchez"), "Motorcycles"},
{"Manchez Scout", "Maibatsu", "Maibatsu Manchez Scout", 1086534307, gameplay.get_hash_key("manchez2"), "Motorcycles"},
{"Nemesis", "Principe", "Principe Nemesis", 3660088182, gameplay.get_hash_key("nemesis"), "Motorcycles"},
{"Nightblade", "Western", "Western Nightblade", 2688780135, gameplay.get_hash_key("nightblade"), "Motorcycles"},
{"Nightmare Deathbike", "Western", "Western Nightmare Deathbike", 2920466844, gameplay.get_hash_key("deathbike3"), "Motorcycles"},
{"Oppressor", "Pegassi", "Pegassi Oppressor", 884483972, gameplay.get_hash_key("oppressor"), "Motorcycles"},
{"Oppressor Mk II", "Pegassi", "Pegassi Oppressor Mk II", 2069146067, gameplay.get_hash_key("oppressor2"), "Motorcycles"},
{"PCJ 600", "Shitzu", "Shitzu PCJ 600", 3385765638, gameplay.get_hash_key("pcj"), "Motorcycles"},
{"Rampant Rocket", "Western", "Western Rampant Rocket", 916547552, gameplay.get_hash_key("rrocket"), "Motorcycles"},
{"Rat Bike", "Western", "Western Rat Bike", 1873600305, gameplay.get_hash_key("ratbike"), "Motorcycles"},
{"Reever", "Western", "Western Reever", 1993851908, gameplay.get_hash_key("reever"), "Motorcycles"},
{"Ruffian", "Pegassi", "Pegassi Ruffian", 3401388520, gameplay.get_hash_key("ruffian"), "Motorcycles"},
{"Sanchez", "Maibatsu", "Maibatsu Sanchez", 2841686334, gameplay.get_hash_key("sanchez2"), "Motorcycles"},
{"Sanchez (livery)", "Maibatsu", "Maibatsu Sanchez (livery)", 788045382, gameplay.get_hash_key("sanchez"), "Motorcycles"},
{"Sanctus", "LCC", "LCC Sanctus", 1491277511, gameplay.get_hash_key("sanctus"), "Motorcycles"},
{"Shinobi", "Nagasaki", "Nagasaki Shinobi", 1353120668, gameplay.get_hash_key("shinobi"), "Motorcycles"},
{"Shotaro", "Nagasaki", "Nagasaki Shotaro", 3889340782, gameplay.get_hash_key("shotaro"), "Motorcycles"},
{"Sovereign", "Western", "Western Sovereign", 743478836, gameplay.get_hash_key("sovereign"), "Motorcycles"},
{"Stryder", "Nagasaki", "Nagasaki Stryder", 301304410, gameplay.get_hash_key("stryder"), "Motorcycles"},
{"Thrust", "Dinka", "Dinka Thrust", 1836027715, gameplay.get_hash_key("thrust"), "Motorcycles"},
{"Vader", "Shitzu", "Shitzu Vader", 4154065143, gameplay.get_hash_key("vader"), "Motorcycles"},
{"Vindicator", "Dinka", "Dinka Vindicator", 2941886209, gameplay.get_hash_key("vindicator"), "Motorcycles"},
{"Vortex", "Pegassi", "Pegassi Vortex", 3685342204, gameplay.get_hash_key("vortex"), "Motorcycles"},
{"Wolfsbane", "Western", "Western Wolfsbane", 3676349299, gameplay.get_hash_key("wolfsbane"), "Motorcycles"},
{"Zombie Bobber", "Western", "Western Zombie Bobber", 3285698347, gameplay.get_hash_key("zombiea"), "Motorcycles"},
{"Zombie Chopper", "Western", "Western Zombie Chopper", 3724934023, gameplay.get_hash_key("zombieb"), "Motorcycles"},
{"Apocalypse Dominator", "Vapid", "Vapid Apocalypse Dominator", 3606777648, gameplay.get_hash_key("dominator4"), "Muscle"},
{"Apocalypse Impaler", "Declasse", "Declasse Apocalypse Impaler", 1009171724, gameplay.get_hash_key("impaler2"), "Muscle"},
{"Apocalypse Imperator", "Vapid", "Vapid Apocalypse Imperator", 444994115, gameplay.get_hash_key("imperator"), "Muscle"},
{"Apocalypse Slamvan", "Vapid", "Vapid Apocalypse Slamvan", 2233918197, gameplay.get_hash_key("slamvan4"), "Muscle"},
{"Beater Dukes", "Imponte", "Imponte Beater Dukes", 2134119907, gameplay.get_hash_key("dukes3"), "Muscle"},
{"Blade", "Vapid", "Vapid Blade", 3089165662, gameplay.get_hash_key("blade"), "Muscle"},
{"Buccaneer", "Albany", "Albany Buccaneer", 3612755468, gameplay.get_hash_key("buccaneer"), "Muscle"},
{"Buccaneer Custom", "Albany", "Albany Buccaneer Custom", 3281516360, gameplay.get_hash_key("buccaneer2"), "Muscle"},
{"Buffalo STX", "Bravado", "Bravado Buffalo STX", 3675036420, gameplay.get_hash_key("buffalo4"), "Muscle"},
{"Burger Shot Stallion", "Declasse", "Declasse Burger Shot Stallion", 3893323758, gameplay.get_hash_key("stalion2"), "Muscle"},
{"Chino", "Vapid", "Vapid Chino", 349605904, gameplay.get_hash_key("chino"), "Muscle"},
{"Chino Custom", "Vapid", "Vapid Chino Custom", 2933279331, gameplay.get_hash_key("chino2"), "Muscle"},
{"Clique", "Vapid", "Vapid Clique", 2728360112, gameplay.get_hash_key("clique"), "Muscle"},
{"Coquette BlackFin", "Invetero", "Invetero Coquette BlackFin", 784565758, gameplay.get_hash_key("coquette3"), "Muscle"},
{"Deviant", "Schyster", "Schyster Deviant", 1279262537, gameplay.get_hash_key("deviant"), "Muscle"},
{"Dominator", "Vapid", "Vapid Dominator", 80636076, gameplay.get_hash_key("dominator"), "Muscle"},
{"Dominator ASP", "Vapid", "Vapid Dominator ASP", 426742808, gameplay.get_hash_key("dominator7"), "Muscle"},
{"Dominator GTT", "Vapid", "Vapid Dominator GTT", 736672010, gameplay.get_hash_key("dominator8"), "Muscle"},
{"Dominator GTX", "Vapid", "Vapid Dominator GTX", 3308022675, gameplay.get_hash_key("dominator3"), "Muscle"},
{"Drift Yosemite", "Declasse", "Declasse Drift Yosemite", 1693751655, gameplay.get_hash_key("yosemite2"), "Muscle"},
{"Duke O'Death", "Imponte", "Imponte Duke O'Death", 3968823444, gameplay.get_hash_key("dukes2"), "Muscle"},
{"Dukes", "Imponte", "Imponte Dukes", 723973206, gameplay.get_hash_key("dukes"), "Muscle"},
{"Ellie", "Vapid", "Vapid Ellie", 3027423925, gameplay.get_hash_key("ellie"), "Muscle"},
{"Faction", "Willard", "Willard Faction", 2175389151, gameplay.get_hash_key("faction"), "Muscle"},
{"Faction Custom", "Willard", "Willard Faction Custom", 2504420315, gameplay.get_hash_key("faction2"), "Muscle"},
{"Faction Custom Donk", "Willard", "Willard Faction Custom Donk", 2255212070, gameplay.get_hash_key("faction3"), "Muscle"},
{"Future Shock Dominator", "Vapid", "Vapid Future Shock Dominator", 2919906639, gameplay.get_hash_key("dominator5"), "Muscle"},
{"Future Shock Impaler", "Declasse", "Declasse Future Shock Impaler", 2370166601, gameplay.get_hash_key("impaler3"), "Muscle"},
{"Future Shock Imperator", "Vapid", "Vapid Future Shock Imperator", 1637620610, gameplay.get_hash_key("imperator2"), "Muscle"},
{"Future Shock Slamvan", "Vapid", "Vapid Future Shock Slamvan", 373261600, gameplay.get_hash_key("slamvan5"), "Muscle"},
{"Gauntlet", "Bravado", "Bravado Gauntlet", 2494797253, gameplay.get_hash_key("gauntlet"), "Muscle"},
{"Gauntlet Classic", "Bravado", "Bravado Gauntlet Classic", 722226637, gameplay.get_hash_key("gauntlet3"), "Muscle"},
{"Gauntlet Classic Custom", "Bravado", "Bravado Gauntlet Classic Custom", 2172320429, gameplay.get_hash_key("gauntlet5"), "Muscle"},
{"Gauntlet Hellfire", "Bravado", "Bravado Gauntlet Hellfire", 1934384720, gameplay.get_hash_key("gauntlet4"), "Muscle"},
{"Hermes", "Albany", "Albany Hermes", 15219735, gameplay.get_hash_key("hermes"), "Muscle"},
{"Hotknife", "Vapid", "Vapid Hotknife", 37348240, gameplay.get_hash_key("hotknife"), "Muscle"},
{"Hustler", "Vapid", "Vapid Hustler", 600450546, gameplay.get_hash_key("hustler"), "Muscle"},
{"Impaler", "Declasse", "Declasse Impaler", 2198276962, gameplay.get_hash_key("impaler"), "Muscle"},
{"Lost Slamvan", "Vapid", "Vapid Lost Slamvan", 833469436, gameplay.get_hash_key("slamvan2"), "Muscle"},
{"Lurcher", "Albany", "Albany Lurcher", 2068293287, gameplay.get_hash_key("lurcher"), "Muscle"},
{"Manana Custom", "Albany", "Albany Manana Custom", 1717532765, gameplay.get_hash_key("manana2"), "Muscle"},
{"Moonbeam", "Declasse", "Declasse Moonbeam", 525509695, gameplay.get_hash_key("moonbeam"), "Muscle"},
{"Moonbeam Custom", "Declasse", "Declasse Moonbeam Custom", 1896491931, gameplay.get_hash_key("moonbeam2"), "Muscle"},
{"Nightmare Dominator", "Vapid", "Vapid Nightmare Dominator", 3001042683, gameplay.get_hash_key("dominator6"), "Muscle"},
{"Nightmare Impaler", "Declasse", "Declasse Nightmare Impaler", 2550461639, gameplay.get_hash_key("impaler4"), "Muscle"},
{"Nightmare Imperator", "Vapid", "Vapid Nightmare Imperator", 3539435063, gameplay.get_hash_key("imperator3"), "Muscle"},
{"Nightmare Slamvan", "Vapid", "Vapid Nightmare Slamvan", 1742022738, gameplay.get_hash_key("slamvan6"), "Muscle"},
{"Nightshade", "Imponte", "Imponte Nightshade", 2351681756, gameplay.get_hash_key("nightshade"), "Muscle"},
{"Peyote Gasser", "Vapid", "Vapid Peyote Gasser", 2490551588, gameplay.get_hash_key("peyote2"), "Muscle"},
{"Phoenix", "Imponte", "Imponte Phoenix", 2199527893, gameplay.get_hash_key("phoenix"), "Muscle"},
{"Picador", "Cheval", "Cheval Picador", 1507916787, gameplay.get_hash_key("picador"), "Muscle"},
{"Pisswasser Dominator", "Vapid", "Vapid Pisswasser Dominator", 3379262425, gameplay.get_hash_key("dominator2"), "Muscle"},
{"Rat-Loader", "Bravado", "Bravado Rat-Loader", 3627815886, gameplay.get_hash_key("ratloader"), "Muscle"},
{"Rat-Truck", "Bravado", "Bravado Rat-Truck", 3705788919, gameplay.get_hash_key("ratloader2"), "Muscle"},
{"Redwood Gauntlet", "Bravado", "Bravado Redwood Gauntlet", 349315417, gameplay.get_hash_key("gauntlet2"), "Muscle"},
{"Ruiner", "Imponte", "Imponte Ruiner", 4067225593, gameplay.get_hash_key("ruiner"), "Muscle"},
{"Ruiner 2000", "Imponte", "Imponte Ruiner 2000", 941494461, gameplay.get_hash_key("ruiner2"), "Muscle"},
{"Ruiner 3", "Imponte", "Imponte Ruiner 3", 777714999, gameplay.get_hash_key("ruiner3"), "Muscle"},
{"Sabre Turbo", "Declasse", "Declasse Sabre Turbo", 2609945748, gameplay.get_hash_key("sabregt"), "Muscle"},
{"Sabre Turbo Custom", "Declasse", "Declasse Sabre Turbo Custom", 223258115, gameplay.get_hash_key("sabregt2"), "Muscle"},
{"Slamvan", "Vapid", "Vapid Slamvan", 729783779, gameplay.get_hash_key("slamvan"), "Muscle"},
{"Slamvan Custom", "Vapid", "Vapid Slamvan Custom", 1119641113, gameplay.get_hash_key("slamvan3"), "Muscle"},
{"Stallion", "Declasse", "Declasse Stallion", 1923400478, gameplay.get_hash_key("stalion"), "Muscle"},
{"Tampa", "Declasse", "Declasse Tampa", 972671128, gameplay.get_hash_key("tampa"), "Muscle"},
{"Tulip", "Declasse", "Declasse Tulip", 1456744817, gameplay.get_hash_key("tulip"), "Muscle"},
{"Vamos", "Declasse", "Declasse Vamos", 4245851645, gameplay.get_hash_key("vamos"), "Muscle"},
{"Vigero", "Declasse", "Declasse Vigero", 3469130167, gameplay.get_hash_key("vigero"), "Muscle"},
{"Virgo", "Albany", "Albany Virgo", 3796912450, gameplay.get_hash_key("virgo"), "Muscle"},
{"Virgo Classic", "Dundreary", "Dundreary Virgo Classic", 16646064, gameplay.get_hash_key("virgo3"), "Muscle"},
{"Virgo Classic Custom", "Dundreary", "Dundreary Virgo Classic Custom", 3395457658, gameplay.get_hash_key("virgo2"), "Muscle"},
{"Voodoo", "Declasse", "Declasse Voodoo", 523724515, gameplay.get_hash_key("voodoo2"), "Muscle"},
{"Voodoo Custom", "Declasse", "Declasse Voodoo Custom", 2006667053, gameplay.get_hash_key("voodoo"), "Muscle"},
{"Weaponized Tampa", "Declasse", "Declasse Weaponized Tampa", 3084515313, gameplay.get_hash_key("tampa3"), "Muscle"},
{"Yosemite", "Declasse", "Declasse Yosemite", 1871995513, gameplay.get_hash_key("yosemite"), "Muscle"},
{"Apocalypse Bruiser", "Benefactor", "Benefactor Apocalypse Bruiser", 668439077, gameplay.get_hash_key("bruiser"), "Off-Road"},
{"Apocalypse Brutus", "Declasse", "Declasse Apocalypse Brutus", 2139203625, gameplay.get_hash_key("brutus"), "Off-Road"},
{"Apocalypse Sasquatch", "Bravado", "Bravado Apocalypse Sasquatch", 1721676810, gameplay.get_hash_key("monster3"), "Off-Road"},
{"Bifta", "BF", "BF Bifta", 3945366167, gameplay.get_hash_key("bifta"), "Off-Road"},
{"Blazer", "Nagasaki", "Nagasaki Blazer", 2166734073, gameplay.get_hash_key("blazer"), "Off-Road"},
{"Blazer Aqua", "Nagasaki", "Nagasaki Blazer Aqua", 2704629607, gameplay.get_hash_key("blazer5"), "Off-Road"},
{"Blazer Lifeguard", "Nagasaki", "Nagasaki Blazer Lifeguard", 4246935337, gameplay.get_hash_key("blazer2"), "Off-Road"},
{"Bodhi", "Canis", "Canis Bodhi", 2859047862, gameplay.get_hash_key("bodhi2"), "Off-Road"},
{"Brawler", "Coil", "Coil Brawler", 2815302597, gameplay.get_hash_key("brawler"), "Off-Road"},
{"Caracara", "Vapid", "Vapid Caracara", 1254014755, gameplay.get_hash_key("caracara"), "Off-Road"},
{"Caracara 4x4", "Vapid", "Vapid Caracara 4x4", 2945871676, gameplay.get_hash_key("caracara2"), "Off-Road"},
{"Desert Raid", "Vapid", "Vapid Desert Raid", 3631668194, gameplay.get_hash_key("trophytruck2"), "Off-Road"},
{"Dubsta 6x6", "Benefactor", "Benefactor Dubsta 6x6", 3057713523, gameplay.get_hash_key("dubsta3"), "Off-Road"},
{"Dune Buggy", "BF", "BF Dune Buggy", 2633113103, gameplay.get_hash_key("dune"), "Off-Road"},
{"Dune FAV", "BF", "BF Dune FAV", 1897744184, gameplay.get_hash_key("dune3"), "Off-Road"},
{"Duneloader", "Bravado", "Bravado Duneloader", 1770332643, gameplay.get_hash_key("dloader"), "Off-Road"},
{"Everon", "Karin", "Karin Everon", 2538945576, gameplay.get_hash_key("everon"), "Off-Road"},
{"Freecrawler", "Canis", "Canis Freecrawler", 4240635011, gameplay.get_hash_key("freecrawler"), "Off-Road"},
{"Future Shock Bruiser", "Benefactor", "Benefactor Future Shock Bruiser", 2600885406, gameplay.get_hash_key("bruiser2"), "Off-Road"},
{"Future Shock Brutus", "Declasse", "Declasse Future Shock Brutus", 2403970600, gameplay.get_hash_key("brutus2"), "Off-Road"},
{"Future Shock Sasquatch", "Bravado", "Bravado Future Shock Sasquatch", 840387324, gameplay.get_hash_key("monster4"), "Off-Road"},
{"Hellion", "Annis", "Annis Hellion", 3932816511, gameplay.get_hash_key("hellion"), "Off-Road"},
{"Hot Rod Blazer", "Nagasaki", "Nagasaki Hot Rod Blazer", 3025077634, gameplay.get_hash_key("blazer3"), "Off-Road"},
{"Injection", "BF", "BF Injection", 1126868326, gameplay.get_hash_key("bfinjection"), "Off-Road"},
{"Insurgent", "HVY", "HVY Insurgent", 2071877360, gameplay.get_hash_key("insurgent2"), "Off-Road"},
{"Insurgent Pick-Up", "HVY", "HVY Insurgent Pick-Up", 2434067162, gameplay.get_hash_key("insurgent"), "Off-Road"},
{"Insurgent Pick-Up Custom", "HVY", "HVY Insurgent Pick-Up Custom", 2370534026, gameplay.get_hash_key("insurgent3"), "Off-Road"},
{"Kalahari", "Canis", "Canis Kalahari", 92612664, gameplay.get_hash_key("kalahari"), "Off-Road"},
{"Kamacho", "Canis", "Canis Kamacho", 4173521127, gameplay.get_hash_key("kamacho"), "Off-Road"},
{"Liberator", "Vapid", "Vapid Liberator", 3449006043, gameplay.get_hash_key("monster"), "Off-Road"},
{"Marshall", "Cheval", "Cheval Marshall", 1233534620, gameplay.get_hash_key("marshall"), "Off-Road"},
{"Menacer", "HVY", "HVY Menacer", 2044532910, gameplay.get_hash_key("menacer"), "Off-Road"},
{"Mesa 3", "Canis", "Canis Mesa 3", 2230595153, gameplay.get_hash_key("mesa3"), "Off-Road"},
{"Nightmare Bruiser", "Benefactor", "Benefactor Nightmare Bruiser", 2252616474, gameplay.get_hash_key("bruiser3"), "Off-Road"},
{"Nightmare Brutus", "Declasse", "Declasse Nightmare Brutus", 2038858402, gameplay.get_hash_key("brutus3"), "Off-Road"},
{"Nightmare Sasquatch", "Bravado", "Bravado Nightmare Sasquatch", 3579220348, gameplay.get_hash_key("monster5"), "Off-Road"},
{"Nightshark", "HVY", "HVY Nightshark", 433954513, gameplay.get_hash_key("nightshark"), "Off-Road"},
{"Outlaw", "Nagasaki", "Nagasaki Outlaw", 408825843, gameplay.get_hash_key("outlaw"), "Off-Road"},
{"Patriot Mil-Spec", "Mammoth", "Mammoth Patriot Mil-Spec", 3624880708, gameplay.get_hash_key("patriot3"), "Off-Road"},
{"Ramp Buggy", "BF", "BF Ramp Buggy", 3982671785, gameplay.get_hash_key("dune5"), "Off-Road"},
{"Ramp Buggy Custom", "BF", "BF Ramp Buggy Custom", 3467805257, gameplay.get_hash_key("dune4"), "Off-Road"},
{"Rancher XL", "Declasse", "Declasse Rancher XL", 1645267888, gameplay.get_hash_key("rancherxl"), "Off-Road"},
{"Rancher XL 2", "Declasse", "Declasse Rancher XL 2", 1933662059, gameplay.get_hash_key("rancherxl2"), "Off-Road"},
{"RC Bandito", "", "RC Bandito", 4008920556, gameplay.get_hash_key("rcbandito"), "Off-Road"},
{"Rebel", "Karin", "Karin Rebel", 2249373259, gameplay.get_hash_key("rebel2"), "Off-Road"},
{"Riata", "Vapid", "Vapid Riata", 2762269779, gameplay.get_hash_key("riata"), "Off-Road"},
{"Rusty Rebel", "Karin", "Karin Rusty Rebel", 3087195462, gameplay.get_hash_key("rebel"), "Off-Road"},
{"Sandking SWB", "Vapid", "Vapid Sandking SWB", 989381445, gameplay.get_hash_key("sandking2"), "Off-Road"},
{"Sandking XL", "Vapid", "Vapid Sandking XL", 3105951696, gameplay.get_hash_key("sandking"), "Off-Road"},
{"Space Docker", "BF", "BF Space Docker", 534258863, gameplay.get_hash_key("dune2"), "Off-Road"},
{"Street Blazer", "Nagasaki", "Nagasaki Street Blazer", 3854198872, gameplay.get_hash_key("blazer4"), "Off-Road"},
{"Technical", "Karin", "Karin Technical", 2198148358, gameplay.get_hash_key("technical"), "Off-Road"},
{"Technical Aqua", "Karin", "Karin Technical Aqua", 1180875963, gameplay.get_hash_key("technical2"), "Off-Road"},
{"Technical Custom", "Karin", "Karin Technical Custom", 1356124575, gameplay.get_hash_key("technical3"), "Off-Road"},
{"Trophy Truck", "Vapid", "Vapid Trophy Truck", 101905590, gameplay.get_hash_key("trophytruck"), "Off-Road"},
{"Vagrant", "Maxwell", "Maxwell Vagrant", 740289177, gameplay.get_hash_key("vagrant"), "Off-Road"},
{"Verus", "Dinka", "Dinka Verus", 298565713, gameplay.get_hash_key("verus"), "Off-Road"},
{"Winky", "Vapid", "Vapid Winky", 4084658662, gameplay.get_hash_key("winky"), "Off-Road"},
{"Yosemite Rancher", "Declasse", "Declasse Yosemite Rancher", 67753863, gameplay.get_hash_key("yosemite3"), "Off-Road"},
{"Zhaba", "RUNE", "RUNE Zhaba", 1284356689, gameplay.get_hash_key("zhaba"), "Off-Road"},
{"BR8", "Benefactor", "Benefactor BR8", 1492612435, gameplay.get_hash_key("openwheel1"), "Open Wheel"},
{"DR1", "Declasse", "Declasse DR1", 1181339704, gameplay.get_hash_key("openwheel2"), "Open Wheel"},
{"PR4", "Progen", "Progen PR4", 340154634, gameplay.get_hash_key("formula"), "Open Wheel"},
{"R88", "Ocelot", "Ocelot R88", 2334210311, gameplay.get_hash_key("formula2"), "Open Wheel"},
{"Alpha-Z1", "Buckingham", "Buckingham Alpha-Z1", 2771347558, gameplay.get_hash_key("alphaz1"), "Planes"},
{"Atomic Blimp", "", "Atomic Blimp", 4143991942, gameplay.get_hash_key("blimp"), "Planes"},
{"Avenger", "Mammoth", "Mammoth Avenger", 2176659152, gameplay.get_hash_key("avenger"), "Planes"},
{"Avenger 2", "Mammoth", "Mammoth Avenger 2", 408970549, gameplay.get_hash_key("avenger2"), "Planes"},
{"B-11 Strikeforce", "", "B-11 Strikeforce", 1692272545, gameplay.get_hash_key("strikeforce"), "Planes"},
{"Besra", "Western", "Western Besra", 1824333165, gameplay.get_hash_key("besra"), "Planes"},
{"Blimp", "", "Blimp", 3987008919, gameplay.get_hash_key("blimp3"), "Planes"},
{"Cargo Plane", "", "Cargo Plane", 368211810, gameplay.get_hash_key("cargoplane"), "Planes"},
{"Cuban 800", "Western Company ", "Western Company  Cuban 800", 3650256867, gameplay.get_hash_key("cuban800"), "Planes"},
{"Dodo", "Mammoth", "Mammoth Dodo", 3393804037, gameplay.get_hash_key("dodo"), "Planes"},
{"Duster", "Western Company ", "Western Company  Duster", 970356638, gameplay.get_hash_key("duster"), "Planes"},
{"Howard NX-25", "Buckingham", "Buckingham Howard NX-25", 3287439187, gameplay.get_hash_key("howard"), "Planes"},
{"Hydra", "Mammoth", "Mammoth Hydra", 970385471, gameplay.get_hash_key("hydra"), "Planes"},
{"Jet", "", "Jet", 1058115860, gameplay.get_hash_key("jet"), "Planes"},
{"LF-22 Starling", "", "LF-22 Starling", 2594093022, gameplay.get_hash_key("starling"), "Planes"},
{"Luxor", "Buckingham", "Buckingham Luxor", 621481054, gameplay.get_hash_key("luxor"), "Planes"},
{"Luxor Deluxe", "Buckingham", "Buckingham Luxor Deluxe", 3080673438, gameplay.get_hash_key("luxor2"), "Planes"},
{"Mallard", "Western Company ", "Western Company  Mallard", 2172210288, gameplay.get_hash_key("stunt"), "Planes"},
{"Mammatus", "Jobuilt", "Jobuilt Mammatus", 2548391185, gameplay.get_hash_key("mammatus"), "Planes"},
{"Miljet", "Buckingham", "Buckingham Miljet", 165154707, gameplay.get_hash_key("miljet"), "Planes"},
{"Mogul", "Mammoth", "Mammoth Mogul", 3545667823, gameplay.get_hash_key("mogul"), "Planes"},
{"Nimbus", "Buckingham", "Buckingham Nimbus", 2999939664, gameplay.get_hash_key("nimbus"), "Planes"},
{"P-45 Nokota", "", "P-45 Nokota", 1036591958, gameplay.get_hash_key("nokota"), "Planes"},
{"P-996 LAZER", "Jobuilt", "Jobuilt P-996 LAZER", 3013282534, gameplay.get_hash_key("lazer"), "Planes"},
{"Pyro", "Buckingham", "Buckingham Pyro", 2908775872, gameplay.get_hash_key("pyro"), "Planes"},
{"RM-10 Bombushka", "", "RM-10 Bombushka", 4262088844, gameplay.get_hash_key("bombushka"), "Planes"},
{"RO-86 Alkonost", "", "RO-86 Alkonost", 3929093893, gameplay.get_hash_key("alkonost"), "Planes"},
{"Rogue", "Western", "Western Rogue", 3319621991, gameplay.get_hash_key("rogue"), "Planes"},
{"Seabreeze", "Western", "Western Seabreeze", 3902291871, gameplay.get_hash_key("seabreeze"), "Planes"},
{"Shamal", "Buckingham", "Buckingham Shamal", 3080461301, gameplay.get_hash_key("shamal"), "Planes"},
{"Titan", "", "Titan", 1981688531, gameplay.get_hash_key("titan"), "Planes"},
{"Tula", "Mammoth", "Mammoth Tula", 1043222410, gameplay.get_hash_key("tula"), "Planes"},
{"Ultralight", "Nagasaki", "Nagasaki Ultralight", 2531412055, gameplay.get_hash_key("microlight"), "Planes"},
{"V-65 Molotok", "", "V-65 Molotok", 1565978651, gameplay.get_hash_key("molotok"), "Planes"},
{"Velum", "Jobuilt", "Jobuilt Velum", 2621610858, gameplay.get_hash_key("velum"), "Planes"},
{"Velum 5-Seater", "Jobuilt", "Jobuilt Velum 5-Seater", 1077420264, gameplay.get_hash_key("velum2"), "Planes"},
{"Vestra", "Buckingham", "Buckingham Vestra", 1341619767, gameplay.get_hash_key("vestra"), "Planes"},
{"Volatol", "", "Volatol", 447548909, gameplay.get_hash_key("volatol"), "Planes"},
{"Xero Blimp", "", "Xero Blimp", 3681241380, gameplay.get_hash_key("blimp2"), "Planes"},
{"Asea", "Declasse", "Declasse Asea", 2485144969, gameplay.get_hash_key("asea"), "Sedans"},
{"Asea 2", "Declasse", "Declasse Asea 2", 2487343317, gameplay.get_hash_key("asea2"), "Sedans"},
{"Asterope", "Karin", "Karin Asterope", 2391954683, gameplay.get_hash_key("asterope"), "Sedans"},
{"Cinquemila", "Lampadati", "Lampadati Cinquemila", 2767531027, gameplay.get_hash_key("cinquemila"), "Sedans"},
{"Cognoscenti", "Enus", "Enus Cognoscenti", 2264796000, gameplay.get_hash_key("cognoscenti"), "Sedans"},
{"Cognoscenti (Armored)", "Enus", "Enus Cognoscenti (Armored)", 3690124666, gameplay.get_hash_key("cognoscenti2"), "Sedans"},
{"Cognoscenti 55", "Enus", "Enus Cognoscenti 55", 906642318, gameplay.get_hash_key("cog55"), "Sedans"},
{"Cognoscenti 55 (Armored)", "Enus", "Enus Cognoscenti 55 (Armored)", 704435172, gameplay.get_hash_key("cog552"), "Sedans"},
{"Deity", "Enus", "Enus Deity", 1532171089, gameplay.get_hash_key("deity"), "Sedans"},
{"Emperor", "Albany", "Albany Emperor", 3609690755, gameplay.get_hash_key("emperor"), "Sedans"},
{"Emperor 2", "Albany", "Albany Emperor 2", 2411965148, gameplay.get_hash_key("emperor2"), "Sedans"},
{"Emperor 3", "Albany", "Albany Emperor 3", 3053254478, gameplay.get_hash_key("emperor3"), "Sedans"},
{"Fugitive", "Cheval", "Cheval Fugitive", 1909141499, gameplay.get_hash_key("fugitive"), "Sedans"},
{"Glendale", "Benefactor", "Benefactor Glendale", 75131841, gameplay.get_hash_key("glendale"), "Sedans"},
{"Glendale Custom", "Benefactor", "Benefactor Glendale Custom", 3381377750, gameplay.get_hash_key("glendale2"), "Sedans"},
{"Ingot", "Vulcar", "Vulcar Ingot", 3005245074, gameplay.get_hash_key("ingot"), "Sedans"},
{"Intruder", "Karin", "Karin Intruder", 886934177, gameplay.get_hash_key("intruder"), "Sedans"},
{"Premier", "Declasse", "Declasse Premier", 2411098011, gameplay.get_hash_key("premier"), "Sedans"},
{"Primo", "Albany", "Albany Primo", 3144368207, gameplay.get_hash_key("primo"), "Sedans"},
{"Primo Custom", "Albany", "Albany Primo Custom", 2254540506, gameplay.get_hash_key("primo2"), "Sedans"},
{"Regina", "Dundreary", "Dundreary Regina", 4280472072, gameplay.get_hash_key("regina"), "Sedans"},
{"Romero Hearse", "Chariot", "Chariot Romero Hearse", 627094268, gameplay.get_hash_key("romero"), "Sedans"},
{"Schafter", "Benefactor", "Benefactor Schafter", 3039514899, gameplay.get_hash_key("schafter2"), "Sedans"},
{"Schafter LWB (Armored)", "Benefactor", "Benefactor Schafter LWB (Armored)", 1922255844, gameplay.get_hash_key("schafter6"), "Sedans"},
{"Schafter V12 (Armored)", "Benefactor", "Benefactor Schafter V12 (Armored)", 3406724313, gameplay.get_hash_key("schafter5"), "Sedans"},
{"Stafford", "Enus", "Enus Stafford", 321186144, gameplay.get_hash_key("stafford"), "Sedans"},
{"Stanier", "Vapid", "Vapid Stanier", 2817386317, gameplay.get_hash_key("stanier"), "Sedans"},
{"Stratum", "Zirconium", "Zirconium Stratum", 1723137093, gameplay.get_hash_key("stratum"), "Sedans"},
{"Stretch", "Dundreary", "Dundreary Stretch", 2333339779, gameplay.get_hash_key("stretch"), "Sedans"},
{"Super Diamond", "Enus", "Enus Super Diamond", 1123216662, gameplay.get_hash_key("superd"), "Sedans"},
{"Surge", "Cheval", "Cheval Surge", 2400073108, gameplay.get_hash_key("surge"), "Sedans"},
{"Tailgater", "Obey", "Obey Tailgater", 3286105550, gameplay.get_hash_key("tailgater"), "Sedans"},
{"Tailgater S", "Obey", "Obey Tailgater S", 3050505892, gameplay.get_hash_key("tailgater2"), "Sedans"},
{"Turreted Limo", "Benefactor", "Benefactor Turreted Limo", 4180339789, gameplay.get_hash_key("limo2"), "Sedans"},
{"Warrener", "Vulcar", "Vulcar Warrener", 1373123368, gameplay.get_hash_key("warrener"), "Sedans"},
{"Warrener HKR", "Vulcar", "Vulcar Warrener HKR", 579912970, gameplay.get_hash_key("warrener2"), "Sedans"},
{"Washington", "Albany", "Albany Washington", 1777363799, gameplay.get_hash_key("washington"), "Sedans"},
{"Airport Bus", "Brute", "Brute Airport Bus", 1283517198, gameplay.get_hash_key("airbus"), "Service"},
{"Brickade", "MTL", "MTL Brickade", 3989239879, gameplay.get_hash_key("brickade"), "Service"},
{"Bus", "Brute ", "Brute  Bus", 3581397346, gameplay.get_hash_key("bus"), "Service"},
{"Dashound", "Western Company ", "Western Company  Dashound", 2222034228, gameplay.get_hash_key("coach"), "Service"},
{"Dune", "MTL", "MTL Dune", 2191146052, gameplay.get_hash_key("rallytruck"), "Service"},
{"Festival Bus", "Vapid", "Vapid Festival Bus", 345756458, gameplay.get_hash_key("pbus2"), "Service"},
{"Rental Shuttle Bus", "Brute", "Brute Rental Shuttle Bus", 3196165219, gameplay.get_hash_key("rentalbus"), "Service"},
{"Taxi", "Vapid", "Vapid Taxi", 3338918751, gameplay.get_hash_key("taxi"), "Service"},
{"Tourbus", "Brute", "Brute Tourbus", 1941029835, gameplay.get_hash_key("tourbus"), "Service"},
{"Trashmaster", "Jobuilt", "Jobuilt Trashmaster", 1917016601, gameplay.get_hash_key("trash"), "Service"},
{"Trashmaster 2", "Brute", "Brute Trashmaster 2", 3039269212, gameplay.get_hash_key("trash2"), "Service"},
{"Wastelander", "MTL", "MTL Wastelander", 2382949506, gameplay.get_hash_key("wastelander"), "Service"},
{"8F Drafter", "Obey", "Obey 8F Drafter", 686471183, gameplay.get_hash_key("drafter"), "Sports"},
{"9F", "Obey", "Obey 9F", 1032823388, gameplay.get_hash_key("ninef"), "Sports"},
{"9F Cabrio", "Obey", "Obey 9F Cabrio", 2833484545, gameplay.get_hash_key("ninef2"), "Sports"},
{"Alpha", "Albany", "Albany Alpha", 767087018, gameplay.get_hash_key("alpha"), "Sports"},
{"Apocalypse ZR380", "Annis", "Annis Apocalypse ZR380", 540101442, gameplay.get_hash_key("zr380"), "Sports"},
{"Banshee", "Bravado", "Bravado Banshee", 3253274834, gameplay.get_hash_key("banshee"), "Sports"},
{"Bestia GTS", "Grotti", "Grotti Bestia GTS", 1274868363, gameplay.get_hash_key("bestiagts"), "Sports"},
{"Blista Compact", "Dinka", "Dinka Blista Compact", 1039032026, gameplay.get_hash_key("blista2"), "Sports"},
{"Buffalo", "Bravado", "Bravado Buffalo", 3990165190, gameplay.get_hash_key("buffalo"), "Sports"},
{"Buffalo S", "Bravado", "Bravado Buffalo S", 736902334, gameplay.get_hash_key("buffalo2"), "Sports"},
{"Calico GTF", "Karin", "Karin Calico GTF", 3101054893, gameplay.get_hash_key("calico"), "Sports"},
{"Carbonizzare", "Grotti", "Grotti Carbonizzare", 2072687711, gameplay.get_hash_key("carbonizzare"), "Sports"},
{"Comet", "Pfister", "Pfister Comet", 3249425686, gameplay.get_hash_key("comet2"), "Sports"},
{"Comet Retro Custom", "Pfister", "Pfister Comet Retro Custom", 2272483501, gameplay.get_hash_key("comet3"), "Sports"},
{"Comet S2", "Pfister", "Pfister Comet S2", 2568944644, gameplay.get_hash_key("comet6"), "Sports"},
{"Comet S2 Cabrio", "Pfister", "Pfister Comet S2 Cabrio", 1141395928, gameplay.get_hash_key("comet7"), "Sports"},
{"Comet Safari", "Pfister", "Pfister Comet Safari", 1561920505, gameplay.get_hash_key("comet4"), "Sports"},
{"Comet SR", "Pfister", "Pfister Comet SR", 661493923, gameplay.get_hash_key("comet5"), "Sports"},
{"Coquette", "Invetero", "Invetero Coquette", 108773431, gameplay.get_hash_key("coquette"), "Sports"},
{"Coquette D10", "Invetero", "Invetero Coquette D10", 2566281822, gameplay.get_hash_key("coquette4"), "Sports"},
{"Cypher", "Ubermacht", "Ubermacht Cypher", 1755697647, gameplay.get_hash_key("cypher"), "Sports"},
{"Drift Tampa", "Declasse", "Declasse Drift Tampa", 3223586949, gameplay.get_hash_key("tampa2"), "Sports"},
{"Elegy Retro Custom", "Annis", "Annis Elegy Retro Custom", 196747873, gameplay.get_hash_key("elegy"), "Sports"},
{"Elegy RH8", "Annis", "Annis Elegy RH8", 3728579874, gameplay.get_hash_key("elegy2"), "Sports"},
{"Euros", "Annis", "Annis Euros", 2038480341, gameplay.get_hash_key("euros"), "Sports"},
{"Feltzer", "Benefactor", "Benefactor Feltzer", 2299640309, gameplay.get_hash_key("feltzer2"), "Sports"},
{"Flash GT", "Vapid", "Vapid Flash GT", 3035832600, gameplay.get_hash_key("flashgt"), "Sports"},
{"Furore GT", "Lampadati", "Lampadati Furore GT", 3205927392, gameplay.get_hash_key("furoregt"), "Sports"},
{"Fusilade", "Schyster", "Schyster Fusilade", 499169875, gameplay.get_hash_key("fusilade"), "Sports"},
{"Futo", "Karin", "Karin Futo", 2016857647, gameplay.get_hash_key("futo"), "Sports"},
{"Futo GTX", "Karin", "Karin Futo GTX", 2787736776, gameplay.get_hash_key("futo2"), "Sports"},
{"Future Shock ZR380", "Annis", "Annis Future Shock ZR380", 3188846534, gameplay.get_hash_key("zr3802"), "Sports"},
{"GB200", "Vapid", "Vapid GB200", 1909189272, gameplay.get_hash_key("gb200"), "Sports"},
{"Go Go Monkey Blista", "Dinka", "Dinka Go Go Monkey Blista", 3703315515, gameplay.get_hash_key("blista3"), "Sports"},
{"Growler", "Pfister", "Pfister Growler", 1304459735, gameplay.get_hash_key("growler"), "Sports"},
{"Hotring Sabre", "Declasse", "Declasse Hotring Sabre", 1115909093, gameplay.get_hash_key("hotring"), "Sports"},
{"Imorgon", "Overflod", "Overflod Imorgon", 3162245632, gameplay.get_hash_key("imorgon"), "Sports"},
{"Issi Sport", "Weeny", "Weeny Issi Sport", 1854776567, gameplay.get_hash_key("issi7"), "Sports"},
{"Itali GTO", "Grotti", "Grotti Itali GTO", 3963499524, gameplay.get_hash_key("italigto"), "Sports"},
{"Itali RSX", "Grotti", "Grotti Itali RSX", 3145241962, gameplay.get_hash_key("italirsx"), "Sports"},
{"Jester", "Dinka", "Dinka Jester", 2997294755, gameplay.get_hash_key("jester"), "Sports"},
{"Jester (Racecar)", "Dinka", "Dinka Jester (Racecar)", 3188613414, gameplay.get_hash_key("jester2"), "Sports"},
{"Jester Classic", "Dinka", "Dinka Jester Classic", 4080061290, gameplay.get_hash_key("jester3"), "Sports"},
{"Jester RR", "Dinka", "Dinka Jester RR", 2712905841, gameplay.get_hash_key("jester4"), "Sports"},
{"Jugular", "Ocelot", "Ocelot Jugular", 4086055493, gameplay.get_hash_key("jugular"), "Sports"},
{"Khamelion", "Hijak", "Hijak Khamelion", 544021352, gameplay.get_hash_key("khamelion"), "Sports"},
{"Komoda", "Lampadati", "Lampadati Komoda", 3460613305, gameplay.get_hash_key("komoda"), "Sports"},
{"Kuruma", "Karin", "Karin Kuruma", 2922118804, gameplay.get_hash_key("kuruma"), "Sports"},
{"Kuruma (Armored)", "Karin", "Karin Kuruma (Armored)", 410882957, gameplay.get_hash_key("kuruma2"), "Sports"},
{"Locust", "Ocelot", "Ocelot Locust", 3353694737, gameplay.get_hash_key("locust"), "Sports"},
{"Lynx", "Ocelot", "Ocelot Lynx", 482197771, gameplay.get_hash_key("lynx"), "Sports"},
{"Massacro", "Dewbauchee", "Dewbauchee Massacro", 4152024626, gameplay.get_hash_key("massacro"), "Sports"},
{"Massacro (Racecar)", "Dewbauchee", "Dewbauchee Massacro (Racecar)", 3663206819, gameplay.get_hash_key("massacro2"), "Sports"},
{"Neo", "Vysser", "Vysser Neo", 2674840994, gameplay.get_hash_key("neo"), "Sports"},
{"Neon", "Pfister", "Pfister Neon", 2445973230, gameplay.get_hash_key("neon"), "Sports"},
{"Nightmare ZR380", "Annis", "Annis Nightmare ZR380", 2816263004, gameplay.get_hash_key("zr3803"), "Sports"},
{"Omnis", "Obey", "Obey Omnis", 3517794615, gameplay.get_hash_key("omnis"), "Sports"},
{"Paragon R", "Enus", "Enus Paragon R", 3847255899, gameplay.get_hash_key("paragon"), "Sports"},
{"Paragon R (Armored)", "Enus", "Enus Paragon R (Armored)", 1416466158, gameplay.get_hash_key("paragon2"), "Sports"},
{"Pariah", "Ocelot", "Ocelot Pariah", 867799010, gameplay.get_hash_key("pariah"), "Sports"},
{"Penumbra", "Maibatsu", "Maibatsu Penumbra", 3917501776, gameplay.get_hash_key("penumbra"), "Sports"},
{"Penumbra FF", "Maibatsu", "Maibatsu Penumbra FF", 3663644634, gameplay.get_hash_key("penumbra2"), "Sports"},
{"Raiden", "Coil", "Coil Raiden", 2765724541, gameplay.get_hash_key("raiden"), "Sports"},
{"Rapid GT", "Dewbauchee", "Dewbauchee Rapid GT", 2360515092, gameplay.get_hash_key("rapidgt"), "Sports"},
{"Rapid GT 2", "Dewbauchee", "Dewbauchee Rapid GT 2", 1737773231, gameplay.get_hash_key("rapidgt2"), "Sports"},
{"Raptor", "BF", "BF Raptor", 3620039993, gameplay.get_hash_key("raptor"), "Sports"},
{"Remus", "Annis", "Annis Remus", 1377217886, gameplay.get_hash_key("remus"), "Sports"},
{"Revolter", "Ubermacht", "Ubermacht Revolter", 3884762073, gameplay.get_hash_key("revolter"), "Sports"},
{"RT3000", "Dinka", "Dinka RT3000", 3842363289, gameplay.get_hash_key("rt3000"), "Sports"},
{"Ruston", "Hijak", "Hijak Ruston", 719660200, gameplay.get_hash_key("ruston"), "Sports"},
{"Schafter LWB", "Benefactor", "Benefactor Schafter LWB", 1489967196, gameplay.get_hash_key("schafter4"), "Sports"},
{"Schafter V12", "Benefactor", "Benefactor Schafter V12", 2809443750, gameplay.get_hash_key("schafter3"), "Sports"},
{"Schlagen GT", "Benefactor", "Benefactor Schlagen GT", 3787471536, gameplay.get_hash_key("schlagen"), "Sports"},
{"Schwartzer", "Benefactor", "Benefactor Schwartzer", 3548084598, gameplay.get_hash_key("schwarzer"), "Sports"},
{"Sentinel Classic", "Ubermacht", "Ubermacht Sentinel Classic", 1104234922, gameplay.get_hash_key("sentinel3"), "Sports"},
{"Seven-70", "Dewbauchee", "Dewbauchee Seven-70", 2537130571, gameplay.get_hash_key("seven70"), "Sports"},
{"Specter", "Dewbauchee", "Dewbauchee Specter", 1886268224, gameplay.get_hash_key("specter"), "Sports"},
{"Specter Custom", "Dewbauchee", "Dewbauchee Specter Custom", 1074745671, gameplay.get_hash_key("specter2"), "Sports"},
{"Sprunk Buffalo", "Bravado", "Bravado Sprunk Buffalo", 237764926, gameplay.get_hash_key("buffalo3"), "Sports"},
{"Streiter", "Benefactor", "Benefactor Streiter", 1741861769, gameplay.get_hash_key("streiter"), "Sports"},
{"Sugoi", "Dinka", "Dinka Sugoi", 987469656, gameplay.get_hash_key("sugoi"), "Sports"},
{"Sultan", "Karin", "Karin Sultan", 970598228, gameplay.get_hash_key("sultan"), "Sports"},
{"Sultan Classic", "Karin", "Karin Sultan Classic", 872704284, gameplay.get_hash_key("sultan2"), "Sports"},
{"Sultan RS Classic", "Karin", "Karin Sultan RS Classic", 4003946083, gameplay.get_hash_key("sultan3"), "Sports"},
{"Surano", "Benefactor", "Benefactor Surano", 384071873, gameplay.get_hash_key("surano"), "Sports"},
{"Tropos Rallye", "Lampadati", "Lampadati Tropos Rallye", 1887331236, gameplay.get_hash_key("tropos"), "Sports"},
{"Vectre", "Emperor", "Emperor Vectre", 2754593701, gameplay.get_hash_key("vectre"), "Sports"},
{"Verlierer", "Bravado", "Bravado Verlierer", 1102544804, gameplay.get_hash_key("verlierer2"), "Sports"},
{"Veto Classic", "Dinka", "Dinka Veto Classic", 3437611258, gameplay.get_hash_key("veto"), "Sports"},
{"Veto Modern", "Dinka", "Dinka Veto Modern", 2802050217, gameplay.get_hash_key("veto2"), "Sports"},
{"V-STR", "Albany", "Albany V-STR", 1456336509, gameplay.get_hash_key("vstr"), "Sports"},
{"ZR350", "Annis", "Annis ZR350", 2436313176, gameplay.get_hash_key("zr350"), "Sports"},
{"190z", "Karin", "Karin 190z", 838982985, gameplay.get_hash_key("z190"), "Sports Classics"},
{"Ardent", "Ocelot", "Ocelot Ardent", 159274291, gameplay.get_hash_key("ardent"), "Sports Classics"},
{"Casco", "Lampadati", "Lampadati Casco", 941800958, gameplay.get_hash_key("casco"), "Sports Classics"},
{"Cheburek", "RUNE", "RUNE Cheburek", 3306466016, gameplay.get_hash_key("cheburek"), "Sports Classics"},
{"Cheetah Classic", "Grotti", "Grotti Cheetah Classic", 223240013, gameplay.get_hash_key("cheetah2"), "Sports Classics"},
{"Coquette Classic", "Invetero", "Invetero Coquette Classic", 1011753235, gameplay.get_hash_key("coquette2"), "Sports Classics"},
{"Deluxo", "Imponte", "Imponte Deluxo", 1483171323, gameplay.get_hash_key("deluxo"), "Sports Classics"},
{"Dynasty", "Weeny", "Weeny Dynasty", 310284501, gameplay.get_hash_key("dynasty"), "Sports Classics"},
{"Fagaloa", "Vulcar", "Vulcar Fagaloa", 1617472902, gameplay.get_hash_key("fagaloa"), "Sports Classics"},
{"FrÃ¤nken Stange", "Albany", "Albany FrÃ¤nken Stange", 3463132580, gameplay.get_hash_key("btype2"), "Sports Classics"},
{"GT500", "Grotti", "Grotti GT500", 2215179066, gameplay.get_hash_key("gt500"), "Sports Classics"},
{"Infernus Classic", "Pegassi", "Pegassi Infernus Classic", 2889029532, gameplay.get_hash_key("infernus2"), "Sports Classics"},
{"JB 700", "Dewbauchee", "Dewbauchee JB 700", 1051415893, gameplay.get_hash_key("jb700"), "Sports Classics"},
{"JB 700W", "Dewbauchee", "Dewbauchee JB 700W", 394110044, gameplay.get_hash_key("jb7002"), "Sports Classics"},
{"Mamba", "Declasse", "Declasse Mamba", 2634021974, gameplay.get_hash_key("mamba"), "Sports Classics"},
{"Manana", "Albany", "Albany Manana", 2170765704, gameplay.get_hash_key("manana"), "Sports Classics"},
{"Michelli GT", "Lampadati", "Lampadati Michelli GT", 1046206681, gameplay.get_hash_key("michelli"), "Sports Classics"},
{"Monroe", "Pegassi", "Pegassi Monroe", 3861591579, gameplay.get_hash_key("monroe"), "Sports Classics"},
{"Nebula Turbo", "Vulcar", "Vulcar Nebula Turbo", 3412338231, gameplay.get_hash_key("nebula"), "Sports Classics"},
{"Peyote", "Vapid", "Vapid Peyote", 1830407356, gameplay.get_hash_key("peyote"), "Sports Classics"},
{"Peyote Custom", "Vapid", "Vapid Peyote Custom", 1107404867, gameplay.get_hash_key("peyote3"), "Sports Classics"},
{"Pigalle", "Lampadati", "Lampadati Pigalle", 1078682497, gameplay.get_hash_key("pigalle"), "Sports Classics"},
{"Rapid GT Classic", "Dewbauchee", "Dewbauchee Rapid GT Classic", 2049897956, gameplay.get_hash_key("rapidgt3"), "Sports Classics"},
{"Retinue", "Vapid", "Vapid Retinue", 1841130506, gameplay.get_hash_key("retinue"), "Sports Classics"},
{"Retinue Mk II", "Vapid", "Vapid Retinue Mk II", 2031587082, gameplay.get_hash_key("retinue2"), "Sports Classics"},
{"Roosevelt", "Albany", "Albany Roosevelt", 117401876, gameplay.get_hash_key("btype"), "Sports Classics"},
{"Roosevelt Valor", "Albany", "Albany Roosevelt Valor", 3692679425, gameplay.get_hash_key("btype3"), "Sports Classics"},
{"Savestra", "Annis", "Annis Savestra", 903794909, gameplay.get_hash_key("savestra"), "Sports Classics"},
{"Stinger", "Grotti", "Grotti Stinger", 1545842587, gameplay.get_hash_key("stinger"), "Sports Classics"},
{"Stinger GT", "Grotti", "Grotti Stinger GT", 2196019706, gameplay.get_hash_key("stingergt"), "Sports Classics"},
{"Stirling GT", "Benefactor", "Benefactor Stirling GT", 2728226064, gameplay.get_hash_key("feltzer3"), "Sports Classics"},
{"Stromberg", "Ocelot", "Ocelot Stromberg", 886810209, gameplay.get_hash_key("stromberg"), "Sports Classics"},
{"Swinger", "Ocelot", "Ocelot Swinger", 500482303, gameplay.get_hash_key("swinger"), "Sports Classics"},
{"Toreador", "Pegassi", "Pegassi Toreador", 1455990255, gameplay.get_hash_key("toreador"), "Sports Classics"},
{"Torero", "Pegassi", "Pegassi Torero", 1504306544, gameplay.get_hash_key("torero"), "Sports Classics"},
{"Tornado", "Declasse", "Declasse Tornado", 464687292, gameplay.get_hash_key("tornado"), "Sports Classics"},
{"Tornado 2", "Declasse", "Declasse Tornado 2", 1531094468, gameplay.get_hash_key("tornado2"), "Sports Classics"},
{"Tornado 3", "Declasse", "Declasse Tornado 3", 1762279763, gameplay.get_hash_key("tornado3"), "Sports Classics"},
{"Tornado 4", "Declasse", "Declasse Tornado 4", 2261744861, gameplay.get_hash_key("tornado4"), "Sports Classics"},
{"Tornado Custom", "Declasse", "Declasse Tornado Custom", 2497353967, gameplay.get_hash_key("tornado5"), "Sports Classics"},
{"Tornado Rat Rod", "Declasse", "Declasse Tornado Rat Rod", 2736567667, gameplay.get_hash_key("tornado6"), "Sports Classics"},
{"Turismo Classic", "Grotti", "Grotti Turismo Classic", 3312836369, gameplay.get_hash_key("turismo2"), "Sports Classics"},
{"Viseris", "Lampadati", "Lampadati Viseris", 3903371924, gameplay.get_hash_key("viseris"), "Sports Classics"},
{"Zion Classic", "Ubermacht", "Ubermacht Zion Classic", 1862507111, gameplay.get_hash_key("zion3"), "Sports Classics"},
{"Z-Type", "Truffade", "Truffade Z-Type", 758895617, gameplay.get_hash_key("ztype"), "Sports Classics"},
{"811", "Pfister", "Pfister 811", 2465164804, gameplay.get_hash_key("pfister811"), "Super"},
{"Adder", "Truffade", "Truffade Adder", 3078201489, gameplay.get_hash_key("adder"), "Super"},
{"Autarch", "Overflod", "Overflod Autarch", 3981782132, gameplay.get_hash_key("autarch"), "Super"},
{"Banshee 900R", "Bravado", "Bravado Banshee 900R", 633712403, gameplay.get_hash_key("banshee2"), "Super"},
{"Bullet", "Vapid", "Vapid Bullet", 2598821281, gameplay.get_hash_key("bullet"), "Super"},
{"Champion", "Dewbauchee", "Dewbauchee Champion", 3379732821, gameplay.get_hash_key("champion"), "Super"},
{"Cheetah", "Grotti", "Grotti Cheetah", 2983812512, gameplay.get_hash_key("cheetah"), "Super"},
{"Cyclone", "Coil", "Coil Cyclone", 1392481335, gameplay.get_hash_key("cyclone"), "Super"},
{"Deveste Eight", "Principe", "Principe Deveste Eight", 1591739866, gameplay.get_hash_key("deveste"), "Super"},
{"Emerus", "Progen", "Progen Emerus", 1323778901, gameplay.get_hash_key("emerus"), "Super"},
{"Entity XF", "Overflod", "Overflod Entity XF", 3003014393, gameplay.get_hash_key("entityxf"), "Super"},
{"Entity XXR", "Overflod", "Overflod Entity XXR", 2174267100, gameplay.get_hash_key("entity2"), "Super"},
{"ETR1", "Emperor", "Emperor ETR1", 819197656, gameplay.get_hash_key("sheava"), "Super"},
{"FMJ", "Vapid", "Vapid FMJ", 1426219628, gameplay.get_hash_key("fmj"), "Super"},
{"Furia", "Grotti", "Grotti Furia", 960812448, gameplay.get_hash_key("furia"), "Super"},
{"GP1", "Progen", "Progen GP1", 1234311532, gameplay.get_hash_key("gp1"), "Super"},
{"Ignus", "Pegassi", "Pegassi Ignus", 2850852987, gameplay.get_hash_key("ignus"), "Super"},
{"Infernus", "Pegassi", "Pegassi Infernus", 418536135, gameplay.get_hash_key("infernus"), "Super"},
{"Itali GTB", "Progen", "Progen Itali GTB", 2246633323, gameplay.get_hash_key("italigtb"), "Super"},
{"Itali GTB Custom", "Progen", "Progen Itali GTB Custom", 3812247419, gameplay.get_hash_key("italigtb2"), "Super"},
{"Krieger", "Benefactor", "Benefactor Krieger", 3630826055, gameplay.get_hash_key("krieger"), "Super"},
{"Nero", "Truffade", "Truffade Nero", 1034187331, gameplay.get_hash_key("nero"), "Super"},
{"Nero Custom", "Truffade", "Truffade Nero Custom", 1093792632, gameplay.get_hash_key("nero2"), "Super"},
{"Osiris", "Pegassi", "Pegassi Osiris", 1987142870, gameplay.get_hash_key("osiris"), "Super"},
{"Penetrator", "Ocelot", "Ocelot Penetrator", 2536829930, gameplay.get_hash_key("penetrator"), "Super"},
{"RE-7B", "Annis", "Annis RE-7B", 3062131285, gameplay.get_hash_key("le7b"), "Super"},
{"Reaper", "Pegassi", "Pegassi Reaper", 234062309, gameplay.get_hash_key("reaper"), "Super"},
{"Rocket Voltic", "Coil", "Coil Rocket Voltic", 989294410, gameplay.get_hash_key("voltic2"), "Super"},
{"S80RR", "Annis", "Annis S80RR", 3970348707, gameplay.get_hash_key("s80"), "Super"},
{"SC1", "Ubermacht", "Ubermacht SC1", 1352136073, gameplay.get_hash_key("sc1"), "Super"},
{"Scramjet", "Declasse", "Declasse Scramjet", 3656405053, gameplay.get_hash_key("scramjet"), "Super"},
{"Sultan RS", "Karin", "Karin Sultan RS", 3999278268, gameplay.get_hash_key("sultanrs"), "Super"},
{"T20", "Progen", "Progen T20", 1663218586, gameplay.get_hash_key("t20"), "Super"},
{"Taipan", "Cheval", "Cheval Taipan", 3160260734, gameplay.get_hash_key("taipan"), "Super"},
{"Tempesta", "Pegassi", "Pegassi Tempesta", 272929391, gameplay.get_hash_key("tempesta"), "Super"},
{"Tezeract", "Pegassi", "Pegassi Tezeract", 1031562256, gameplay.get_hash_key("tezeract"), "Super"},
{"Thrax", "Truffade", "Truffade Thrax", 1044193113, gameplay.get_hash_key("thrax"), "Super"},
{"Tigon", "Lampadati", "Lampadati Tigon", 2936769864, gameplay.get_hash_key("tigon"), "Super"},
{"Turismo R", "Grotti", "Grotti Turismo R", 408192225, gameplay.get_hash_key("turismor"), "Super"},
{"Tyrant", "Overflod", "Overflod Tyrant", 3918533058, gameplay.get_hash_key("tyrant"), "Super"},
{"Tyrus", "Progen", "Progen Tyrus", 2067820283, gameplay.get_hash_key("tyrus"), "Super"},
{"Vacca", "Pegassi", "Pegassi Vacca", 338562499, gameplay.get_hash_key("vacca"), "Super"},
{"Vagner", "Dewbauchee", "Dewbauchee Vagner", 1939284556, gameplay.get_hash_key("vagner"), "Super"},
{"Vigilante", "Grotti", "Grotti Vigilante", 3052358707, gameplay.get_hash_key("vigilante"), "Super"},
{"Visione", "Grotti", "Grotti Visione", 3296789504, gameplay.get_hash_key("visione"), "Super"},
{"Voltic", "Coil", "Coil Voltic", 2672523198, gameplay.get_hash_key("voltic"), "Super"},
{"X80 Proto", "Grotti", "Grotti X80 Proto", 2123327359, gameplay.get_hash_key("prototipo"), "Super"},
{"XA-21", "Ocelot", "Ocelot XA-21", 917809321, gameplay.get_hash_key("xa21"), "Super"},
{"Zeno", "Overflod", "Overflod Zeno", 655665811, gameplay.get_hash_key("zeno"), "Super"},
{"Zentorno", "Pegassi", "Pegassi Zentorno", 2891838741, gameplay.get_hash_key("zentorno"), "Super"},
{"Zorrusso", "Pegassi", "Pegassi Zorrusso", 3612858749, gameplay.get_hash_key("zorrusso"), "Super"},
{"Astron", "Pfister", "Pfister Astron", 629969764, gameplay.get_hash_key("astron"), "SUVs"},
{"Baller", "Gallivanter", "Gallivanter Baller", 3486135912, gameplay.get_hash_key("baller"), "SUVs"},
{"Baller 2", "Gallivanter", "Gallivanter Baller 2", 142944341, gameplay.get_hash_key("baller2"), "SUVs"},
{"Baller LE", "Gallivanter", "Gallivanter Baller LE", 1878062887, gameplay.get_hash_key("baller3"), "SUVs"},
{"Baller LE (Armored)", "Gallivanter", "Gallivanter Baller LE (Armored)", 470404958, gameplay.get_hash_key("baller5"), "SUVs"},
{"Baller LE LWB", "Gallivanter", "Gallivanter Baller LE LWB", 634118882, gameplay.get_hash_key("baller4"), "SUVs"},
{"Baller LE LWB (Armored)", "Gallivanter", "Gallivanter Baller LE LWB (Armored)", 666166960, gameplay.get_hash_key("baller6"), "SUVs"},
{"Baller ST", "Gallivanter", "Gallivanter Baller ST", 359875117, gameplay.get_hash_key("baller7"), "SUVs"},
{"BeeJay XL", "Karin", "Karin BeeJay XL", 850565707, gameplay.get_hash_key("bjxl"), "SUVs"},
{"Cavalcade", "Albany", "Albany Cavalcade", 2006918058, gameplay.get_hash_key("cavalcade"), "SUVs"},
{"Cavalcade 2", "Albany", "Albany Cavalcade 2", 3505073125, gameplay.get_hash_key("cavalcade2"), "SUVs"},
{"Contender", "Vapid", "Vapid Contender", 683047626, gameplay.get_hash_key("contender"), "SUVs"},
{"Dubsta", "Benefactor", "Benefactor Dubsta", 1177543287, gameplay.get_hash_key("dubsta"), "SUVs"},
{"Dubsta 2", "Benefactor", "Benefactor Dubsta 2", 3900892662, gameplay.get_hash_key("dubsta2"), "SUVs"},
{"FQ 2", "Fathom", "Fathom FQ 2", 3157435195, gameplay.get_hash_key("fq2"), "SUVs"},
{"Granger", "Declasse", "Declasse Granger", 2519238556, gameplay.get_hash_key("granger"), "SUVs"},
{"Granger 3600LX", "Declasse", "Declasse Granger 3600LX", 4033620423, gameplay.get_hash_key("granger2"), "SUVs"},
{"Gresley", "Bravado", "Bravado Gresley", 2751205197, gameplay.get_hash_key("gresley"), "SUVs"},
{"Habanero", "Emperor", "Emperor Habanero", 884422927, gameplay.get_hash_key("habanero"), "SUVs"},
{"Huntley S", "Enus", "Enus Huntley S", 486987393, gameplay.get_hash_key("huntley"), "SUVs"},
{"I-Wagen", "Obey", "Obey I-Wagen", 662793086, gameplay.get_hash_key("iwagen"), "SUVs"},
{"Jubilee", "Enus", "Enus Jubilee", 461465043, gameplay.get_hash_key("jubilee"), "SUVs"},
{"Landstalker", "Dundreary", "Dundreary Landstalker", 1269098716, gameplay.get_hash_key("landstalker"), "SUVs"},
{"Landstalker XL", "Dundreary", "Dundreary Landstalker XL", 3456868130, gameplay.get_hash_key("landstalker2"), "SUVs"},
{"Mesa", "Canis", "Canis Mesa", 914654722, gameplay.get_hash_key("mesa"), "SUVs"},
{"Mesa 2", "Canis", "Canis Mesa 2", 3546958660, gameplay.get_hash_key("mesa2"), "SUVs"},
{"Novak", "Lampadati", "Lampadati Novak", 2465530446, gameplay.get_hash_key("novak"), "SUVs"},
{"Patriot", "Mammoth", "Mammoth Patriot", 3486509883, gameplay.get_hash_key("patriot"), "SUVs"},
{"Patriot Stretch", "Mammoth", "Mammoth Patriot Stretch", 3874056184, gameplay.get_hash_key("patriot2"), "SUVs"},
{"Radius", "Vapid", "Vapid Radius", 2643899483, gameplay.get_hash_key("radi"), "SUVs"},
{"Rebla GTS", "Ubermacht", "Ubermacht Rebla GTS", 83136452, gameplay.get_hash_key("rebla"), "SUVs"},
{"Rocoto", "Obey", "Obey Rocoto", 2136773105, gameplay.get_hash_key("rocoto"), "SUVs"},
{"Seminole", "Canis", "Canis Seminole", 1221512915, gameplay.get_hash_key("seminole"), "SUVs"},
{"Seminole Frontier", "Canis", "Canis Seminole Frontier", 2484160806, gameplay.get_hash_key("seminole2"), "SUVs"},
{"Serrano", "Benefactor", "Benefactor Serrano", 1337041428, gameplay.get_hash_key("serrano"), "SUVs"},
{"Squaddie", "Mammoth", "Mammoth Squaddie", 4192631813, gameplay.get_hash_key("squaddie"), "SUVs"},
{"Toros", "Pegassi", "Pegassi Toros", 3126015148, gameplay.get_hash_key("toros"), "SUVs"},
{"XLS", "Benefactor", "Benefactor XLS", 1203490606, gameplay.get_hash_key("xls"), "SUVs"},
{"XLS (Armored)", "Benefactor", "Benefactor XLS (Armored)", 3862958888, gameplay.get_hash_key("xls2"), "SUVs"},
{"Cable Car", "", "Cable Car", 3334677549, gameplay.get_hash_key("cablecar"), "Trains"},
{"Freight Train", "", "Freight Train", 184361638, gameplay.get_hash_key("freightcar"), "Trains"},
{"Freight Train 2", "", "Freight Train 2", 3186376089, gameplay.get_hash_key("freightcar2"), "Trains"},
{"Freight Train 3", "", "Freight Train 3", 1030400667, gameplay.get_hash_key("freight"), "Trains"},
{"Freight Train Container", "", "Freight Train Container", 920453016, gameplay.get_hash_key("freightcont1"), "Trains"},
{"Freight Train Container 2", "", "Freight Train Container 2", 240201337, gameplay.get_hash_key("freightcont2"), "Trains"},
{"Freight Train Grain", "", "Freight Train Grain", 642617954, gameplay.get_hash_key("freightgrain"), "Trains"},
{"Freight Train Metro", "", "Freight Train Metro", 868868440, gameplay.get_hash_key("metrotrain"), "Trains"},
{"Freight Train Tanker", "", "Freight Train Tanker", 586013744, gameplay.get_hash_key("tankercar"), "Trains"},
{"Airtug", "HYV", "HYV Airtug", 1560980623, gameplay.get_hash_key("airtug"), "Utility"},
{"anker 2", "", "anker 2", 1956216962, gameplay.get_hash_key("tanker2"), "Utility"},
{"Army Tanker", "", "Army Tanker", 3087536137, gameplay.get_hash_key("armytanker"), "Utility"},
{"Army Trailer", "", "Army Trailer", 2818520053, gameplay.get_hash_key("armytrailer"), "Utility"},
{"Army Trailer 2", "", "Army Trailer 2", 2657817814, gameplay.get_hash_key("armytrailer2"), "Utility"},
{"Baletrailer", "", "Baletrailer", 3895125590, gameplay.get_hash_key("baletrailer"), "Utility"},
{"Boat Trailer", "", "Boat Trailer", 524108981, gameplay.get_hash_key("boattrailer"), "Utility"},
{"Caddy", "Nagasaki", "Nagasaki Caddy", 1147287684, gameplay.get_hash_key("caddy"), "Utility"},
{"Caddy 2", "Nagasaki", "Nagasaki Caddy 2", 3757070668, gameplay.get_hash_key("caddy2"), "Utility"},
{"Caddy 3", "Nagasaki", "Nagasaki Caddy 3", 3525819835, gameplay.get_hash_key("caddy3"), "Utility"},
{"Docktug", "HYV", "HYV Docktug", 3410276810, gameplay.get_hash_key("docktug"), "Utility"},
{"Fieldmaster 2", "Stanley", "Stanley Fieldmaster 2", 2218488798, gameplay.get_hash_key("tractor2"), "Utility"},
{"Fieldmaster 3", "Stanley", "Stanley Fieldmaster 3", 1445631933, gameplay.get_hash_key("tractor3"), "Utility"},
{"Forklift", "HVY", "HVY Forklift", 1491375716, gameplay.get_hash_key("forklift"), "Utility"},
{"Lawn Mower", "Jack Sheepe", "Jack Sheepe Lawn Mower", 1783355638, gameplay.get_hash_key("mower"), "Utility"},
{"Mobile Operations Center", "Pegasus", "Pegasus Mobile Operations Center", 1502869817, gameplay.get_hash_key("trailerlarge"), "Utility"},
{"Dock Trailer", "", "Dock Trailer", 2154757102, gameplay.get_hash_key("docktrailer"), "Utility"},
{"Prop Trailer", "", "Prop Trailer", 356391690, gameplay.get_hash_key("proptrailer"), "Utility"},
{"Train Trailer", "", "Train Trailer", 1019737494, gameplay.get_hash_key("graintrailer"), "Utility"},
{"Freight Trailer", "", "Freight Trailer", 3517691494, gameplay.get_hash_key("freighttrailer"), "Utility"},
{"Ripley", "HYV", "HYV Ripley", 3448987385, gameplay.get_hash_key("ripley"), "Utility"},
{"Sadler", "Vapid", "Vapid Sadler", 3695398481, gameplay.get_hash_key("sadler"), "Utility"},
{"Sadler 2", "Vapid", "Vapid Sadler 2", 734217681, gameplay.get_hash_key("sadler2"), "Utility"},
{"Scrap Truck", "Vapid", "Vapid Scrap Truck", 2594165727, gameplay.get_hash_key("scrap"), "Utility"},
{"Slamtruck", "Vapid", "Vapid Slamtruck", 3249056020, gameplay.get_hash_key("slamtruck"), "Utility"},
{"Towtruck", "Vapid", "Vapid Towtruck", 2971866336, gameplay.get_hash_key("towtruck"), "Utility"},
{"Towtruck 2", "Vapid", "Vapid Towtruck 2", 3852654278, gameplay.get_hash_key("towtruck2"), "Utility"},
{"Tractor", "Stanley", "Stanley Tractor", 1641462412, gameplay.get_hash_key("tractor"), "Utility"},
{"Trailer", "", "Trailer", 3194418602, gameplay.get_hash_key("trailers4"), "Utility"},
{"Trailer 2", "", "Trailer 2", 2715434129, gameplay.get_hash_key("trailers2"), "Utility"},
{"Trailer 3", "", "Trailer 3", 2236089197, gameplay.get_hash_key("trailers3"), "Utility"},
{"Trailer 4", "", "Trailer 4", 2091594960, gameplay.get_hash_key("tr4"), "Utility"},
{"Trailer Car Carrier", "", "Trailer Car Carrier", 2078290630, gameplay.get_hash_key("tr2"), "Utility"},
{"Trailer Covered", "", "Trailer Covered", 3417488910, gameplay.get_hash_key("trailers"), "Utility"},
{"Trailer Cultivator", "", "Trailer Cultivator", 390902130, gameplay.get_hash_key("raketrailer"), "Utility"},
{"Trailer Fame or Shame", "", "Trailer Fame or Shame", 2524324030, gameplay.get_hash_key("tvtrailer"), "Utility"},
{"Trailer Flatbed", "", "Trailer Flatbed", 2942498482, gameplay.get_hash_key("trflat"), "Utility"},
{"Trailer Logs", "", "Trailer Logs", 2016027501, gameplay.get_hash_key("trailerlogs"), "Utility"},
{"Trailer Marquis", "", "Trailer Marquis", 1784254509, gameplay.get_hash_key("tr3"), "Utility"},
{"Trailer Small", "", "Trailer Small", 712162987, gameplay.get_hash_key("trailersmall"), "Utility"},
{"Trailer Tanker", "", "Trailer Tanker", 3564062519, gameplay.get_hash_key("tanker"), "Utility"},
{"Utility Truck", "Brute", "Brute Utility Truck", 516990260, gameplay.get_hash_key("utillitruck"), "Utility"},
{"Utility Truck 2", "Brute", "Brute Utility Truck 2", 887537515, gameplay.get_hash_key("utillitruck2"), "Utility"},
{"Utility Truck 3", "Stanley", "Stanley Utility Truck 3", 2132890591, gameplay.get_hash_key("utillitruck3"), "Utility"},
{"Armored Boxville", "Brute", "Brute Armored Boxville", 682434785, gameplay.get_hash_key("boxville5"), "Vans"},
{"Bison", "Bravado", "Bravado Bison", 4278019151, gameplay.get_hash_key("bison"), "Vans"},
{"Bison 2", "Bravado", "Bravado Bison 2", 2072156101, gameplay.get_hash_key("bison2"), "Vans"},
{"Bison 3", "Bravado", "Bravado Bison 3", 1739845664, gameplay.get_hash_key("bison3"), "Vans"},
{"Bobcat XL", "Vapid", "Vapid Bobcat XL", 1069929536, gameplay.get_hash_key("bobcatxl"), "Vans"},
{"Boxville", "Brute", "Brute Boxville", 2307837162, gameplay.get_hash_key("boxville"), "Vans"},
{"Boxville 2", "Brute ", "Brute  Boxville 2", 4061868990, gameplay.get_hash_key("boxville2"), "Vans"},
{"Boxville 3", "Brute", "Brute Boxville 3", 121658888, gameplay.get_hash_key("boxville3"), "Vans"},
{"Boxville 4", "Brute", "Brute Boxville 4", 444171386, gameplay.get_hash_key("boxville4"), "Vans"},
{"Bugstars Burrito", "Declasse", "Declasse Bugstars Burrito", 3387490166, gameplay.get_hash_key("burrito2"), "Vans"},
{"Burrito", "Declasse", "Declasse Burrito", 2948279460, gameplay.get_hash_key("burrito"), "Vans"},
{"Burrito 3", "Declasse", "Declasse Burrito 3", 2551651283, gameplay.get_hash_key("burrito3"), "Vans"},
{"Burrito 4", "Declasse", "Declasse Burrito 4", 893081117, gameplay.get_hash_key("burrito4"), "Vans"},
{"Burrito 5", "Declasse", "Declasse Burrito 5", 1132262048, gameplay.get_hash_key("burrito5"), "Vans"},
{"Camper", "Brute", "Brute Camper", 1876516712, gameplay.get_hash_key("camper"), "Vans"},
{"Clown Van", "Vapid", "Vapid Clown Van", 728614474, gameplay.get_hash_key("speedo2"), "Vans"},
{"Gang Burrito", "Declasse", "Declasse Gang Burrito", 2549763894, gameplay.get_hash_key("gburrito"), "Vans"},
{"Gang Burrito 2", "Declasse", "Declasse Gang Burrito 2", 296357396, gameplay.get_hash_key("gburrito2"), "Vans"},
{"Journey", "Zirconium", "Zirconium Journey", 4174679674, gameplay.get_hash_key("journey"), "Vans"},
{"Minivan", "Vapid", "Vapid Minivan", 3984502180, gameplay.get_hash_key("minivan"), "Vans"},
{"Minivan Custom", "Vapid", "Vapid Minivan Custom", 3168702960, gameplay.get_hash_key("minivan2"), "Vans"},
{"Paradise", "Bravado", "Bravado Paradise", 1488164764, gameplay.get_hash_key("paradise"), "Vans"},
{"Pony", "Brute", "Brute Pony", 4175309224, gameplay.get_hash_key("pony"), "Vans"},
{"Pony 2", "Brute", "Brute Pony 2", 943752001, gameplay.get_hash_key("pony2"), "Vans"},
{"Rumpo", "Bravado", "Bravado Rumpo", 1162065741, gameplay.get_hash_key("rumpo"), "Vans"},
{"Rumpo 2", "Bravado", "Bravado Rumpo 2", 2518351607, gameplay.get_hash_key("rumpo2"), "Vans"},
{"Rumpo Custom", "Bravado", "Bravado Rumpo Custom", 1475773103, gameplay.get_hash_key("rumpo3"), "Vans"},
{"Speedo", "Vapid", "Vapid Speedo", 3484649228, gameplay.get_hash_key("speedo"), "Vans"},
{"Speedo Custom", "Vapid", "Vapid Speedo Custom", 219613597, gameplay.get_hash_key("speedo4"), "Vans"},
{"Surfer", "BF", "BF Surfer", 699456151, gameplay.get_hash_key("surfer"), "Vans"},
{"Surfer 2", "BF", "BF Surfer 2", 2983726598, gameplay.get_hash_key("surfer2"), "Vans"},
{"Taco Van", "Brute", "Brute Taco Van", 1951180813, gameplay.get_hash_key("taco"), "Vans"},
{"Youga", "Bravado", "Bravado Youga", 65402552, gameplay.get_hash_key("youga"), "Vans"},
{"Youga Classic", "Bravado", "Bravado Youga Classic", 1026149675, gameplay.get_hash_key("youga2"), "Vans"},
{"Youga Classic 4x4", "Bravado", "Bravado Youga Classic 4x4", 1802742206, gameplay.get_hash_key("youga3"), "Vans"},
{"Youga Custom", "Vapid", "Vapid Youga Custom", 1486521356, gameplay.get_hash_key("youga4"), "Vans"},
}--retarded sparrow removed


_GT_veh_grief_hash_list = {
{gameplay.get_hash_key("avenger"),		false,"Avenger"},					--1
{gameplay.get_hash_key("avenger2"),		false,"Avenger"},				--2
{gameplay.get_hash_key("savage"),		false,"Savage"},					--3
{gameplay.get_hash_key("buzzard"),		false,"Buzzard Attack Chopper"},	--4
{gameplay.get_hash_key("akula"),		false,"Akula"},						--5
{gameplay.get_hash_key("hunter"),		false,"FH-1 Hunter"},				--6
{gameplay.get_hash_key("hydra"),		false,"Hydra"},						--7
{gameplay.get_hash_key("lazer"),		false,"P-996 LAZER"},				--8
{gameplay.get_hash_key("nokota"),		false,"P-45 Nokota"},				--9
{gameplay.get_hash_key("seabreeze"),	false,"Seabreeze"},				--10
{gameplay.get_hash_key("rogue"),		false,"Rogue"},						--11
{gameplay.get_hash_key("molotok"),		false,"V-65 Molotok"},			--12
{gameplay.get_hash_key("strikeforce"),	false,"B-11 Strikeforce"},	--13
{gameplay.get_hash_key("oppressor"),	false,"Oppressor"},				--14
{gameplay.get_hash_key("oppressor2"),	false,"Oppressor Mk2"},		--15
{gameplay.get_hash_key("deluxo"),		false,"Deluxo"},					--16
{gameplay.get_hash_key("toreador"),		false,"Toreador"},				--17
{gameplay.get_hash_key("rhino"),		false,"Rhino Tank"},				--18
{gameplay.get_hash_key("khanjali"),		false,"TM-02 Khanjali"},			--19
{gameplay.get_hash_key("menacer"),		false,"Menacer"},					--20
{gameplay.get_hash_key("nightshark"),	false,"Nightshark"},			--21
{gameplay.get_hash_key("insurgent3"),	false,"Insurgent Custom"},		--22
{gameplay.get_hash_key("phantom2"),		false,"Phantom Wedge"},			--23
{gameplay.get_hash_key("dune5"),		false,"Ramp Buggy"},				--24
{gameplay.get_hash_key("dune4"),		false,"Ramp Buggy"},				--25
}

_GT_veh_hash_true_name = {}

	-- _G_int_for_start = 0
-- _G_veh_has_record=menu.add_feature("Record vehicle hash and name","action_value_i",0,function(f) crash after around 100-300 so i had to break it up
	-- _GT_all_veh_hash = vehicle.get_all_vehicle_model_hashes()
	-- local veh,msg,file
	-- local last_i = 0
	-- -- while f.on do
		-- -- system.yield(0)
		-- for i=1, #_GT_all_veh_hash do
			-- if i > f.value and i <= _G_veh_has_record_end.value then
				-- _GF_req_stream_hash(_GT_all_veh_hash[i])
				-- veh = vehicle.create_vehicle(_GT_all_veh_hash[i], player.get_player_coords(player.player_id())+v3(math.random(-100,100),math.random(-100,100),math.random(50,75)), 0.0, false, false)
				-- system.yield(25)
				-- msg = "\n".._GT_all_veh_hash[i]..", ".._GF_model_name(veh)..", ".._GF_class_name(veh)..", ".._GF_brand_name(veh)
				-- file=io.open(utils.get_appdata_path("PopstarDevs", "").."\\2Take1Menu\\scripts\\GeeSkid\\veh_hash_name.cfg","a")
				-- file:write(msg)
				-- file:close()
				-- system.yield(25)
				-- entity.set_entity_as_no_longer_needed(veh)
				-- system.yield(25)
				-- _GF_delete(veh, 100)
				-- system.yield(25)
				-- last_i=i
			-- end
		-- end
		-- menu.notify("Complete "..last_i.."",_G_GeeVer,4,2)
	-- --end
-- end)
-- _G_veh_has_record.max=700
-- _G_veh_has_record.min=0
-- _G_veh_has_record.mod=25

-- _G_veh_has_record_end=menu.add_feature("veh hash limit","action_value_i",0,function(f)

-- end)
-- _G_veh_has_record_end.max=1000
-- _G_veh_has_record_end.min=0
-- _G_veh_has_record_end.mod=25
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	